//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyWorkChg
    {
        public System.DateTime ag_date { get; set; }
        public string ag_dpno { get; set; }
        public string ag_emno { get; set; }
        public string ag_cname { get; set; }
        public Nullable<System.DateTime> ag_osdate { get; set; }
        public Nullable<System.DateTime> ag_oedate { get; set; }
        public decimal ag_ohour { get; set; }
        public Nullable<System.DateTime> ag_sdate { get; set; }
        public Nullable<System.DateTime> ag_edate { get; set; }
        public decimal ag_hour { get; set; }
        public System.DateTime ag_update { get; set; }
        public string ag_upemno { get; set; }
        public string ag_reason { get; set; }
    }
}
