//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyWork
    {
        public System.DateTime ak_date { get; set; }
        public string ak_dpno { get; set; }
        public string ak_emno { get; set; }
        public string ak_cname { get; set; }
        public Nullable<decimal> ak_yn { get; set; }
        public Nullable<decimal> ak_yn0 { get; set; }
        public Nullable<decimal> ak_yn1 { get; set; }
        public Nullable<decimal> ak_yn2 { get; set; }
        public Nullable<System.DateTime> ak_update { get; set; }
        public string ak_upemno { get; set; }
        public Nullable<System.DateTime> ak_sdate { get; set; }
        public Nullable<System.DateTime> ak_edate { get; set; }
        public decimal ak_hour { get; set; }
        public string ak_content { get; set; }
        public Nullable<decimal> ak_verify { get; set; }
        public string ak_vername { get; set; }
        public decimal ak_holiday { get; set; }
        public Nullable<System.DateTime> ak_vdate { get; set; }
        public decimal ak_power { get; set; }
    }
}
