//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applybuyB
    {
        public string ab_mkno { get; set; }
        public decimal ab_item { get; set; }
        public string ab_mtno { get; set; }
        public Nullable<decimal> ab_long { get; set; }
        public Nullable<decimal> ab_width { get; set; }
        public Nullable<decimal> ab_amount { get; set; }
        public decimal ab_accamt { get; set; }
        public Nullable<System.DateTime> ab_date { get; set; }
        public string ab_suno { get; set; }
        public Nullable<decimal> ab_price { get; set; }
        public string ab_payunit { get; set; }
        public string ab_memo { get; set; }
        public Nullable<decimal> ab_yn2 { get; set; }
        public string ab_emno2 { get; set; }
        public string ab_cname2 { get; set; }
        public Nullable<System.DateTime> ab_vdate2 { get; set; }
        public Nullable<decimal> ab_yn3 { get; set; }
        public string ab_emno3 { get; set; }
        public string ab_cname3 { get; set; }
        public Nullable<System.DateTime> ab_vdate3 { get; set; }
        public Nullable<decimal> ab_yn4 { get; set; }
        public string ab_emno4 { get; set; }
        public string ab_cname4 { get; set; }
        public Nullable<System.DateTime> ab_vdate4 { get; set; }
        public Nullable<decimal> ab_close { get; set; }
        public string ab_curr { get; set; }
        public string ab_reason { get; set; }
        public string ab_spec { get; set; }
        public string ab_stno { get; set; }
        public decimal ab_qc { get; set; }
        public decimal ab_seqno { get; set; }
    }
}
