//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applybuy
    {
        public string ab_suno { get; set; }
        public string ab_mtno { get; set; }
        public string ab_mkno { get; set; }
        public Nullable<decimal> ab_long { get; set; }
        public Nullable<decimal> ab_width { get; set; }
        public Nullable<decimal> ab_amount { get; set; }
        public Nullable<System.DateTime> ab_date { get; set; }
        public string ab_emno { get; set; }
        public string ab_emno1 { get; set; }
        public Nullable<System.DateTime> ab_date1 { get; set; }
        public string ab_phno { get; set; }
        public string ab_dpno { get; set; }
        public Nullable<decimal> ab_price { get; set; }
        public Nullable<decimal> ab_accamt { get; set; }
        public string ab_payunit { get; set; }
    }
}
