//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applybuyH
    {
        public string abh_mkno { get; set; }
        public Nullable<decimal> abh_flag { get; set; }
        public string abh_cemno { get; set; }
        public Nullable<System.DateTime> abh_cdate { get; set; }
        public string abh_dpno { get; set; }
        public string abh_phno { get; set; }
        public Nullable<decimal> abh_post { get; set; }
        public Nullable<System.DateTime> abh_postdate { get; set; }
        public Nullable<decimal> abh_yn1 { get; set; }
        public string abh_emno1 { get; set; }
        public string abh_cname1 { get; set; }
        public Nullable<System.DateTime> abh_vdate1 { get; set; }
        public string abh_memo { get; set; }
        public decimal abh_Kind { get; set; }
        public decimal abh_top { get; set; }
        public string abh_imno { get; set; }
        public string abh_dsn { get; set; }
        public decimal abh_printYN { get; set; }
        public string abh_rddsn { get; set; }
        public decimal abh_reason { get; set; }
    }
}
