//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arfeeOther
    {
        public decimal ao_seqno { get; set; }
        public string ao_no { get; set; }
        public string ao_cuno { get; set; }
        public Nullable<System.DateTime> ao_date { get; set; }
        public string ao_kind { get; set; }
        public string ao_content { get; set; }
        public decimal ao_qty { get; set; }
        public decimal ao_price { get; set; }
        public decimal ao_amt { get; set; }
        public string ao_curr { get; set; }
        public string ao_memo { get; set; }
        public string ao_dpno { get; set; }
        public string ao_cemno { get; set; }
        public Nullable<System.DateTime> ao_cdate { get; set; }
        public decimal ao_ver { get; set; }
        public string ao_vemno { get; set; }
        public Nullable<System.DateTime> ao_vdate { get; set; }
        public decimal ao_print { get; set; }
        public decimal ao_post { get; set; }
        public Nullable<System.DateTime> ao_postdate { get; set; }
        public decimal ao_inv { get; set; }
        public decimal ao_ocserial { get; set; }
        public string ao_ChgMemo { get; set; }
    }
}
