//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asseth
    {
        public string compid { get; set; }
        public string ash_no { get; set; }
        public string ash_cname { get; set; }
        public string ash_ename { get; set; }
        public string ash_place { get; set; }
        public Nullable<System.DateTime> ash_date { get; set; }
        public string ash_unit { get; set; }
        public Nullable<decimal> ash_qty { get; set; }
        public Nullable<decimal> ash_year { get; set; }
        public Nullable<decimal> ash_type { get; set; }
        public Nullable<decimal> ash_amt1 { get; set; }
        public Nullable<decimal> ash_amt2 { get; set; }
        public Nullable<decimal> ash_amt3 { get; set; }
        public Nullable<decimal> ash_amt4 { get; set; }
        public string ash_macno1 { get; set; }
        public string ash_macno2 { get; set; }
        public string ash_macno3 { get; set; }
        public Nullable<System.DateTime> ash_date1 { get; set; }
        public Nullable<System.DateTime> ash_date2 { get; set; }
        public Nullable<decimal> ash_amt5 { get; set; }
        public Nullable<decimal> ash_taxamt { get; set; }
        public string ash_macno4 { get; set; }
        public string ash_vhno { get; set; }
        public string ash_vbskey { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
