//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachb
    {
        public string compid { get; set; }
        public string atb_vhno { get; set; }
        public string atb_vbskey { get; set; }
        public string atb_skey { get; set; }
        public Nullable<System.DateTime> atb_vhdate { get; set; }
        public string atb_no { get; set; }
        public Nullable<decimal> atb_money { get; set; }
        public Nullable<decimal> atb_amoney { get; set; }
        public string atb_10 { get; set; }
        public string atb_descs { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
