//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class badpro
    {
        public string bo_yymm { get; set; }
        public string bo_no { get; set; }
        public decimal bo_kind { get; set; }
        public string bo_mkno { get; set; }
        public string bo_setno { get; set; }
        public string bo_mnno { get; set; }
        public Nullable<decimal> bo_colamt { get; set; }
        public Nullable<decimal> bo_lyn { get; set; }
        public Nullable<decimal> bo_cutamt { get; set; }
        public Nullable<decimal> bo_badamt { get; set; }
        public Nullable<decimal> bo_lost { get; set; }
        public string bo_dpunit { get; set; }
        public string bo_dpno1 { get; set; }
        public string bo_dpno2 { get; set; }
        public string bo_dpno3 { get; set; }
        public string bo_dpno4 { get; set; }
        public string bo_dpno5 { get; set; }
        public string bo_dpno6 { get; set; }
        public Nullable<decimal> bo_dpreat1 { get; set; }
        public Nullable<decimal> bo_dpreat2 { get; set; }
        public Nullable<decimal> bo_dpreat3 { get; set; }
        public Nullable<decimal> bo_dpreat4 { get; set; }
        public Nullable<decimal> bo_dpreat5 { get; set; }
        public Nullable<decimal> bo_dpreat6 { get; set; }
        public string bo_emno1 { get; set; }
        public string bo_emno2 { get; set; }
        public string bo_emno3 { get; set; }
        public string bo_emno4 { get; set; }
        public string bo_emno5 { get; set; }
        public string bo_emno6 { get; set; }
        public string bo_memo { get; set; }
        public string bo_ws { get; set; }
        public string bo_badunit { get; set; }
        public string bo_suno1 { get; set; }
        public string bo_suno2 { get; set; }
        public string bo_suno3 { get; set; }
        public string bo_suno4 { get; set; }
        public string bo_suno5 { get; set; }
        public string bo_suno6 { get; set; }
        public string bo_suname1 { get; set; }
        public string bo_suname2 { get; set; }
        public string bo_suname3 { get; set; }
        public string bo_suname4 { get; set; }
        public string bo_suname5 { get; set; }
        public string bo_suname6 { get; set; }
        public decimal bo_risk { get; set; }
    }
}
