//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bascolor_TC
    {
        public string bc_setno { get; set; }
        public string bc_chno { get; set; }
        public decimal bc_seq { get; set; }
        public string bc_num { get; set; }
        public Nullable<decimal> bc_kind { get; set; }
        public decimal bc_qty { get; set; }
        public string bc_memo { get; set; }
        public decimal bc_filmqty { get; set; }
        public decimal bc_centerline { get; set; }
        public decimal bc_colnum { get; set; }
        public string bc_setno1 { get; set; }
        public Nullable<System.DateTime> bc_cdate { get; set; }
        public decimal bc_optics { get; set; }
    }
}
