//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basepayF
    {
        public string bf_fnno { get; set; }
        public string bf_ceno { get; set; }
        public decimal bf_11 { get; set; }
        public decimal bf_12 { get; set; }
        public decimal bf_21 { get; set; }
        public decimal bf_22 { get; set; }
        public decimal bf_26 { get; set; }
        public decimal bf_27 { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public int bf_explain { get; set; }
    }
}
