//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basset
    {
        public string bs_setno { get; set; }
        public Nullable<decimal> bs_mono { get; set; }
        public string bs_prno { get; set; }
        public string bs_size { get; set; }
        public string bs_machine { get; set; }
        public Nullable<decimal> bs_time { get; set; }
        public string bs_pbno { get; set; }
        public Nullable<decimal> bs_shanum { get; set; }
        public Nullable<decimal> bs_repnum { get; set; }
        public string bs_wno { get; set; }
        public Nullable<System.DateTime> bs_date { get; set; }
        public string bs_emno { get; set; }
        public Nullable<System.DateTime> bs_update { get; set; }
        public Nullable<System.DateTime> bs_date1 { get; set; }
        public string bs_pno { get; set; }
        public Nullable<decimal> bs_plen { get; set; }
        public Nullable<decimal> bs_pwid { get; set; }
        public string bs_uno { get; set; }
        public Nullable<decimal> bs_ulen { get; set; }
        public Nullable<decimal> bs_uwid { get; set; }
        public Nullable<decimal> bs_20 { get; set; }
        public string bs_store { get; set; }
        public string bs_netcls { get; set; }
        public Nullable<decimal> bs_share { get; set; }
        public string bs_share1 { get; set; }
        public string bs_share2 { get; set; }
        public string bs_share3 { get; set; }
        public string bs_imgname { get; set; }
        public string bs_dpno { get; set; }
        public decimal bs_modflag { get; set; }
        public string bs_setno2 { get; set; }
        public string bs_mtno1 { get; set; }
        public Nullable<decimal> bs_len1 { get; set; }
        public Nullable<decimal> bs_wid1 { get; set; }
        public string bs_mtno2 { get; set; }
        public Nullable<decimal> bs_len2 { get; set; }
        public Nullable<decimal> bs_wid2 { get; set; }
        public string bs_mtno3 { get; set; }
        public Nullable<decimal> bs_len3 { get; set; }
        public Nullable<decimal> bs_wid3 { get; set; }
        public string bs_mtno4 { get; set; }
        public Nullable<decimal> bs_len4 { get; set; }
        public Nullable<decimal> bs_wid4 { get; set; }
        public string bs_mtno5 { get; set; }
        public Nullable<decimal> bs_len5 { get; set; }
        public Nullable<decimal> bs_wid5 { get; set; }
        public string bs_mtno6 { get; set; }
        public Nullable<decimal> bs_len6 { get; set; }
        public Nullable<decimal> bs_wid6 { get; set; }
        public string bs_mtno7 { get; set; }
        public Nullable<decimal> bs_len7 { get; set; }
        public Nullable<decimal> bs_wid7 { get; set; }
        public decimal bs_cutfont { get; set; }
        public decimal bs_cutfont1 { get; set; }
        public decimal bs_cutfont2 { get; set; }
        public decimal bs_bknife { get; set; }
        public decimal bs_punch { get; set; }
        public string bs_glass { get; set; }
        public decimal bs_uyn { get; set; }
        public decimal bs_checkcolor { get; set; }
        public string bs_memo { get; set; }
        public decimal bs_filmqty { get; set; }
        public decimal bs_knife { get; set; }
        public decimal bs_centerline { get; set; }
        public decimal bs_pprice { get; set; }
        public decimal bs_lock { get; set; }
        public decimal bs_ROHS { get; set; }
        public decimal bs_CPSIA { get; set; }
        public decimal bs_Reach { get; set; }
        public decimal bs_difficulty { get; set; }
        public decimal bs_difficulty_New { get; set; }
        public decimal bs_PrtPlus { get; set; }
        public decimal bs_PrtPlus_New { get; set; }
        public decimal bs_keep { get; set; }
        public decimal bs_kday { get; set; }
        public decimal bs_special { get; set; }
        public decimal bs_PrintLevel { get; set; }
        public int bs_times1 { get; set; }
        public int bs_times2 { get; set; }
        public int bs_times3 { get; set; }
        public decimal bs_BlackCross { get; set; }
    }
}
