//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch
    {
        public System.DateTime bh_date { get; set; }
        public int bh_seqno { get; set; }
        public string bh_note { get; set; }
        public decimal bh_yn1 { get; set; }
        public decimal bh_yn2 { get; set; }
        public Nullable<System.DateTime> bh_cdate { get; set; }
    }
}
