//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bomanad
    {
        public string ba_makno { get; set; }
        public string ba_setno { get; set; }
        public System.DateTime ba_cdate { get; set; }
        public Nullable<decimal> ba_pabay { get; set; }
        public Nullable<decimal> ba_urgy { get; set; }
        public string ba_reason { get; set; }
        public string ba_inno { get; set; }
        public Nullable<System.DateTime> ba_idate { get; set; }
        public Nullable<System.DateTime> ba_rdate { get; set; }
        public string ba_cuno { get; set; }
        public System.DateTime ba_mocdate { get; set; }
    }
}
