//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bomeff
    {
        public string be_yymm { get; set; }
        public string be_dpno { get; set; }
        public string be_cuno { get; set; }
        public string be_setno { get; set; }
        public Nullable<decimal> be_stdamt { get; set; }
        public Nullable<decimal> be_price { get; set; }
        public Nullable<decimal> be_mod { get; set; }
        public Nullable<decimal> be_modcost { get; set; }
        public Nullable<decimal> be_mo { get; set; }
        public Nullable<decimal> be_moqty { get; set; }
        public Nullable<decimal> be_mocost { get; set; }
        public Nullable<decimal> be_del { get; set; }
        public Nullable<decimal> be_delqty { get; set; }
        public Nullable<decimal> be_delamt { get; set; }
        public Nullable<decimal> be_rqty { get; set; }
        public Nullable<decimal> be_rcost { get; set; }
        public Nullable<decimal> be_qty { get; set; }
        public Nullable<decimal> be_amt { get; set; }
        public Nullable<decimal> be_cost { get; set; }
        public Nullable<decimal> be_usage { get; set; }
        public Nullable<decimal> be_net { get; set; }
        public Nullable<decimal> be_eff { get; set; }
    }
}
