//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bomlev3
    {
        public string b3_setno { get; set; }
        public string b3_upno { get; set; }
        public string b3_cuupno { get; set; }
        public string b3_desc { get; set; }
        public Nullable<decimal> b3_qty { get; set; }
        public Nullable<decimal> b3_amt { get; set; }
        public string b3_user { get; set; }
        public Nullable<System.DateTime> b3_date { get; set; }
        public string b3_mykno { get; set; }
        public string b3_ver { get; set; }
        public decimal b3_amt_s { get; set; }
        public decimal b3_weight { get; set; }
    }
}
