//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bomlev2
    {
        public string b2_carno { get; set; }
        public string b2_setno { get; set; }
        public string b2_cusetno { get; set; }
        public string b2_desc { get; set; }
        public Nullable<decimal> b2_qty { get; set; }
        public Nullable<decimal> b2_stdamt { get; set; }
        public Nullable<int> b2_order { get; set; }
        public string b2_user { get; set; }
        public Nullable<System.DateTime> b2_date { get; set; }
        public string b2_no { get; set; }
        public Nullable<System.DateTime> b2_date2 { get; set; }
        public string b2_mykno { get; set; }
        public decimal b2_10 { get; set; }
        public decimal b2_weight { get; set; }
    }
}
