//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BommoEff
    {
        public System.DateTime mf_date { get; set; }
        public string mf_dpno { get; set; }
        public string mf_dpname { get; set; }
        public decimal mf_lastsch { get; set; }
        public decimal mf_lastpaper { get; set; }
        public decimal mf_lastnet { get; set; }
        public decimal mf_lastnp { get; set; }
        public decimal mf_lastpaper1 { get; set; }
        public decimal mf_lastnet1 { get; set; }
        public decimal mf_lastnp1 { get; set; }
        public decimal mf_lastinsert { get; set; }
        public decimal mf_lastprint { get; set; }
        public decimal mf_sch { get; set; }
        public decimal mf_sch_pm11 { get; set; }
        public decimal mf_paper_pm11 { get; set; }
        public decimal mf_net_pm11 { get; set; }
        public decimal mf_yn { get; set; }
        public decimal mf_expu { get; set; }
        public decimal mf_expu_pm11 { get; set; }
        public decimal mf_preSCnt { get; set; }
        public decimal mf_preECnt { get; set; }
    }
}
