//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bommo
    {
        public string mo_setno { get; set; }
        public Nullable<decimal> mo_qty { get; set; }
        public string mo_mkno { get; set; }
        public string mo_carno { get; set; }
        public Nullable<decimal> mo_mpaper { get; set; }
        public System.DateTime mo_date { get; set; }
        public string mo_sloc { get; set; }
        public string mo_mpno { get; set; }
        public Nullable<decimal> mo_code { get; set; }
        public string mo_memo1 { get; set; }
        public string mo_memo2 { get; set; }
        public Nullable<decimal> mo_mend { get; set; }
        public Nullable<decimal> mo_yn { get; set; }
        public System.DateTime mo_cdate { get; set; }
        public string mo_emno { get; set; }
        public Nullable<System.DateTime> mo_opdate { get; set; }
        public string mo_reason { get; set; }
        public string mo_mtno1 { get; set; }
        public string mo_mtno2 { get; set; }
        public string mo_mtno3 { get; set; }
        public Nullable<decimal> mo_in { get; set; }
        public string mo_dpno { get; set; }
        public Nullable<decimal> mo_close { get; set; }
        public Nullable<decimal> mo_post { get; set; }
        public decimal mo_jit { get; set; }
        public decimal mo_jitdpno { get; set; }
        public decimal mo_knife { get; set; }
        public Nullable<System.DateTime> mo_cdate1 { get; set; }
        public Nullable<System.DateTime> mo_postdate { get; set; }
        public Nullable<System.DateTime> mo_schdate1 { get; set; }
        public Nullable<System.DateTime> mo_schdate2 { get; set; }
        public Nullable<System.DateTime> mo_outdate { get; set; }
        public decimal mo_netqty { get; set; }
        public Nullable<System.DateTime> mo_bomdate { get; set; }
        public Nullable<System.DateTime> mo_paperdate { get; set; }
        public Nullable<System.DateTime> mo_coldate { get; set; }
        public Nullable<System.DateTime> mo_preDateS { get; set; }
        public Nullable<System.DateTime> mo_preDateE { get; set; }
        public Nullable<System.DateTime> mo_predate { get; set; }
        public Nullable<System.DateTime> mo_printdate { get; set; }
        public Nullable<System.DateTime> mo_extradate { get; set; }
        public Nullable<System.DateTime> mo_indate { get; set; }
        public Nullable<System.DateTime> mo_ExpPrintOK { get; set; }
        public decimal mo_kind { get; set; }
        public string mo_enno { get; set; }
        public decimal mo_lock { get; set; }
        public string mo_pemno { get; set; }
        public decimal mo_auto { get; set; }
        public decimal mo_inqty { get; set; }
        public decimal mo_stdcarqty { get; set; }
        public decimal mo_DoPost { get; set; }
        public decimal mo_plan { get; set; }
        public string SNO { get; set; }
        public Nullable<System.DateTime> mo_getcard { get; set; }
        public Nullable<System.DateTime> mo_pudate1 { get; set; }
        public Nullable<System.DateTime> mo_pudate2 { get; set; }
        public decimal mo_paperTemp { get; set; }
        public Nullable<System.DateTime> mo_FuncChkTime { get; set; }
        public decimal mo_mono { get; set; }
        public decimal mo_ssqty { get; set; }
        public decimal mo_reqqty { get; set; }
        public decimal mo_adjqty { get; set; }
        public decimal mo_ver { get; set; }
        public string mo_vemno { get; set; }
        public string mo_vname { get; set; }
        public Nullable<System.DateTime> mo_vdate { get; set; }
        public decimal mo_batch { get; set; }
        public decimal mo_batchNo { get; set; }
        public string mo_DelReason { get; set; }
        public decimal mo_plen { get; set; }
        public decimal mo_pwid { get; set; }
        public decimal mo_MakePaper { get; set; }
        public Nullable<System.DateTime> mo_MPDateS { get; set; }
        public Nullable<System.DateTime> mo_MPDateE { get; set; }
        public Nullable<System.DateTime> mo_MPDateSCH { get; set; }
        public decimal mo_MP_get { get; set; }
        public decimal mo_MP_Error { get; set; }
        public decimal mo_MP_charge { get; set; }
        public decimal mo_MP_Cnt { get; set; }
        public string mo_SchReason { get; set; }
        public decimal mo_ICT { get; set; }
        public decimal mo_MP_NG { get; set; }
        public Nullable<int> mo_ColorCnt { get; set; }
        public Nullable<int> mo_OilGCnt { get; set; }
        public Nullable<int> mo_OilRCnt { get; set; }
        public Nullable<System.DateTime> mo_StartPrint { get; set; }
        public Nullable<System.DateTime> mo_SchDate { get; set; }
        public decimal mo_print { get; set; }
        public decimal mo_ver1 { get; set; }
        public string mo_vemno1 { get; set; }
        public string mo_vname1 { get; set; }
        public Nullable<System.DateTime> mo_vdate1 { get; set; }
        public decimal mo_SchConf { get; set; }
        public string mo_SchConf_Emno { get; set; }
        public Nullable<System.DateTime> mo_SchConf_Date { get; set; }
        public Nullable<System.DateTime> mo_deadline { get; set; }
        public string mo_SuppDpno { get; set; }
        public decimal mo_GoodQty { get; set; }
        public int mo_ColorChk1 { get; set; }
        public int mo_ColorChk2 { get; set; }
        public string mo_prno { get; set; }
        public string mo_MPemno { get; set; }
    }
}
