//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomPriceChg
    {
        public decimal bc_seqno { get; set; }
        public string bc_kind { get; set; }
        public string bc_pdno { get; set; }
        public string bc_cupdno { get; set; }
        public string bc_desc { get; set; }
        public string bc_cuno { get; set; }
        public string bc_mykno { get; set; }
        public decimal bc_oprice { get; set; }
        public decimal bc_nprice { get; set; }
        public decimal bc_ostd { get; set; }
        public decimal bc_nstd { get; set; }
        public Nullable<System.DateTime> bc_update { get; set; }
        public string bc_cemno { get; set; }
        public string bc_cname { get; set; }
        public decimal bc_ver { get; set; }
        public string bc_vemno { get; set; }
        public string bc_vname { get; set; }
        public Nullable<System.DateTime> bc_vdate { get; set; }
    }
}
