//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bonusc
    {
        public string bs_yy { get; set; }
        public Nullable<decimal> bs_fintrw { get; set; }
        public Nullable<decimal> bs_rwday { get; set; }
        public Nullable<decimal> bs_dprw1 { get; set; }
        public Nullable<decimal> bs_rwday1 { get; set; }
        public Nullable<decimal> bs_dprw2 { get; set; }
        public Nullable<decimal> bs_rwday2 { get; set; }
        public Nullable<decimal> bs_dprw3 { get; set; }
        public Nullable<decimal> bs_rwday3 { get; set; }
        public Nullable<decimal> bs_dprw4 { get; set; }
        public Nullable<decimal> bs_rwday4 { get; set; }
        public Nullable<decimal> bs_dprw5 { get; set; }
        public Nullable<decimal> bs_rwday5 { get; set; }
        public Nullable<decimal> bs_dprw6 { get; set; }
        public Nullable<decimal> bs_rwday6 { get; set; }
        public Nullable<decimal> bs_dprw7 { get; set; }
        public Nullable<decimal> bs_rwday7 { get; set; }
        public Nullable<decimal> bs_dprw8 { get; set; }
        public Nullable<decimal> bs_rwday8 { get; set; }
        public decimal bs_dprw9 { get; set; }
        public decimal bs_rwday9 { get; set; }
        public decimal bs_dprw10 { get; set; }
        public decimal bs_rwday10 { get; set; }
    }
}
