//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusColor
    {
        public string buc_puno { get; set; }
        public decimal buc_seq { get; set; }
        public string buc_chno { get; set; }
        public Nullable<decimal> buc_kind { get; set; }
        public Nullable<decimal> buc_qty { get; set; }
        public Nullable<System.DateTime> buc_date { get; set; }
        public Nullable<System.DateTime> buc_cdate { get; set; }
        public string buc_emno { get; set; }
        public string buc_memo { get; set; }
    }
}
