//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buybreed
    {
        public string bb_year { get; set; }
        public string bb_month { get; set; }
        public string bb_setno { get; set; }
        public Nullable<decimal> bb_proamt { get; set; }
        public Nullable<decimal> bb_times { get; set; }
        public Nullable<decimal> bb_moamt { get; set; }
        public Nullable<decimal> bb_ptimes { get; set; }
        public Nullable<decimal> bb_long { get; set; }
        public Nullable<decimal> bb_width { get; set; }
        public Nullable<decimal> bb_price { get; set; }
        public string bb_pname { get; set; }
        public Nullable<decimal> bb_maatt { get; set; }
        public Nullable<decimal> bb_ordamt { get; set; }
        public string bb_dpno { get; set; }
    }
}
