//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ca_cabs42_01
    {
        public string ce_no { get; set; }
        public string ce_name { get; set; }
        public Nullable<decimal> A1 { get; set; }
        public Nullable<decimal> A2 { get; set; }
        public Nullable<decimal> A3 { get; set; }
        public Nullable<decimal> B1 { get; set; }
        public Nullable<decimal> B2 { get; set; }
        public Nullable<decimal> B3 { get; set; }
        public Nullable<decimal> C1 { get; set; }
        public Nullable<decimal> C2 { get; set; }
        public Nullable<decimal> C3 { get; set; }
        public Nullable<decimal> D1 { get; set; }
        public Nullable<decimal> D2 { get; set; }
        public Nullable<decimal> D3 { get; set; }
        public Nullable<decimal> E1 { get; set; }
        public Nullable<decimal> E2 { get; set; }
        public Nullable<decimal> E3 { get; set; }
        public Nullable<decimal> F1 { get; set; }
        public Nullable<decimal> F2 { get; set; }
        public Nullable<decimal> F3 { get; set; }
        public Nullable<decimal> G1 { get; set; }
        public Nullable<decimal> G2 { get; set; }
        public Nullable<decimal> G3 { get; set; }
        public Nullable<decimal> H1 { get; set; }
        public Nullable<decimal> H2 { get; set; }
        public Nullable<decimal> H3 { get; set; }
        public Nullable<decimal> I1 { get; set; }
        public Nullable<decimal> I2 { get; set; }
        public Nullable<decimal> I3 { get; set; }
        public Nullable<decimal> J1 { get; set; }
        public Nullable<decimal> J2 { get; set; }
        public Nullable<decimal> J3 { get; set; }
        public Nullable<decimal> K1 { get; set; }
        public Nullable<decimal> K2 { get; set; }
        public Nullable<decimal> K3 { get; set; }
        public Nullable<decimal> L1 { get; set; }
        public Nullable<decimal> L2 { get; set; }
        public Nullable<decimal> L3 { get; set; }
        public Nullable<decimal> M1 { get; set; }
        public Nullable<decimal> M2 { get; set; }
        public Nullable<decimal> M3 { get; set; }
    }
}
