//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ca_cabs43_01
    {
        public string er_yymm { get; set; }
        public string er_emno { get; set; }
        public string em_cname { get; set; }
        public decimal db_cnt { get; set; }
        public decimal db_total { get; set; }
        public decimal mo_incnt { get; set; }
        public decimal InOutCnt { get; set; }
        public Nullable<decimal> my_effsal { get; set; }
        public Nullable<decimal> er_bashour { get; set; }
        public Nullable<decimal> er_hour { get; set; }
        public decimal my_artot { get; set; }
        public Nullable<decimal> my_taxot { get; set; }
        public Nullable<decimal> my_foodsal { get; set; }
        public Nullable<decimal> my_pri { get; set; }
        public Nullable<decimal> my_empben { get; set; }
        public decimal my_retire { get; set; }
        public Nullable<decimal> my_cost { get; set; }
        public Nullable<double> fld2 { get; set; }
        public Nullable<System.DateTime> em_20 { get; set; }
        public Nullable<decimal> em_71 { get; set; }
        public Nullable<decimal> em_72 { get; set; }
        public Nullable<System.DateTime> em_75 { get; set; }
        public Nullable<decimal> em_78 { get; set; }
        public decimal by_11 { get; set; }
        public decimal mhf_amt1 { get; set; }
        public decimal mhf_amt2 { get; set; }
        public decimal mhf_amt3 { get; set; }
        public decimal mhf_amt4 { get; set; }
    }
}
