//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ca_cabs25_01
    {
        public string MO_MKNO { get; set; }
        public string MO_DPNO { get; set; }
        public string MO_SETNO { get; set; }
        public Nullable<decimal> MO_QTY { get; set; }
        public Nullable<decimal> mo_mpaper { get; set; }
        public Nullable<decimal> bs_mono { get; set; }
        public decimal mo_kind { get; set; }
        public string mo_enno { get; set; }
        public string pr_cname { get; set; }
        public decimal SS_QTY { get; set; }
        public string mt_unit { get; set; }
        public decimal LW_FQTY { get; set; }
        public decimal woc_omaper { get; set; }
        public decimal woc_oqty { get; set; }
        public Nullable<decimal> MBO_GoodRate { get; set; }
        public decimal mo_GoodQty { get; set; }
        public decimal pr_good { get; set; }
        public string pp_name { get; set; }
    }
}
