//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cardp
    {
        public System.DateTime cp_date { get; set; }
        public string cp_emno { get; set; }
        public string cp_seca { get; set; }
        public string cp_secb { get; set; }
        public string cp_secc { get; set; }
        public string cp_secd { get; set; }
        public string cp_t1 { get; set; }
        public string cp_t2 { get; set; }
        public string cp_t3 { get; set; }
        public Nullable<decimal> cp_meal { get; set; }
        public decimal cp_holiday { get; set; }
        public decimal cp_handle { get; set; }
        public Nullable<System.DateTime> cp_HandleTime { get; set; }
        public string cp_t4 { get; set; }
    }
}
