//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterLine
    {
        public string cl_mkno { get; set; }
        public string cl_setno { get; set; }
        public Nullable<System.DateTime> cl_date { get; set; }
        public Nullable<System.DateTime> cl_cudate { get; set; }
        public string cl_size { get; set; }
        public Nullable<decimal> cl_getflim { get; set; }
        public Nullable<decimal> cl_nettemp { get; set; }
        public Nullable<decimal> cl_netpre { get; set; }
        public string cl_dpno { get; set; }
        public string cl_bompre { get; set; }
        public Nullable<decimal> cl_jit { get; set; }
        public Nullable<decimal> cl_netqty { get; set; }
        public string cl_paper { get; set; }
        public Nullable<decimal> cl_paperTemp { get; set; }
        public Nullable<decimal> cl_carqty { get; set; }
        public string cl_ws { get; set; }
        public string cl_spec { get; set; }
        public Nullable<decimal> cl_mpaper { get; set; }
        public string cl_yn { get; set; }
        public string cl_psize { get; set; }
        public Nullable<System.DateTime> cl_bomdate { get; set; }
        public Nullable<System.DateTime> cl_paperdate { get; set; }
        public Nullable<System.DateTime> cl_coldate { get; set; }
        public string cl_prno { get; set; }
        public decimal cl_combine { get; set; }
    }
}
