//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeDate1
    {
        public string ed_orno { get; set; }
        public Nullable<System.DateTime> ed_ordate { get; set; }
        public string ed_item { get; set; }
        public string ed_cupdno { get; set; }
        public string ed_level { get; set; }
        public Nullable<System.DateTime> ed_date { get; set; }
        public Nullable<decimal> ed_amt { get; set; }
        public string ed_cuno { get; set; }
        public int RowNo { get; set; }
        public string Col_A { get; set; }
        public Nullable<System.DateTime> Col_B { get; set; }
        public Nullable<System.DateTime> Col_C { get; set; }
        public string Col_D { get; set; }
        public string Col_E { get; set; }
        public string Col_F { get; set; }
        public string Col_G { get; set; }
        public string Col_H { get; set; }
        public string Col_I { get; set; }
        public string Col_J { get; set; }
        public string Col_K { get; set; }
        public string Col_L { get; set; }
        public string Col_M { get; set; }
        public string Col_N { get; set; }
        public string Col_O { get; set; }
        public string Col_P { get; set; }
        public string Col_Q { get; set; }
        public Nullable<System.DateTime> Col_R { get; set; }
        public string Col_S { get; set; }
        public string Col_T { get; set; }
        public string Col_U { get; set; }
    }
}
