//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class charge
    {
        public Nullable<decimal> ch_peo { get; set; }
        public Nullable<decimal> ch_cpu { get; set; }
        public Nullable<decimal> ch_col { get; set; }
        public Nullable<decimal> ch_colb { get; set; }
        public Nullable<decimal> ch_dry65 { get; set; }
        public Nullable<decimal> ch_dry75 { get; set; }
        public Nullable<decimal> ch_dry88 { get; set; }
        public Nullable<decimal> ch_dryp { get; set; }
        public Nullable<decimal> ch_dryz { get; set; }
        public Nullable<decimal> ch_dryz1 { get; set; }
        public Nullable<decimal> ch_dryc { get; set; }
        public Nullable<decimal> ch_samp { get; set; }
        public Nullable<decimal> ch_quana { get; set; }
        public Nullable<decimal> ch_quanb { get; set; }
        public Nullable<decimal> ch_quanc { get; set; }
        public Nullable<decimal> ch_quand { get; set; }
        public Nullable<decimal> ch_quane { get; set; }
        public Nullable<decimal> ch_quanf { get; set; }
        public Nullable<decimal> ch_moldi { get; set; }
        public Nullable<decimal> ch_molda { get; set; }
        public Nullable<decimal> ch_moldb { get; set; }
        public Nullable<decimal> ch_moldc { get; set; }
        public Nullable<decimal> ch_moldl { get; set; }
        public Nullable<decimal> ch_moldw { get; set; }
        public Nullable<decimal> ch_knief { get; set; }
        public Nullable<decimal> ch_knieb { get; set; }
        public Nullable<decimal> ch_disca { get; set; }
        public Nullable<decimal> ch_discb { get; set; }
        public Nullable<decimal> ch_discc { get; set; }
        public Nullable<decimal> ch_discd { get; set; }
        public Nullable<decimal> ch_disce { get; set; }
        public Nullable<decimal> ch_discf { get; set; }
        public Nullable<decimal> ch_mana { get; set; }
        public Nullable<decimal> ch_prof { get; set; }
        public Nullable<decimal> ch_pack { get; set; }
        public decimal ch_dry117 { get; set; }
        public decimal ch_dry130 { get; set; }
        public decimal ch_dry110 { get; set; }
        public decimal ch_dry136 { get; set; }
        public decimal ch_dry125 { get; set; }
        public decimal ch_dry113 { get; set; }
        public decimal ch_ChgCar { get; set; }
    }
}
