//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chk
    {
        public System.DateTime ck_date { get; set; }
        public string ck_diff { get; set; }
        public string ck_mtno { get; set; }
        public Nullable<decimal> ck_qty1 { get; set; }
        public Nullable<decimal> ck_qty2 { get; set; }
        public Nullable<decimal> ck_qty3 { get; set; }
        public Nullable<decimal> ck_yn { get; set; }
        public Nullable<decimal> ck_width { get; set; }
        public Nullable<decimal> ck_long { get; set; }
        public string ck_reason { get; set; }
        public Nullable<System.DateTime> ck_cdate { get; set; }
        public decimal ck_src { get; set; }
    }
}
