//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public string cs_cono { get; set; }
        public string cs_no { get; set; }
        public string cs_name { get; set; }
        public string cs_11 { get; set; }
        public string cs_12 { get; set; }
        public string cs_21 { get; set; }
        public string cs_22 { get; set; }
        public string cs_31 { get; set; }
        public string cs_32 { get; set; }
        public string cs_41 { get; set; }
        public string cs_42 { get; set; }
        public string cs_51 { get; set; }
        public string cs_52 { get; set; }
        public string cs_53 { get; set; }
        public string cs_54 { get; set; }
        public Nullable<decimal> cs_55 { get; set; }
        public string cs_61 { get; set; }
        public string cs_62 { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
    }
}
