//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_coin34_01
    {
        public decimal seqno { get; set; }
        public Nullable<System.DateTime> QueryDate { get; set; }
        public string Lock_cuno { get; set; }
        public string cu_sname { get; set; }
        public string cu_dpno { get; set; }
        public string cu_emno { get; set; }
        public string em_cname { get; set; }
        public decimal NotPay { get; set; }
        public decimal bd_amount { get; set; }
        public decimal NotPayAll { get; set; }
        public decimal TradeLimit { get; set; }
        public decimal The_Rate { get; set; }
        public int DoSend { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public decimal ar_pamount { get; set; }
    }
}
