//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coaccta
    {
        public string compid { get; set; }
        public string caa_year { get; set; }
        public string caa_depno { get; set; }
        public string caa_macno { get; set; }
        public Nullable<decimal> caa_db00 { get; set; }
        public Nullable<decimal> caa_db01 { get; set; }
        public Nullable<decimal> caa_db02 { get; set; }
        public Nullable<decimal> caa_db03 { get; set; }
        public Nullable<decimal> caa_db04 { get; set; }
        public Nullable<decimal> caa_db05 { get; set; }
        public Nullable<decimal> caa_db06 { get; set; }
        public Nullable<decimal> caa_db07 { get; set; }
        public Nullable<decimal> caa_db08 { get; set; }
        public Nullable<decimal> caa_db09 { get; set; }
        public Nullable<decimal> caa_db10 { get; set; }
        public Nullable<decimal> caa_db11 { get; set; }
        public Nullable<decimal> caa_db12 { get; set; }
        public Nullable<decimal> caa_cr00 { get; set; }
        public Nullable<decimal> caa_cr01 { get; set; }
        public Nullable<decimal> caa_cr02 { get; set; }
        public Nullable<decimal> caa_cr03 { get; set; }
        public Nullable<decimal> caa_cr04 { get; set; }
        public Nullable<decimal> caa_cr05 { get; set; }
        public Nullable<decimal> caa_cr06 { get; set; }
        public Nullable<decimal> caa_cr07 { get; set; }
        public Nullable<decimal> caa_cr08 { get; set; }
        public Nullable<decimal> caa_cr09 { get; set; }
        public Nullable<decimal> caa_cr10 { get; set; }
        public Nullable<decimal> caa_cr11 { get; set; }
        public Nullable<decimal> caa_cr12 { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
