//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coacctc
    {
        public string compid { get; set; }
        public string cac_year { get; set; }
        public string cac_cskno { get; set; }
        public string cac_csno { get; set; }
        public string cac_macno { get; set; }
        public Nullable<decimal> cac_db00 { get; set; }
        public Nullable<decimal> cac_db01 { get; set; }
        public Nullable<decimal> cac_db02 { get; set; }
        public Nullable<decimal> cac_db03 { get; set; }
        public Nullable<decimal> cac_db04 { get; set; }
        public Nullable<decimal> cac_db05 { get; set; }
        public Nullable<decimal> cac_db06 { get; set; }
        public Nullable<decimal> cac_db07 { get; set; }
        public Nullable<decimal> cac_db08 { get; set; }
        public Nullable<decimal> cac_db09 { get; set; }
        public Nullable<decimal> cac_db10 { get; set; }
        public Nullable<decimal> cac_db11 { get; set; }
        public Nullable<decimal> cac_db12 { get; set; }
        public Nullable<decimal> cac_cr00 { get; set; }
        public Nullable<decimal> cac_cr01 { get; set; }
        public Nullable<decimal> cac_cr02 { get; set; }
        public Nullable<decimal> cac_cr03 { get; set; }
        public Nullable<decimal> cac_cr04 { get; set; }
        public Nullable<decimal> cac_cr05 { get; set; }
        public Nullable<decimal> cac_cr06 { get; set; }
        public Nullable<decimal> cac_cr07 { get; set; }
        public Nullable<decimal> cac_cr08 { get; set; }
        public Nullable<decimal> cac_cr09 { get; set; }
        public Nullable<decimal> cac_cr10 { get; set; }
        public Nullable<decimal> cac_cr11 { get; set; }
        public Nullable<decimal> cac_cr12 { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
