//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coacctb
    {
        public string compid { get; set; }
        public string cab_year { get; set; }
        public string cab_pjno { get; set; }
        public string cab_macno { get; set; }
        public Nullable<decimal> cab_db00 { get; set; }
        public Nullable<decimal> cab_db01 { get; set; }
        public Nullable<decimal> cab_db02 { get; set; }
        public Nullable<decimal> cab_db03 { get; set; }
        public Nullable<decimal> cab_db04 { get; set; }
        public Nullable<decimal> cab_db05 { get; set; }
        public Nullable<decimal> cab_db06 { get; set; }
        public Nullable<decimal> cab_db07 { get; set; }
        public Nullable<decimal> cab_db08 { get; set; }
        public Nullable<decimal> cab_db09 { get; set; }
        public Nullable<decimal> cab_db10 { get; set; }
        public Nullable<decimal> cab_db11 { get; set; }
        public Nullable<decimal> cab_db12 { get; set; }
        public Nullable<decimal> cab_cr00 { get; set; }
        public Nullable<decimal> cab_cr01 { get; set; }
        public Nullable<decimal> cab_cr02 { get; set; }
        public Nullable<decimal> cab_cr03 { get; set; }
        public Nullable<decimal> cab_cr04 { get; set; }
        public Nullable<decimal> cab_cr05 { get; set; }
        public Nullable<decimal> cab_cr06 { get; set; }
        public Nullable<decimal> cab_cr07 { get; set; }
        public Nullable<decimal> cab_cr08 { get; set; }
        public Nullable<decimal> cab_cr09 { get; set; }
        public Nullable<decimal> cab_cr10 { get; set; }
        public Nullable<decimal> cab_cr11 { get; set; }
        public Nullable<decimal> cab_cr12 { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
