//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coin01h
    {
        public decimal ih_pgno { get; set; }
        public decimal ih_rec { get; set; }
        public string ih_no { get; set; }
        public string ih_chno { get; set; }
        public Nullable<System.DateTime> ih_date { get; set; }
        public string ih_ufyno { get; set; }
        public string ih_cuno { get; set; }
        public Nullable<System.DateTime> ih_ddate { get; set; }
        public string ih_acpe { get; set; }
        public string ih_acpa { get; set; }
        public Nullable<decimal> ih_aby { get; set; }
        public Nullable<decimal> ih_subtot { get; set; }
        public Nullable<decimal> ih_taxatt { get; set; }
        public Nullable<decimal> ih_tax { get; set; }
        public Nullable<decimal> ih_priny { get; set; }
        public Nullable<decimal> ih_ediy { get; set; }
        public string ih_faatt { get; set; }
        public Nullable<decimal> ih_post { get; set; }
        public string ih_inhno { get; set; }
        public string ih_no1 { get; set; }
        public string ih_chno1 { get; set; }
        public Nullable<System.DateTime> ih_date1 { get; set; }
        public string ih_ufyno1 { get; set; }
        public string ih_cuno1 { get; set; }
        public Nullable<System.DateTime> ih_ddate1 { get; set; }
        public string ih_acpe1 { get; set; }
        public string ih_acpa1 { get; set; }
        public Nullable<decimal> ih_aby1 { get; set; }
        public Nullable<decimal> ih_subtot1 { get; set; }
        public Nullable<decimal> ih_taxatt1 { get; set; }
        public Nullable<decimal> ih_tax1 { get; set; }
        public Nullable<decimal> ih_priny1 { get; set; }
        public Nullable<decimal> ih_ediy1 { get; set; }
        public string ih_faatt1 { get; set; }
        public Nullable<decimal> ih_post1 { get; set; }
        public string ih_inhno1 { get; set; }
    }
}
