//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coldetail
    {
        public string cd_ym { get; set; }
        public string cd_no { get; set; }
        public string cd_cuno { get; set; }
        public string cd_accno { get; set; }
        public string cd_billno { get; set; }
        public string cd_abst { get; set; }
        public Nullable<System.DateTime> cd_date { get; set; }
        public string cd_emno { get; set; }
        public Nullable<System.DateTime> cd_date1 { get; set; }
        public Nullable<System.DateTime> cd_date2 { get; set; }
        public Nullable<decimal> cd_yield { get; set; }
        public Nullable<decimal> cd_ret { get; set; }
        public Nullable<decimal> cd_disc { get; set; }
        public Nullable<decimal> cd_other { get; set; }
        public string cd_desc { get; set; }
        public Nullable<decimal> cd_amount { get; set; }
        public Nullable<decimal> cd_unamt { get; set; }
        public string cd_opaccno { get; set; }
        public string cd_pac { get; set; }
        public Nullable<System.DateTime> cd_date3 { get; set; }
        public string cd_bank { get; set; }
        public Nullable<decimal> cd_unamt1 { get; set; }
        public Nullable<decimal> cd_amount2 { get; set; }
        public Nullable<decimal> cd_revamt { get; set; }
        public string cd_curr { get; set; }
        public Nullable<decimal> cd_disc1 { get; set; }
        public Nullable<decimal> cd_yield1 { get; set; }
        public Nullable<decimal> cd_amount1 { get; set; }
        public Nullable<decimal> cd_post { get; set; }
        public string cd_dpno { get; set; }
        public decimal cd_ChkAmt { get; set; }
        public Nullable<decimal> cd_billO { get; set; }
        public Nullable<decimal> cd_exchange { get; set; }
        public Nullable<decimal> cd_billTWD { get; set; }
        public string cd_SNO1 { get; set; }
        public string cd_SNO2 { get; set; }
        public string cd_mcno { get; set; }
        public decimal cd_amount3 { get; set; }
    }
}
