//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorSch
    {
        public string cs_puno { get; set; }
        public decimal cs_item { get; set; }
        public Nullable<decimal> cs_hour { get; set; }
        public string cs_dpno { get; set; }
        public string cs_dpno1 { get; set; }
        public string cs_cuno { get; set; }
        public Nullable<System.DateTime> cs_postdate { get; set; }
        public Nullable<System.DateTime> cs_pdate { get; set; }
        public Nullable<System.DateTime> cs_date { get; set; }
        public Nullable<decimal> cs_seq { get; set; }
        public Nullable<decimal> cs_working { get; set; }
        public Nullable<decimal> cs_close { get; set; }
        public string cs_emno { get; set; }
        public Nullable<System.DateTime> cs_adate { get; set; }
        public Nullable<System.DateTime> cs_cdate { get; set; }
        public Nullable<decimal> cs_jit { get; set; }
    }
}
