//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorChange
    {
        public Nullable<decimal> cg_kind { get; set; }
        public Nullable<System.DateTime> cg_date { get; set; }
        public string cg_emno { get; set; }
        public string cg_ceno { get; set; }
        public string cg_prop { get; set; }
        public string cg_loc { get; set; }
        public Nullable<decimal> cg_weight { get; set; }
        public Nullable<decimal> cg_qty { get; set; }
        public string cg_mkno { get; set; }
        public decimal cg_seqno { get; set; }
        public Nullable<decimal> cg_serial { get; set; }
        public Nullable<decimal> cg_subject { get; set; }
        public string cg_setno { get; set; }
        public Nullable<decimal> cg_weight1 { get; set; }
        public string cg_reason1 { get; set; }
    }
}
