//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coltime
    {
        public System.DateTime ce_date { get; set; }
        public string ce_emno { get; set; }
        public Nullable<decimal> ce_cause { get; set; }
        public string ce_puno { get; set; }
        public Nullable<decimal> ce_time { get; set; }
        public string ce_text { get; set; }
        public Nullable<decimal> ce_close { get; set; }
        public decimal ce_hdate { get; set; }
    }
}
