//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuscard
    {
        public string ca_cuno { get; set; }
        public string ca_csname { get; set; }
        public string ca_payway { get; set; }
        public string ca_date { get; set; }
        public decimal ca_class { get; set; }
        public string ca_abst { get; set; }
        public Nullable<decimal> ca_amount { get; set; }
        public Nullable<decimal> ca_disc { get; set; }
        public Nullable<decimal> ca_yield { get; set; }
        public Nullable<System.DateTime> ca_date1 { get; set; }
        public string ca_dpno { get; set; }
        public decimal ca_seq { get; set; }
        public string ca_cdno { get; set; }
        public string ca_mykno { get; set; }
        public decimal ca_amount_NT { get; set; }
        public decimal ca_disc_NT { get; set; }
        public decimal ca_yield_NT { get; set; }
        public decimal ca_pamount { get; set; }
        public decimal ca_pamount_NT { get; set; }
        public decimal ca_pyn { get; set; }
    }
}
