//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class custsupp
    {
        public string cs_no { get; set; }
        public string cs_sname { get; set; }
        public string cs_name { get; set; }
        public string cs_kind { get; set; }
        public string cs_uniid { get; set; }
        public string cs_director { get; set; }
        public string cs_tel1 { get; set; }
        public string cs_tel2 { get; set; }
        public string cs_fax1 { get; set; }
        public string cs_fax2 { get; set; }
        public string cs_email { get; set; }
        public string cs_poistid { get; set; }
        public string cs_addr { get; set; }
        public string cs_invaddr { get; set; }
        public string cs_contect { get; set; }
        public string cs_10 { get; set; }
        public string cs_11 { get; set; }
        public string cs_notes { get; set; }
        public string cs_mykno { get; set; }
        public string compid { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
