//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEff
    {
        public string ce_yymm { get; set; }
        public string ce_dpno { get; set; }
        public string ce_cuno { get; set; }
        public string ce_sname { get; set; }
        public Nullable<decimal> ce_colnum { get; set; }
        public Nullable<decimal> ce_d { get; set; }
        public Nullable<decimal> ce_dcost { get; set; }
        public Nullable<decimal> ce_mo { get; set; }
        public Nullable<decimal> ce_mocost { get; set; }
        public Nullable<decimal> ce_free { get; set; }
        public Nullable<decimal> ce_freeamt { get; set; }
        public Nullable<decimal> ce_r { get; set; }
        public Nullable<decimal> ce_ramt { get; set; }
        public Nullable<decimal> ce_amt { get; set; }
        public Nullable<decimal> ce_im { get; set; }
        public Nullable<decimal> ce_imamt { get; set; }
        public Nullable<decimal> ce_imrate { get; set; }
        public Nullable<decimal> ce_drate { get; set; }
        public Nullable<decimal> ce_irate { get; set; }
        public Nullable<decimal> ce_rate { get; set; }
    }
}
