//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dayload
    {
        public System.DateTime dl_date { get; set; }
        public decimal dl_11 { get; set; }
        public decimal dl_12 { get; set; }
        public decimal dl_13 { get; set; }
        public decimal dl_21 { get; set; }
        public decimal dl_22 { get; set; }
        public decimal dl_23 { get; set; }
        public decimal dl_24 { get; set; }
        public decimal dl_31 { get; set; }
        public decimal dl_32 { get; set; }
        public decimal dl_33 { get; set; }
        public Nullable<decimal> dl_41 { get; set; }
        public Nullable<decimal> dl_42 { get; set; }
    }
}
