//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class degree
    {
        public string de_level { get; set; }
        public Nullable<decimal> de_degree { get; set; }
        public Nullable<decimal> de_time { get; set; }
        public Nullable<decimal> de_amt1 { get; set; }
        public Nullable<decimal> de_amt2 { get; set; }
    }
}
