//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveb
    {
        public string db_no { get; set; }
        public Nullable<System.DateTime> db_date { get; set; }
        public string db_cuno { get; set; }
        public string db_cusname { get; set; }
        public string db_noteno { get; set; }
        public string db_loc { get; set; }
        public Nullable<decimal> db_tax { get; set; }
        public string db_emno { get; set; }
        public string db_orno { get; set; }
        public string db_cupdno { get; set; }
        public string db_pdno { get; set; }
        public string db_spec { get; set; }
        public Nullable<decimal> db_uprice { get; set; }
        public Nullable<decimal> db_amount { get; set; }
        public Nullable<decimal> db_total { get; set; }
        public Nullable<decimal> db_free { get; set; }
        public Nullable<System.DateTime> db_date1 { get; set; }
        public Nullable<decimal> db_amount1 { get; set; }
        public Nullable<System.DateTime> db_date2 { get; set; }
        public Nullable<decimal> db_amount2 { get; set; }
        public Nullable<System.DateTime> db_date3 { get; set; }
        public Nullable<decimal> db_amount3 { get; set; }
        public string db_lvno { get; set; }
        public Nullable<decimal> db_memo { get; set; }
        public string db_curr { get; set; }
        public string db_chkno { get; set; }
        public Nullable<decimal> db_inv { get; set; }
        public Nullable<decimal> db_chkamt { get; set; }
        public Nullable<decimal> db_okamt { get; set; }
        public string db_fano { get; set; }
        public string db_dpno { get; set; }
        public Nullable<decimal> db_freeamt { get; set; }
        public Nullable<decimal> db_post { get; set; }
        public Nullable<decimal> db_one { get; set; }
        public Nullable<decimal> db_close { get; set; }
        public Nullable<decimal> db_send { get; set; }
        public string db_ym { get; set; }
        public string db_line { get; set; }
        public string db_item { get; set; }
        public string db_mkid { get; set; }
        public string db_reason { get; set; }
        public decimal db_kind { get; set; }
        public string db_boxno { get; set; }
        public decimal db_PageNo { get; set; }
        public string db_mkno { get; set; }
        public decimal db_ver { get; set; }
        public Nullable<System.DateTime> db_vdate1 { get; set; }
        public Nullable<System.DateTime> db_vdate2 { get; set; }
        public string db_note { get; set; }
        public decimal db_SignBack { get; set; }
        public string db_SignNote { get; set; }
        public string db_cupdno1 { get; set; }
        public Nullable<System.DateTime> db_vdate3 { get; set; }
        public string db_vemno1 { get; set; }
        public string db_vemno2 { get; set; }
        public string db_vemno3 { get; set; }
        public string db_cino { get; set; }
        public decimal db_excrate { get; set; }
        public string db_forward { get; set; }
        public string db_shipto { get; set; }
        public string db_ETotal { get; set; }
        public decimal db_INTotal { get; set; }
        public string db_trans { get; set; }
        public decimal db_seqno { get; set; }
        public string db_cumemo { get; set; }
        public Nullable<System.DateTime> db_cdate { get; set; }
        public string bs_prno { get; set; }
        public string pr_ename { get; set; }
        public string pr_cname { get; set; }
        public Nullable<System.DateTime> db_ctime { get; set; }
        public string db_GiantNo { get; set; }
    }
}
