//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dphour
    {
        public string ym { get; set; }
        public string DP_NO { get; set; }
        public string DP_NAME { get; set; }
        public string EM_NO { get; set; }
        public string EM_NAME { get; set; }
        public Nullable<decimal> BASEHOUR { get; set; }
        public Nullable<decimal> LEAHOUR { get; set; }
        public Nullable<decimal> T_ADD1 { get; set; }
        public Nullable<decimal> H_ADD1 { get; set; }
        public Nullable<decimal> T_ADD2 { get; set; }
        public Nullable<decimal> H_ADD2 { get; set; }
        public Nullable<decimal> vm_early { get; set; }
        public Nullable<decimal> vm_21 { get; set; }
        public Nullable<decimal> vm_231 { get; set; }
    }
}
