//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dracost
    {
        public string dc_puno { get; set; }
        public string dc_emno { get; set; }
        public Nullable<System.DateTime> dc_date { get; set; }
        public string dc_cuno { get; set; }
        public string dc_prno { get; set; }
        public string dc_mnno { get; set; }
        public string dc_desc { get; set; }
        public Nullable<decimal> dc_fee { get; set; }
        public Nullable<decimal> dc_colfee { get; set; }
        public Nullable<decimal> dc_sfee { get; set; }
        public Nullable<decimal> dc_pfee { get; set; }
        public Nullable<decimal> dc_spfee { get; set; }
        public Nullable<decimal> dc_mfee { get; set; }
        public Nullable<decimal> dc_total { get; set; }
        public Nullable<decimal> dc_charge { get; set; }
        public Nullable<decimal> dc_share { get; set; }
        public Nullable<decimal> dc_dhour { get; set; }
        public Nullable<decimal> dc_dprice { get; set; }
        public Nullable<decimal> dc_dchour { get; set; }
        public Nullable<decimal> dc_dcprice { get; set; }
        public Nullable<decimal> dc_coll { get; set; }
        public Nullable<decimal> dc_colw { get; set; }
        public Nullable<decimal> dc_colnum { get; set; }
        public Nullable<decimal> dc_cprice { get; set; }
        public Nullable<decimal> dc_pnum65 { get; set; }
        public Nullable<decimal> dc_price65 { get; set; }
        public Nullable<decimal> dc_pnum75 { get; set; }
        public Nullable<decimal> dc_price75 { get; set; }
        public Nullable<decimal> dc_pnum88 { get; set; }
        public Nullable<decimal> dc_price88 { get; set; }
        public Nullable<decimal> dc_other { get; set; }
        public Nullable<decimal> dc_oprice { get; set; }
        public Nullable<decimal> dc_platen { get; set; }
        public Nullable<decimal> dc_platep { get; set; }
        public Nullable<decimal> dc_zincl { get; set; }
        public Nullable<decimal> dc_zincw { get; set; }
        public Nullable<decimal> dc_zincnum { get; set; }
        public Nullable<decimal> dc_zincp { get; set; }
        public Nullable<decimal> dc_coppl { get; set; }
        public Nullable<decimal> dc_coppw { get; set; }
        public Nullable<decimal> dc_coppnum { get; set; }
        public Nullable<decimal> dc_coppp { get; set; }
        public Nullable<decimal> dc_shinen { get; set; }
        public Nullable<decimal> dc_shinep { get; set; }
        public Nullable<decimal> dc_printcn { get; set; }
        public Nullable<decimal> dc_printcp { get; set; }
        public Nullable<decimal> dc_mrate { get; set; }
        public string dc_dpno { get; set; }
        public decimal dc_pnum117 { get; set; }
        public decimal dc_price117 { get; set; }
        public decimal dc_pnum130 { get; set; }
        public decimal dc_price130 { get; set; }
        public decimal dc_pnum110 { get; set; }
        public decimal dc_price110 { get; set; }
        public decimal dc_pnum136 { get; set; }
        public decimal dc_price136 { get; set; }
        public decimal dc_pnum125 { get; set; }
        public decimal dc_price125 { get; set; }
        public decimal dc_pnum113 { get; set; }
        public decimal dc_price113 { get; set; }
    }
}
