//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECS02
    {
        public string The_YM { get; set; }
        public string The_mkno { get; set; }
        public string The_setno { get; set; }
        public string The_mtno { get; set; }
        public decimal The_ICnt { get; set; }
        public decimal The_IAmt1 { get; set; }
        public decimal The_IAmt2 { get; set; }
        public decimal The_IAmt3 { get; set; }
        public decimal The_IAmt4 { get; set; }
        public decimal The_ECnt { get; set; }
        public decimal The_EAmt0 { get; set; }
        public decimal The_EAmt1 { get; set; }
        public decimal The_EAmt2 { get; set; }
        public decimal The_EAmt3 { get; set; }
        public decimal The_EAmt4 { get; set; }
        public decimal The_OCnt { get; set; }
        public decimal The_OAmt1 { get; set; }
        public decimal The_OAmt2 { get; set; }
        public decimal The_OAmt3 { get; set; }
        public decimal The_OAmt4 { get; set; }
        public decimal The_Sale { get; set; }
        public decimal The_SQty { get; set; }
        public decimal The_SAmt1 { get; set; }
        public decimal The_SAmt2 { get; set; }
        public decimal The_SAmt3 { get; set; }
        public decimal The_SAmt4 { get; set; }
        public decimal The_ChkCnt { get; set; }
        public string The_cuno { get; set; }
    }
}
