//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECS01
    {
        public string The_YM { get; set; }
        public string The_mtno { get; set; }
        public string The_spec { get; set; }
        public string The_unit1 { get; set; }
        public decimal The_ICnt { get; set; }
        public decimal The_IPrice { get; set; }
        public decimal The_ITotal { get; set; }
        public decimal The_ECnt { get; set; }
        public decimal The_EPrice { get; set; }
        public decimal The_ETotal { get; set; }
        public decimal The_ETotal1 { get; set; }
        public decimal The_CCnt { get; set; }
        public decimal The_CPrice { get; set; }
        public decimal The_CTotal { get; set; }
        public decimal The_OCnt { get; set; }
        public decimal The_OPrice { get; set; }
        public decimal The_OTotal { get; set; }
        public decimal The_SCnt { get; set; }
        public decimal The_SPrice { get; set; }
        public decimal The_STotal { get; set; }
        public decimal The_CCnt1 { get; set; }
        public decimal The_CCnt2 { get; set; }
        public decimal The_CCnt3 { get; set; }
        public decimal The_CCnt4 { get; set; }
        public decimal The_CCnt5 { get; set; }
        public decimal The_CCnt6 { get; set; }
        public decimal The_CCnt7 { get; set; }
        public decimal The_ChkCnt { get; set; }
        public decimal The_CCnt8 { get; set; }
        public decimal The_CCnt9 { get; set; }
        public decimal The_CCnt10 { get; set; }
        public decimal The_CCnt11 { get; set; }
        public decimal The_CCnt12 { get; set; }
        public decimal The_FinCnt { get; set; }
    }
}
