//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECS03
    {
        public string The_YM { get; set; }
        public string The_upno { get; set; }
        public string The_spec { get; set; }
        public decimal The_IPrice { get; set; }
        public decimal The_ICnt { get; set; }
        public decimal The_IAmt { get; set; }
        public decimal The_ECnt1 { get; set; }
        public decimal The_EAmt1 { get; set; }
        public decimal The_ECnt2 { get; set; }
        public decimal The_EAmt2 { get; set; }
        public decimal The_CCnt1 { get; set; }
        public decimal The_CAmt1 { get; set; }
        public decimal The_CCnt2 { get; set; }
        public decimal The_CAmt2 { get; set; }
        public decimal The_SQty { get; set; }
        public decimal The_SAmt { get; set; }
        public decimal The_ChkCnt { get; set; }
        public string The_prno { get; set; }
    }
}
