//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emhourP
    {
        public string ep_yymm { get; set; }
        public string ep_ptno { get; set; }
        public decimal ep_tothour { get; set; }
        public decimal ep_bashour { get; set; }
        public decimal ep_hour { get; set; }
        public decimal ep_p0 { get; set; }
        public decimal ep_p1 { get; set; }
        public decimal ep_p2 { get; set; }
        public decimal ep_p1h { get; set; }
        public decimal ep_p2h { get; set; }
        public decimal ep_p0Tax { get; set; }
        public decimal ep_p0NTax { get; set; }
        public decimal ep_p1Tax { get; set; }
        public decimal ep_p1NTax { get; set; }
        public decimal ep_p2Tax { get; set; }
        public decimal ep_p2NTax { get; set; }
        public decimal ep_p0rTax { get; set; }
        public decimal ep_p0rNTax { get; set; }
        public decimal ep_p1rTax { get; set; }
        public decimal ep_p1rNTax { get; set; }
        public decimal ep_p2rTax { get; set; }
        public decimal ep_p2rNTax { get; set; }
        public decimal ep_p1wTax { get; set; }
        public decimal ep_p1wNTax { get; set; }
        public decimal ep_p2wTax { get; set; }
        public decimal ep_p2wNTax { get; set; }
        public decimal ep_p0r { get; set; }
        public decimal ep_p1r { get; set; }
        public decimal ep_p2r { get; set; }
        public decimal ep_p0s { get; set; }
        public decimal ep_p1s { get; set; }
        public decimal ep_p2s { get; set; }
        public decimal ep_p0w { get; set; }
        public decimal ep_p1w { get; set; }
        public decimal ep_p2w { get; set; }
    }
}
