//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpChange
    {
        public decimal ec_seqno { get; set; }
        public Nullable<System.DateTime> ec_date { get; set; }
        public string ec_emno { get; set; }
        public string ec_emcname { get; set; }
        public string ec_odpno { get; set; }
        public string ec_odpname { get; set; }
        public string ec_oem31 { get; set; }
        public string ec_oem31name { get; set; }
        public string ec_oemwork { get; set; }
        public string ec_dpno { get; set; }
        public string ec_dpname { get; set; }
        public string ec_em31 { get; set; }
        public string ec_em31name { get; set; }
        public string ec_emwork { get; set; }
        public string ec_cemno { get; set; }
        public Nullable<System.DateTime> ec_cdate { get; set; }
        public decimal ec_post { get; set; }
        public decimal ec_oem79 { get; set; }
        public decimal ec_em79 { get; set; }
    }
}
