//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDept
    {
        public string et_ym { get; set; }
        public string et_emno { get; set; }
        public string et_cname { get; set; }
        public string et_dpno { get; set; }
        public string et_dpname { get; set; }
        public string et_31 { get; set; }
        public decimal et_74 { get; set; }
        public decimal et_85 { get; set; }
        public decimal et_99 { get; set; }
        public decimal et_ceno3 { get; set; }
        public System.DateTime et_date { get; set; }
        public decimal et_labtotal { get; set; }
        public decimal et_heatotal { get; set; }
        public decimal et_heatotal_r { get; set; }
        public string et_work { get; set; }
        public decimal et_overseas { get; set; }
        public decimal et_95 { get; set; }
        public decimal et_96 { get; set; }
    }
}
