//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpGoodRate
    {
        public string The_YM { get; set; }
        public string The_emno { get; set; }
        public string The_emcname { get; set; }
        public string The_dpno { get; set; }
        public string The_dpname { get; set; }
        public decimal mo_mpaper { get; set; }
        public decimal GoodQty { get; set; }
        public decimal The_GoodRate1 { get; set; }
        public decimal The_mpaper { get; set; }
        public decimal The_gpaper { get; set; }
        public decimal The_GoodRate { get; set; }
        public decimal ss_qty { get; set; }
        public decimal mo_qty { get; set; }
        public decimal The_GoodRate2 { get; set; }
    }
}
