//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emqp12
    {
        public System.DateTime The_cdate { get; set; }
        public decimal seqno { get; set; }
        public string mo_date { get; set; }
        public Nullable<decimal> prt1D { get; set; }
        public Nullable<decimal> prt1 { get; set; }
        public Nullable<decimal> sup1 { get; set; }
        public Nullable<decimal> prt2D { get; set; }
        public Nullable<decimal> prt2 { get; set; }
        public Nullable<decimal> sup2 { get; set; }
        public Nullable<decimal> prt3D { get; set; }
        public Nullable<decimal> prt3 { get; set; }
        public Nullable<decimal> sup3 { get; set; }
        public Nullable<decimal> prt4D { get; set; }
        public Nullable<decimal> prt4 { get; set; }
        public Nullable<decimal> sup4 { get; set; }
        public Nullable<decimal> prt5D { get; set; }
        public Nullable<decimal> prt5 { get; set; }
        public Nullable<decimal> sup5 { get; set; }
        public Nullable<decimal> total { get; set; }
        public decimal pcqty1 { get; set; }
        public decimal pcqty2 { get; set; }
        public decimal pcqty3 { get; set; }
        public decimal pcqty4 { get; set; }
        public decimal pcqty5 { get; set; }
    }
}
