//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emqp12_color
    {
        public System.DateTime The_cdate { get; set; }
        public decimal seqno { get; set; }
        public string bh_pdate { get; set; }
        public Nullable<decimal> color1 { get; set; }
        public Nullable<decimal> color1P { get; set; }
        public Nullable<decimal> color1N { get; set; }
        public Nullable<decimal> color2 { get; set; }
        public Nullable<decimal> color2P { get; set; }
        public Nullable<decimal> color2N { get; set; }
        public Nullable<decimal> color3 { get; set; }
        public Nullable<decimal> color3P { get; set; }
        public Nullable<decimal> color3N { get; set; }
        public Nullable<decimal> color4 { get; set; }
        public Nullable<decimal> color4P { get; set; }
        public Nullable<decimal> color4N { get; set; }
        public Nullable<decimal> color5 { get; set; }
        public Nullable<decimal> color5P { get; set; }
        public Nullable<decimal> color5N { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
