//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class errlog
    {
        public string err_key { get; set; }
        public System.DateTime err_date { get; set; }
        public decimal err_no { get; set; }
        public string err_mess { get; set; }
        public string err_prog { get; set; }
        public decimal err_line { get; set; }
        public string updid { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
