//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorColorSch
    {
        public string brg_mkno { get; set; }
        public string brg_setno { get; set; }
        public string brg_emno { get; set; }
        public string rgb_cname { get; set; }
        public Nullable<System.DateTime> brg_date2 { get; set; }
        public Nullable<System.DateTime> brg_date { get; set; }
        public Nullable<System.DateTime> brg_schdate { get; set; }
        public string brg_reason { get; set; }
        public System.DateTime ErrorTime { get; set; }
        public string ErrorSRC { get; set; }
        public string loginCname { get; set; }
        public string The_duty { get; set; }
        public Nullable<System.DateTime> HandleTime { get; set; }
    }
}
