//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionFee
    {
        public string ef_no { get; set; }
        public decimal ef_kind { get; set; }
        public string ef_seq { get; set; }
        public string ef_mtno { get; set; }
        public string ef_tbname { get; set; }
        public string ef_spec { get; set; }
        public Nullable<decimal> ef_badcnt { get; set; }
        public string ef_badunit { get; set; }
        public Nullable<decimal> ef_mono { get; set; }
        public Nullable<decimal> ef_ptimes { get; set; }
        public Nullable<decimal> ef_chgnet { get; set; }
        public Nullable<decimal> ef_long { get; set; }
        public Nullable<decimal> ef_width { get; set; }
        public Nullable<decimal> ef_price { get; set; }
        public Nullable<decimal> ef_limit { get; set; }
        public Nullable<decimal> ef_limitcost { get; set; }
        public Nullable<decimal> ef_chgprice { get; set; }
        public Nullable<decimal> ef_total { get; set; }
    }
}
