//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exception
    {
        public string EN_NO { get; set; }
        public string EN_EMNO { get; set; }
        public string EN_NAME { get; set; }
        public string EN_DPNO { get; set; }
        public string EN_DPNAME { get; set; }
        public string EN_CUNO { get; set; }
        public string EN_CUNAME { get; set; }
        public Nullable<System.DateTime> EN_DATE1 { get; set; }
        public string EN_ORNO { get; set; }
        public string EN_CARNO { get; set; }
        public string EN_DESC { get; set; }
        public Nullable<System.DateTime> EN_DATE2 { get; set; }
        public Nullable<decimal> EN_QTY1 { get; set; }
        public Nullable<decimal> EN_QTY2 { get; set; }
        public string EN_CONTENT1 { get; set; }
        public string EN_FILENAME { get; set; }
        public Nullable<System.DateTime> EN_DATE3 { get; set; }
        public string EN_PLACE { get; set; }
        public Nullable<System.DateTime> EN_DATE4 { get; set; }
        public decimal EN_KIND { get; set; }
        public string EN_REASON { get; set; }
        public string EN_SOLUTION { get; set; }
        public string EN_CONTENT2 { get; set; }
        public Nullable<System.DateTime> EN_UPDATE { get; set; }
        public string EN_ACEMNO { get; set; }
        public string EN_ACNAME { get; set; }
        public Nullable<decimal> EN_POST { get; set; }
        public Nullable<decimal> EN_YN { get; set; }
        public Nullable<decimal> EN_CLOSE { get; set; }
    }
}
