//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exhour
    {
        public string er_emno { get; set; }
        public string er_dpno { get; set; }
        public System.DateTime er_date { get; set; }
        public string er_hour_s { get; set; }
        public string er_hour_e { get; set; }
        public decimal er_hour { get; set; }
        public string er_reason { get; set; }
        public int er_no { get; set; }
        public string er_note { get; set; }
        public decimal er_yn { get; set; }
        public decimal er_post { get; set; }
    }
}
