//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expbuy
    {
        public string eb_mtno { get; set; }
        public Nullable<decimal> eb_amount { get; set; }
        public Nullable<decimal> eb_long { get; set; }
        public Nullable<decimal> eb_width { get; set; }
        public Nullable<decimal> eb_weight { get; set; }
        public Nullable<decimal> eb_mat { get; set; }
        public System.DateTime eb_date { get; set; }
    }
}
