//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expu_chg
    {
        public string The_Action { get; set; }
        public System.DateTime The_Date { get; set; }
        public string eu_mkno { get; set; }
        public string eu_setno { get; set; }
        public string eu_mtno { get; set; }
        public string eu_suno { get; set; }
        public decimal eu_width { get; set; }
        public decimal eu_owidth { get; set; }
        public decimal eu_long { get; set; }
        public decimal eu_olong { get; set; }
        public decimal eu_puramt { get; set; }
        public decimal eu_opuramt { get; set; }
        public string eu_emno { get; set; }
    }
}
