//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expusift_chg
    {
        public string The_Action { get; set; }
        public System.DateTime The_Date { get; set; }
        public string et_mkno { get; set; }
        public string et_setno { get; set; }
        public string et_mtno { get; set; }
        public string et_suno { get; set; }
        public string et_osuno { get; set; }
        public decimal et_width { get; set; }
        public decimal et_owidth { get; set; }
        public decimal et_long { get; set; }
        public decimal et_olong { get; set; }
        public decimal et_amount { get; set; }
        public decimal et_oamount { get; set; }
        public string et_emno { get; set; }
    }
}
