//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expu
    {
        public string eu_suno { get; set; }
        public string eu_mtno { get; set; }
        public string eu_mkno { get; set; }
        public decimal eu_long { get; set; }
        public decimal eu_width { get; set; }
        public Nullable<decimal> eu_puramt { get; set; }
        public Nullable<System.DateTime> eu_date { get; set; }
        public string eu_setno { get; set; }
        public string eu_emno { get; set; }
        public Nullable<System.DateTime> eu_date1 { get; set; }
        public string eu_puno { get; set; }
        public string eu_emno1 { get; set; }
        public Nullable<System.DateTime> eu_date2 { get; set; }
        public Nullable<decimal> eu_chnum { get; set; }
        public Nullable<System.DateTime> eu_date3 { get; set; }
        public Nullable<decimal> eu_yn { get; set; }
        public Nullable<decimal> eu_retamt { get; set; }
        public Nullable<System.DateTime> eu_date4 { get; set; }
        public string eu_memo { get; set; }
        public string eu_dpno { get; set; }
        public string eu_isno { get; set; }
        public decimal eu_accamt { get; set; }
        public Nullable<decimal> eu_yn1 { get; set; }
        public string eu_shno { get; set; }
        public Nullable<decimal> eu_price { get; set; }
        public string eu_orno { get; set; }
        public Nullable<decimal> eu_yn2 { get; set; }
        public string eu_payunit { get; set; }
        public Nullable<decimal> eu_getqty1 { get; set; }
        public decimal eu_getqty2 { get; set; }
        public Nullable<decimal> eu_qc { get; set; }
        public decimal eu_paper { get; set; }
        public decimal eu_yn3 { get; set; }
        public decimal eu_yn4 { get; set; }
        public string eu_mtnoA { get; set; }
        public decimal eu_save { get; set; }
        public decimal eu_item { get; set; }
        public decimal eu_ver1 { get; set; }
        public string eu_vemno1 { get; set; }
        public string eu_vemcname1 { get; set; }
        public Nullable<System.DateTime> eu_vdate1 { get; set; }
        public decimal eu_ver2 { get; set; }
        public string eu_vemno2 { get; set; }
        public string eu_vemcname2 { get; set; }
        public Nullable<System.DateTime> eu_vdate2 { get; set; }
        public decimal eu_yn5 { get; set; }
        public string eu_reason { get; set; }
        public decimal eu_yn6 { get; set; }
        public decimal eu_qcin { get; set; }
        public decimal eu_chnum_s { get; set; }
        public string eu_emno6 { get; set; }
        public decimal eu_yn7 { get; set; }
        public Nullable<System.DateTime> eu_date7 { get; set; }
        public string eu_tno { get; set; }
        public decimal eu_post { get; set; }
        public string eu_emno7 { get; set; }
        public decimal eu_ver3 { get; set; }
        public string eu_vemno3 { get; set; }
        public string eu_vemcname3 { get; set; }
        public Nullable<System.DateTime> eu_vdate3 { get; set; }
        public string eu_trans { get; set; }
        public string eu_spec { get; set; }
        public Nullable<System.DateTime> reply_due_dt { get; set; }
        public string urgent_fg { get; set; }
        public Nullable<int> eu_DateChk { get; set; }
        public string eu_orno2 { get; set; }
        public string eu_orno3 { get; set; }
        public string eu_itemno { get; set; }
        public string eu_badreason { get; set; }
        public Nullable<System.DateTime> eu_cdate { get; set; }
        public decimal eu_Tprice { get; set; }
        public decimal eu_seqno { get; set; }
    }
}
