//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraWorkStatics
    {
        public decimal tb_kind { get; set; }
        public decimal cl_yn { get; set; }
        public System.DateTime the_date { get; set; }
        public string dp_no { get; set; }
        public string dp_name { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> PreLeftCnt { get; set; }
        public Nullable<decimal> PreLeftCnt1 { get; set; }
        public Nullable<decimal> inCnt { get; set; }
        public Nullable<decimal> inCnt1 { get; set; }
        public Nullable<decimal> outCnt { get; set; }
        public Nullable<decimal> outCnt1 { get; set; }
        public Nullable<decimal> leftCnt { get; set; }
        public Nullable<decimal> leftCnt1 { get; set; }
        public Nullable<decimal> WorkTime { get; set; }
        public Nullable<decimal> Eff { get; set; }
        public Nullable<decimal> EffPer { get; set; }
    }
}
