//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class family
    {
        public string fa_cono { get; set; }
        public string fa_emno { get; set; }
        public string fa_bkey { get; set; }
        public string fa_id { get; set; }
        public string fa_name { get; set; }
        public Nullable<decimal> fa_11 { get; set; }
        public Nullable<decimal> fa_sex { get; set; }
        public string fa_12 { get; set; }
        public Nullable<System.DateTime> fa_birth { get; set; }
        public string fa_addr { get; set; }
        public Nullable<System.DateTime> fa_bdate { get; set; }
        public Nullable<System.DateTime> fa_edate { get; set; }
        public string fa_memo { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public decimal fa_14 { get; set; }
    }
}
