//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class faupric
    {
        public string fp_suno { get; set; }
        public string fp_no { get; set; }
        public string fp_emno { get; set; }
        public Nullable<System.DateTime> fp_date1 { get; set; }
        public Nullable<System.DateTime> fp_date2 { get; set; }
        public Nullable<decimal> fp_price1 { get; set; }
        public string fp_memo1 { get; set; }
        public Nullable<decimal> fp_price2 { get; set; }
        public string fp_memo2 { get; set; }
        public Nullable<decimal> fp_price3 { get; set; }
        public string fp_memo3 { get; set; }
        public Nullable<decimal> fp_price4 { get; set; }
        public string fp_memo4 { get; set; }
        public Nullable<decimal> fp_price5 { get; set; }
        public string fp_memo5 { get; set; }
        public Nullable<decimal> fp_price6 { get; set; }
        public string fp_memo6 { get; set; }
        public Nullable<decimal> fp_price7 { get; set; }
        public string fp_memo7 { get; set; }
        public Nullable<decimal> fp_price8 { get; set; }
        public string fp_memo8 { get; set; }
        public Nullable<decimal> fp_price9 { get; set; }
        public string fp_memo9 { get; set; }
        public Nullable<decimal> fp_price10 { get; set; }
        public string fp_memo10 { get; set; }
        public string fp_curr1 { get; set; }
        public string fp_curr2 { get; set; }
        public string fp_curr3 { get; set; }
        public string fp_curr4 { get; set; }
        public string fp_curr5 { get; set; }
        public string fp_curr6 { get; set; }
        public string fp_curr7 { get; set; }
        public string fp_curr8 { get; set; }
        public string fp_curr9 { get; set; }
        public string fp_curr10 { get; set; }
        public string fp_filename { get; set; }
        public string fp_file1 { get; set; }
        public string fp_file2 { get; set; }
        public string fp_file3 { get; set; }
        public string fp_file4 { get; set; }
        public string fp_file5 { get; set; }
        public string fp_file6 { get; set; }
        public string fp_file7 { get; set; }
        public string fp_file8 { get; set; }
        public string fp_file9 { get; set; }
        public string fp_file10 { get; set; }
    }
}
