//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flatbed
    {
        public decimal fb_seqno { get; set; }
        public string fb_mkno { get; set; }
        public string fb_setno { get; set; }
        public decimal fb_finqty { get; set; }
        public Nullable<System.DateTime> fb_enddate { get; set; }
        public string fb_dpno { get; set; }
        public string fb_emno { get; set; }
        public long fb_PKID { get; set; }
        public string fb_tbno { get; set; }
    }
}
