//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fs_pr06_01
    {
        public string bs_dpno { get; set; }
        public string bs_setno { get; set; }
        public string sh_no { get; set; }
        public string sh_spec { get; set; }
        public string sh_curr { get; set; }
        public string myk_name { get; set; }
        public Nullable<decimal> sh_amount { get; set; }
        public Nullable<decimal> sh_amount1 { get; set; }
        public Nullable<decimal> sh_uprice { get; set; }
        public Nullable<decimal> er_excrate { get; set; }
        public Nullable<System.DateTime> sh_date1 { get; set; }
        public Nullable<decimal> NT_Cost { get; set; }
        public string sh_loc1 { get; set; }
        public string con_dpno { get; set; }
        public string con_cuno { get; set; }
        public string con_prno { get; set; }
        public Nullable<System.DateTime> con_lastdate { get; set; }
        public Nullable<System.DateTime> con_upddate1 { get; set; }
        public Nullable<System.DateTime> con_upddate2 { get; set; }
        public string con_shno1 { get; set; }
        public string con_shno2 { get; set; }
        public Nullable<System.DateTime> sh_date { get; set; }
        public string The_BoxNo { get; set; }
        public string The_reason { get; set; }
        public string fs_cemno { get; set; }
        public string fs_cname { get; set; }
        public decimal fs_verify { get; set; }
        public string fs_vname { get; set; }
        public Nullable<System.DateTime> fs_vdate { get; set; }
        public decimal fs_print { get; set; }
        public string sh_loc2 { get; set; }
        public string sh_loc3 { get; set; }
        public decimal con_prtype { get; set; }
        public decimal con_CleanDay { get; set; }
        public string bs_prno { get; set; }
    }
}
