//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gumption
    {
        public decimal gn_seqno { get; set; }
        public Nullable<System.DateTime> gn_date { get; set; }
        public string gn_dpno { get; set; }
        public string gn_emno { get; set; }
        public string gn_name { get; set; }
        public Nullable<decimal> gn_kind { get; set; }
        public Nullable<decimal> gn_source { get; set; }
        public decimal gn_qty { get; set; }
        public decimal gn_qty1 { get; set; }
        public decimal gn_yn { get; set; }
        public string gn_cemno { get; set; }
        public Nullable<System.DateTime> gn_cdate { get; set; }
        public string gn_uemno { get; set; }
        public Nullable<System.DateTime> gn_udate { get; set; }
    }
}
