//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayPrt
    {
        public int Kind { get; set; }
        public int seq { get; set; }
        public string D01 { get; set; }
        public string D02 { get; set; }
        public string D03 { get; set; }
        public string D04 { get; set; }
        public string D05 { get; set; }
        public string D06 { get; set; }
        public string memo01 { get; set; }
        public string memo02 { get; set; }
        public string memo03 { get; set; }
        public string memo04 { get; set; }
        public string memo05 { get; set; }
        public string memo06 { get; set; }
        public string kind01 { get; set; }
        public string kind02 { get; set; }
        public string kind03 { get; set; }
        public string kind04 { get; set; }
        public string kind05 { get; set; }
        public string kind06 { get; set; }
        public string flag01 { get; set; }
        public string flag02 { get; set; }
        public string flag03 { get; set; }
        public string flag04 { get; set; }
        public string flag05 { get; set; }
        public string flag06 { get; set; }
        public string The_YY { get; set; }
        public Nullable<int> The_Cnt { get; set; }
    }
}
