//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrstate
    {
        public string he_yymm { get; set; }
        public string he_dpno { get; set; }
        public Nullable<decimal> he_member { get; set; }
        public Nullable<decimal> he_member1 { get; set; }
        public Nullable<decimal> he_thour { get; set; }
        public Nullable<decimal> he_leahour { get; set; }
        public Nullable<decimal> he_owhour { get; set; }
        public Nullable<decimal> he_member2 { get; set; }
        public Nullable<decimal> he_thour2 { get; set; }
        public Nullable<decimal> he_realamt { get; set; }
        public Nullable<decimal> he_bashour { get; set; }
        public Nullable<decimal> he_dpahour { get; set; }
        public Nullable<decimal> he_dpmem { get; set; }
        public Nullable<decimal> he_dphour { get; set; }
        public Nullable<decimal> he_tothour { get; set; }
    }
}
