//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inform
    {
        public string im_inno { get; set; }
        public string im_cuno { get; set; }
        public string im_cusname { get; set; }
        public string im_orno { get; set; }
        public Nullable<System.DateTime> im_ordate { get; set; }
        public string im_orway { get; set; }
        public string im_salway { get; set; }
        public string im_loc { get; set; }
        public string im_emno { get; set; }
        public string im_cause { get; set; }
        public string im_orginno { get; set; }
        public Nullable<System.DateTime> im_cdate { get; set; }
        public string im_fano { get; set; }
        public Nullable<decimal> im_yn { get; set; }
        public string im_dpno { get; set; }
        public string im_meno1 { get; set; }
        public string im_meno2 { get; set; }
        public Nullable<decimal> im_yn1 { get; set; }
        public Nullable<decimal> im_yn2 { get; set; }
        public Nullable<decimal> im_post { get; set; }
        public Nullable<decimal> im_yn3 { get; set; }
        public string im_bono { get; set; }
        public string im_cemno { get; set; }
        public string SNO { get; set; }
        public string im_pino { get; set; }
        public string im_suno { get; set; }
        public string im_DelReason { get; set; }
        public decimal im_inv { get; set; }
        public decimal im_print { get; set; }
    }
}
