//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class instock
    {
        public string ik_no { get; set; }
        public Nullable<System.DateTime> ik_date { get; set; }
        public Nullable<decimal> ik_reason { get; set; }
        public Nullable<System.DateTime> ik_date1 { get; set; }
        public string ik_suno { get; set; }
        public string ik_emno { get; set; }
        public string ik_mtno { get; set; }
        public string ik_puno2 { get; set; }
        public decimal ik_width { get; set; }
        public decimal ik_long { get; set; }
        public Nullable<decimal> ik_qty { get; set; }
        public Nullable<decimal> ik_qty1 { get; set; }
        public string ik_seqno { get; set; }
        public string ik_diff { get; set; }
        public string ik_loc { get; set; }
        public decimal ik_qty2 { get; set; }
        public Nullable<decimal> ik_price { get; set; }
        public Nullable<decimal> ik_satype { get; set; }
        public string ik_no3 { get; set; }
        public string ik_payno { get; set; }
        public Nullable<decimal> ik_10 { get; set; }
        public Nullable<decimal> ik_yn { get; set; }
        public Nullable<decimal> ik_yn1 { get; set; }
        public Nullable<decimal> ik_yn2 { get; set; }
        public Nullable<decimal> ik_getqty { get; set; }
        public Nullable<decimal> ik_yn3 { get; set; }
        public decimal ik_seq { get; set; }
        public string ik_emno1 { get; set; }
        public decimal ik_yn4 { get; set; }
        public string ik_puno { get; set; }
        public string ik_memo { get; set; }
        public string ik_src { get; set; }
        public Nullable<System.DateTime> ik_cdate { get; set; }
        public decimal ik_doTransfer { get; set; }
        public decimal ik_srcSeqno { get; set; }
    }
}
