//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class insure
    {
        public string is_emno { get; set; }
        public string is_id { get; set; }
        public string is_seq { get; set; }
        public Nullable<System.DateTime> is_date { get; set; }
        public string is_cono { get; set; }
        public Nullable<decimal> is_11 { get; set; }
        public decimal is_12 { get; set; }
        public string is_13 { get; set; }
        public decimal is_14 { get; set; }
        public string is_memo { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
    }
}
