//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsureDetail
    {
        public string id_yymm { get; set; }
        public string id_emno { get; set; }
        public string id_id { get; set; }
        public Nullable<System.DateTime> id_birth { get; set; }
        public decimal id_yn { get; set; }
        public string id_cname { get; set; }
        public decimal id_amt { get; set; }
        public decimal id_kind { get; set; }
        public decimal id_diff { get; set; }
        public string id_yymm1 { get; set; }
    }
}
