//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsureFam
    {
        public decimal im_seqno { get; set; }
        public string im_emno { get; set; }
        public string im_cname { get; set; }
        public string im_famname { get; set; }
        public string im_id { get; set; }
        public decimal im_fa11 { get; set; }
        public decimal im_11 { get; set; }
        public System.DateTime im_cdate { get; set; }
    }
}
