//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegratedReport_YM
    {
        public string YM1 { get; set; }
        public string YM2 { get; set; }
        public string dpno { get; set; }
        public string dpname { get; set; }
        public Nullable<decimal> Col1 { get; set; }
        public Nullable<decimal> Col2 { get; set; }
        public Nullable<decimal> Col3 { get; set; }
        public Nullable<decimal> Col4 { get; set; }
        public Nullable<decimal> Col5 { get; set; }
        public Nullable<decimal> Col6 { get; set; }
        public Nullable<decimal> Col7 { get; set; }
        public Nullable<decimal> Col8 { get; set; }
        public Nullable<decimal> Col9 { get; set; }
        public Nullable<decimal> Col10 { get; set; }
        public Nullable<decimal> Col11 { get; set; }
        public Nullable<decimal> Col12 { get; set; }
        public decimal MonthCnt { get; set; }
    }
}
