//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invhisth
    {
        public string in_no { get; set; }
        public string in_chno { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string in_ufyno { get; set; }
        public string in_cuno { get; set; }
        public Nullable<System.DateTime> in_ddate { get; set; }
        public string in_acpe { get; set; }
        public string in_acpa { get; set; }
        public Nullable<decimal> in_aby { get; set; }
        public Nullable<decimal> in_subtot { get; set; }
        public Nullable<decimal> in_taxatt { get; set; }
        public Nullable<decimal> in_tax { get; set; }
        public Nullable<decimal> in_priny { get; set; }
        public Nullable<decimal> in_ediy { get; set; }
        public string in_faatt { get; set; }
        public string in_yymm { get; set; }
        public decimal in_seqno { get; set; }
    }
}
