//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invhistb
    {
        public string iv_no { get; set; }
        public string iv_pname { get; set; }
        public Nullable<decimal> iv_qty { get; set; }
        public string iv_unit { get; set; }
        public Nullable<decimal> iv_price { get; set; }
        public Nullable<decimal> iv_amt { get; set; }
        public string iv_memo { get; set; }
        public string iv_tno { get; set; }
        public string iv_pdno { get; set; }
        public string iv_chno { get; set; }
        public Nullable<decimal> iv_nprec { get; set; }
        public string iv_cupdno { get; set; }
        public string iv_orno { get; set; }
        public string iv_yymm { get; set; }
        public Nullable<decimal> iv_ibseqno { get; set; }
        public decimal iv_seqno { get; set; }
    }
}
