//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invno
    {
        public string ie_year { get; set; }
        public string ie_month { get; set; }
        public string ie_word { get; set; }
        public string ie_fno { get; set; }
        public string ie_lno { get; set; }
        public string ie_nno { get; set; }
        public decimal ie_kind { get; set; }
        public string ie_fno_b { get; set; }
        public string ie_lno_b { get; set; }
        public string ie_nno_b { get; set; }
        public string ie_word_b { get; set; }
    }
}
