//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceDis
    {
        public string ihd_no { get; set; }
        public Nullable<System.DateTime> ihd_date { get; set; }
        public string ihd_ufyno { get; set; }
        public string ihd_cuno { get; set; }
        public Nullable<System.DateTime> ihd_ddate { get; set; }
        public string ihd_acpe { get; set; }
        public string ibd_pname { get; set; }
        public Nullable<decimal> ibd_qty { get; set; }
        public string ibd_unit { get; set; }
        public Nullable<decimal> ibd_price { get; set; }
        public Nullable<decimal> ibd_amt { get; set; }
        public string ibd_memo { get; set; }
        public string ibd_tno { get; set; }
        public string ibd_pdno { get; set; }
        public string ibd_cupdno { get; set; }
        public string ibd_orno { get; set; }
    }
}
