//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoicedh
    {
        public string inh_no { get; set; }
        public string inh_cuno { get; set; }
        public string inh_cuname { get; set; }
        public Nullable<System.DateTime> inh_invdate { get; set; }
        public Nullable<System.DateTime> inh_update { get; set; }
        public string inh_inno { get; set; }
        public string inh_order { get; set; }
        public Nullable<System.DateTime> inh_shipdate { get; set; }
        public string inh_shipfrom { get; set; }
        public string inh_shipto { get; set; }
        public string inh_curr { get; set; }
        public string inh_head1 { get; set; }
        public string inh_loc { get; set; }
        public string inh_forwad { get; set; }
        public Nullable<decimal> inh_ttlamt { get; set; }
        public string inh_tailer1 { get; set; }
        public string inh_tailer2 { get; set; }
        public string inh_sales { get; set; }
        public string inh_emno { get; set; }
        public Nullable<decimal> inh_fileud { get; set; }
        public Nullable<System.DateTime> inh_dbdate { get; set; }
        public string inh_dbno { get; set; }
        public string inh_fob { get; set; }
        public string inh_remark { get; set; }
        public string inh_tel { get; set; }
        public string inh_fax { get; set; }
        public string inh_attn { get; set; }
        public decimal inh_confirm { get; set; }
        public decimal inh_post { get; set; }
        public string inh_femno { get; set; }
        public string inh_thno { get; set; }
        public Nullable<System.DateTime> inh_thdate { get; set; }
        public decimal inh_thamt { get; set; }
        public decimal inh_excrate { get; set; }
        public decimal inh_kind { get; set; }
        public string inh_memo { get; set; }
        public string inh_F5NO { get; set; }
        public string inh_fileud_Show { get; set; }
        public Nullable<System.DateTime> QryDate1 { get; set; }
        public Nullable<System.DateTime> QryDate2 { get; set; }
        public Nullable<System.DateTime> QryDate3 { get; set; }
        public Nullable<System.DateTime> QryDate4 { get; set; }
        public string inh_PINO { get; set; }
        public Nullable<System.DateTime> QryDate5 { get; set; }
        public Nullable<System.DateTime> QryDate6 { get; set; }
        public string inh_shipno { get; set; }
        public decimal inh_close { get; set; }
        public decimal inh_declaration { get; set; }
    }
}
