//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceh_Temp
    {
        public string ih_no { get; set; }
        public string ih_chno { get; set; }
        public Nullable<System.DateTime> ih_date { get; set; }
        public string ih_ufyno { get; set; }
        public string ih_cuno { get; set; }
        public Nullable<System.DateTime> ih_ddate { get; set; }
        public string ih_acpe { get; set; }
        public string ih_acpa { get; set; }
        public decimal ih_aby { get; set; }
        public decimal ih_subtot { get; set; }
        public decimal ih_taxatt { get; set; }
        public decimal ih_tax { get; set; }
        public decimal ih_priny { get; set; }
        public decimal ih_ediy { get; set; }
        public string ih_faatt { get; set; }
        public decimal ih_post { get; set; }
    }
}
