//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISODOC
    {
        public int The_Kind { get; set; }
        public string The_No { get; set; }
        public string The_Name { get; set; }
        public Nullable<System.DateTime> v1 { get; set; }
        public Nullable<System.DateTime> v2 { get; set; }
        public Nullable<System.DateTime> v3 { get; set; }
        public Nullable<System.DateTime> v4 { get; set; }
        public Nullable<System.DateTime> v5 { get; set; }
        public Nullable<System.DateTime> v6 { get; set; }
        public Nullable<System.DateTime> v7 { get; set; }
        public Nullable<System.DateTime> v8 { get; set; }
        public Nullable<System.DateTime> v9 { get; set; }
        public Nullable<System.DateTime> v10 { get; set; }
        public Nullable<System.DateTime> v11 { get; set; }
        public Nullable<System.DateTime> v12 { get; set; }
        public Nullable<System.DateTime> v13 { get; set; }
        public Nullable<System.DateTime> v14 { get; set; }
        public Nullable<System.DateTime> v15 { get; set; }
    }
}
