//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class knifeCar
    {
        public decimal kc_seqno { get; set; }
        public string kc_mkno { get; set; }
        public string kc_setno { get; set; }
        public decimal kc_finqty { get; set; }
        public Nullable<System.DateTime> kc_enddate { get; set; }
        public string kc_dpno { get; set; }
        public string kc_emno { get; set; }
        public long kc_PKID { get; set; }
        public string kc_tbno { get; set; }
    }
}
