//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class letter
    {
        public string le_dsn { get; set; }
        public Nullable<System.DateTime> le_date { get; set; }
        public string le_dpno { get; set; }
        public string le_dpname { get; set; }
        public string le_emno { get; set; }
        public string le_cname { get; set; }
        public string le_kind { get; set; }
        public string le_unit { get; set; }
        public string le_content { get; set; }
        public string le_upfile { get; set; }
        public string le_cemno { get; set; }
        public string le_ccname { get; set; }
        public Nullable<System.DateTime> le_cdate { get; set; }
        public Nullable<int> le_yn { get; set; }
        public Nullable<System.DateTime> le_yndate { get; set; }
        public string le_upfile2 { get; set; }
        public string le_upfile3 { get; set; }
        public string le_upfile4 { get; set; }
        public string le_upfile5 { get; set; }
        public string le_sendword { get; set; }
        public string le_group { get; set; }
        public decimal le_post { get; set; }
    }
}
