//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loworkChg
    {
        public Nullable<System.DateTime> lw_date { get; set; }
        public string lw_emno { get; set; }
        public string lw_dpno { get; set; }
        public Nullable<decimal> lw_watt { get; set; }
        public string lw_mkno { get; set; }
        public string lw_ws { get; set; }
        public decimal lw_fqty { get; set; }
        public decimal lw_carqty { get; set; }
        public decimal lw_priqty { get; set; }
        public decimal lw_priqty1 { get; set; }
        public decimal lw_shtime { get; set; }
        public decimal lw_motime { get; set; }
        public decimal lw_tcqty { get; set; }
        public decimal lw_pcqty { get; set; }
        public decimal lw_fqtyO { get; set; }
        public decimal lw_carqtyO { get; set; }
        public decimal lw_priqtyO { get; set; }
        public decimal lw_priqty1O { get; set; }
        public decimal lw_shtimeO { get; set; }
        public decimal lw_motimeO { get; set; }
        public decimal lw_tcqtyO { get; set; }
        public decimal lw_pcqtyO { get; set; }
        public string lw_uemno { get; set; }
        public Nullable<System.DateTime> lw_update { get; set; }
        public decimal lw_times1 { get; set; }
        public decimal lw_times2 { get; set; }
        public decimal lw_times3 { get; set; }
        public decimal lw_times1O { get; set; }
        public decimal lw_times2O { get; set; }
        public decimal lw_times3O { get; set; }
    }
}
