//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class macct
    {
        public string mac_no { get; set; }
        public string mac_name { get; set; }
        public string mac_ename { get; set; }
        public decimal mac_10 { get; set; }
        public string mac_11 { get; set; }
        public string mac_makno { get; set; }
        public Nullable<decimal> mac_12 { get; set; }
        public Nullable<decimal> mac_13 { get; set; }
        public Nullable<decimal> mac_14 { get; set; }
        public string mac_cskno { get; set; }
        public Nullable<decimal> mac_15 { get; set; }
        public string mac_mykno { get; set; }
        public Nullable<decimal> mac_16 { get; set; }
        public Nullable<decimal> mac_17 { get; set; }
        public string compid { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
