//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maform
    {
        public string mf_mtno { get; set; }
        public string mf_noteno { get; set; }
        public Nullable<System.DateTime> mf_date { get; set; }
        public string mf_setno { get; set; }
        public string mf_formno { get; set; }
        public Nullable<decimal> mf_reqno { get; set; }
        public Nullable<decimal> mf_qty { get; set; }
        public string mf_emno { get; set; }
        public Nullable<decimal> mf_print { get; set; }
    }
}
