//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class marketmon
    {
        public string mm_year { get; set; }
        public string mm_kind { get; set; }
        public string mm_cuno { get; set; }
        public string mm_cusname { get; set; }
        public Nullable<decimal> mm_month1 { get; set; }
        public Nullable<decimal> mm_month2 { get; set; }
        public Nullable<decimal> mm_month3 { get; set; }
        public Nullable<decimal> mm_month4 { get; set; }
        public Nullable<decimal> mm_month5 { get; set; }
        public Nullable<decimal> mm_month6 { get; set; }
        public Nullable<decimal> mm_month7 { get; set; }
        public Nullable<decimal> mm_month8 { get; set; }
        public Nullable<decimal> mm_month9 { get; set; }
        public Nullable<decimal> mm_month10 { get; set; }
        public Nullable<decimal> mm_month11 { get; set; }
        public Nullable<decimal> mm_month12 { get; set; }
        public string mm_dpno1 { get; set; }
        public string mm_dpno2 { get; set; }
        public string mm_dpno3 { get; set; }
        public string mm_dpno4 { get; set; }
        public string mm_dpno5 { get; set; }
        public string mm_dpno6 { get; set; }
        public string mm_dpno7 { get; set; }
        public string mm_dpno8 { get; set; }
        public string mm_dpno9 { get; set; }
        public string mm_dpno10 { get; set; }
        public string mm_dpno11 { get; set; }
        public string mm_dpno12 { get; set; }
        public string mm_mykno { get; set; }
        public decimal mm_month1_NT { get; set; }
        public decimal mm_month2_NT { get; set; }
        public decimal mm_month3_NT { get; set; }
        public decimal mm_month4_NT { get; set; }
        public decimal mm_month5_NT { get; set; }
        public decimal mm_month6_NT { get; set; }
        public decimal mm_month7_NT { get; set; }
        public decimal mm_month8_NT { get; set; }
        public decimal mm_month9_NT { get; set; }
        public decimal mm_month10_NT { get; set; }
        public decimal mm_month11_NT { get; set; }
        public decimal mm_month12_NT { get; set; }
    }
}
