//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matanal
    {
        public string ml_ym { get; set; }
        public string ml_mkno { get; set; }
        public string ml_setno { get; set; }
        public Nullable<decimal> ml_paper { get; set; }
        public string ml_mtno { get; set; }
        public Nullable<decimal> ml_rrlnum { get; set; }
        public Nullable<decimal> ml_uprice { get; set; }
        public string ml_cpro { get; set; }
        public Nullable<decimal> ml_pronum { get; set; }
        public string ml_size { get; set; }
        public Nullable<decimal> ml_matfee { get; set; }
        public Nullable<decimal> ml_caramt { get; set; }
        public Nullable<decimal> ml_rcaramt { get; set; }
        public Nullable<decimal> ml_wfee { get; set; }
        public Nullable<decimal> ml_samt { get; set; }
        public Nullable<decimal> ml_cprint { get; set; }
    }
}
