//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatApply
    {
        public string ma_no { get; set; }
        public string ma_emno { get; set; }
        public string ma_name { get; set; }
        public string ma_dpno { get; set; }
        public string ma_dpname { get; set; }
        public Nullable<System.DateTime> ma_date1 { get; set; }
        public Nullable<System.DateTime> ma_date2 { get; set; }
        public decimal ma_kind { get; set; }
        public string ma_spec { get; set; }
        public decimal ma_security { get; set; }
        public string ma_color { get; set; }
        public string ma_thickness { get; set; }
        public string ma_viscosity { get; set; }
        public string ma_viscosity1 { get; set; }
        public decimal ma_qty { get; set; }
        public string ma_TheUnit { get; set; }
        public string ma_similar { get; set; }
        public string ma_content1 { get; set; }
        public string ma_content2 { get; set; }
        public decimal ma_Rohs { get; set; }
        public decimal ma_Reach { get; set; }
        public decimal ma_Cpsia { get; set; }
        public decimal ma_other { get; set; }
        public decimal ma_sample { get; set; }
        public Nullable<System.DateTime> ma_deletedate { get; set; }
        public Nullable<System.DateTime> ma_postdate { get; set; }
        public string ma_vemno { get; set; }
        public string ma_vname { get; set; }
        public Nullable<System.DateTime> ma_vdate { get; set; }
        public string ma_reason { get; set; }
        public string ma_vemno1 { get; set; }
        public string ma_vname1 { get; set; }
        public Nullable<System.DateTime> ma_vdate1 { get; set; }
        public string ma_reason1 { get; set; }
        public string ma_vemno2 { get; set; }
        public string ma_vname2 { get; set; }
        public Nullable<System.DateTime> ma_vdate2 { get; set; }
        public string ma_vemno3 { get; set; }
        public string ma_vname3 { get; set; }
        public Nullable<System.DateTime> ma_vdate3 { get; set; }
        public string ma_spec1 { get; set; }
        public string ma_suno { get; set; }
        public string ma_supplier { get; set; }
        public string ma_suno1 { get; set; }
        public string ma_supplier1 { get; set; }
        public string ma_Ptype { get; set; }
        public string ma_Ptype1 { get; set; }
        public string ma_Otype { get; set; }
        public string ma_Otype1 { get; set; }
        public string ma_content3 { get; set; }
        public string ma_mtno { get; set; }
        public string ma_spec2 { get; set; }
        public decimal ma_src { get; set; }
        public string ma_suno2 { get; set; }
        public string ma_supplier2 { get; set; }
        public decimal ma_maxqty { get; set; }
        public decimal ma_safeqty { get; set; }
        public decimal ma_point { get; set; }
        public decimal ma_minqty { get; set; }
        public decimal ma_cost { get; set; }
        public string ma_curr { get; set; }
        public string ma_unit { get; set; }
        public string ma_unit1 { get; set; }
        public decimal ma_flag { get; set; }
        public string ma_TheDpno { get; set; }
        public string ma_TheDpname { get; set; }
        public decimal ma_date4 { get; set; }
        public decimal ma_atkind { get; set; }
        public decimal ma_type2 { get; set; }
        public decimal ma_process { get; set; }
        public decimal ma_close { get; set; }
        public string ma_reason2 { get; set; }
        public string ma_reason3 { get; set; }
    }
}
