//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatCostChg
    {
        public decimal mc_seq { get; set; }
        public string mc_mtno { get; set; }
        public string mc_curr { get; set; }
        public Nullable<decimal> mc_cost { get; set; }
        public Nullable<System.DateTime> mc_cdate { get; set; }
        public string mc_emno { get; set; }
    }
}
