//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatDayUse
    {
        public string md_mtno { get; set; }
        public string md_diff { get; set; }
        public decimal md_long { get; set; }
        public decimal md_width { get; set; }
        public decimal md_qty { get; set; }
        public decimal md_qty1 { get; set; }
        public Nullable<System.DateTime> md_cdate { get; set; }
    }
}
