//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public string mt_no { get; set; }
        public string mt_spec { get; set; }
        public string mt_unit { get; set; }
        public string mt_unit1 { get; set; }
        public Nullable<decimal> mt_kind { get; set; }
        public Nullable<System.DateTime> mt_date { get; set; }
        public Nullable<decimal> mt_maxqty { get; set; }
        public Nullable<decimal> mt_safeqty { get; set; }
        public Nullable<decimal> mt_point { get; set; }
        public Nullable<decimal> mt_minqty { get; set; }
        public Nullable<decimal> mt_cost { get; set; }
        public decimal mt_qty { get; set; }
        public decimal mt_wayqty { get; set; }
        public Nullable<System.DateTime> mt_date1 { get; set; }
        public Nullable<System.DateTime> mt_date2 { get; set; }
        public Nullable<System.DateTime> mt_date3 { get; set; }
        public decimal mt_date4 { get; set; }
        public string mt_memo { get; set; }
        public Nullable<decimal> mt_src { get; set; }
        public Nullable<decimal> mt_avgqty { get; set; }
        public Nullable<decimal> mt_type2 { get; set; }
        public Nullable<decimal> mt_dayqty { get; set; }
        public string mt_curr { get; set; }
        public decimal mt_long { get; set; }
        public decimal mt_width { get; set; }
        public string mt_emno { get; set; }
        public string mt_orno { get; set; }
        public string mt_payno { get; set; }
        public decimal mt_use { get; set; }
        public decimal mt_flag { get; set; }
        public string mt_spec_p { get; set; }
        public decimal mt_safeday { get; set; }
        public decimal mt_keep { get; set; }
        public decimal mt_atkind { get; set; }
        public decimal mt_period { get; set; }
        public string mt_dpno { get; set; }
        public string mt_dpname { get; set; }
        public decimal mt_KeepLimit { get; set; }
        public decimal mt_pollution { get; set; }
        public decimal mt_paperloss { get; set; }
        public string mt_memo1 { get; set; }
        public string mt_spec_e { get; set; }
    }
}
