//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBOItem
    {
        public string mi_year { get; set; }
        public decimal mi_kind { get; set; }
        public decimal mi_itemno { get; set; }
        public Nullable<decimal> mi_showno { get; set; }
        public string mi_name { get; set; }
        public Nullable<decimal> mi_score { get; set; }
        public string mi_desc { get; set; }
        public string mi_formula { get; set; }
        public decimal mi_decimal { get; set; }
        public string mi_qkind { get; set; }
        public decimal mi_chklevel { get; set; }
        public decimal mi_chkKind { get; set; }
    }
}
