//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBOResult2
    {
        public string mr_yymm { get; set; }
        public decimal mr_kind { get; set; }
        public decimal mr_itemno { get; set; }
        public Nullable<decimal> mr_showno { get; set; }
        public string mr_dpno { get; set; }
        public string mr_dpname { get; set; }
        public string mr_name { get; set; }
        public string mr_desc { get; set; }
        public string mr_formula { get; set; }
        public Nullable<decimal> mr_decimal { get; set; }
        public string mr_qkind { get; set; }
        public decimal mr_score { get; set; }
        public decimal mr_goal { get; set; }
        public decimal mr_result { get; set; }
        public decimal mr_percent { get; set; }
        public decimal mr_ItemScore { get; set; }
        public decimal mr_Tscore { get; set; }
        public decimal mr_rank { get; set; }
        public decimal mr_ItemRank { get; set; }
    }
}
