//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MisModify
    {
        public string MM_NO { get; set; }
        public string MM_EMNO { get; set; }
        public string MM_NAME { get; set; }
        public string MM_DPNO { get; set; }
        public string MM_DPNAME { get; set; }
        public short MM_ATTACH { get; set; }
        public Nullable<System.DateTime> MM_DATE1 { get; set; }
        public Nullable<System.DateTime> MM_DATE2 { get; set; }
        public string MM_SUBJECT { get; set; }
        public string MM_CONTENT1 { get; set; }
        public Nullable<System.DateTime> MM_UPDATE { get; set; }
        public Nullable<System.DateTime> MM_ACDATE { get; set; }
        public string MM_ACEMNO { get; set; }
        public string MM_ACNAME { get; set; }
        public Nullable<System.DateTime> MM_PCDATE { get; set; }
        public Nullable<decimal> MM_PCHOUR { get; set; }
        public Nullable<System.DateTime> MM_RCDATE { get; set; }
        public Nullable<decimal> MM_RCHOUR { get; set; }
        public Nullable<decimal> MM_POST { get; set; }
        public Nullable<decimal> MM_YN { get; set; }
        public Nullable<decimal> MM_YN1 { get; set; }
        public Nullable<decimal> MM_CLOSE { get; set; }
        public string MM_ACBACKMEMO { get; set; }
        public string MM_MEMO1 { get; set; }
        public string MM_MEMO2 { get; set; }
        public string MM_MEMO3 { get; set; }
        public string MM_FANO { get; set; }
        public Nullable<System.DateTime> MM_SCHDATE { get; set; }
        public string MM_CONTENT2 { get; set; }
        public decimal MM_U1 { get; set; }
        public decimal MM_U2 { get; set; }
        public decimal MM_U3 { get; set; }
        public decimal MM_U4 { get; set; }
        public decimal MM_U5 { get; set; }
        public Nullable<int> mm_sub { get; set; }
        public string MM_MEMO4 { get; set; }
        public string MM_ONEMNO { get; set; }
        public string MM_ONCNAME { get; set; }
        public Nullable<System.DateTime> MM_ONDATE { get; set; }
        public decimal MM_Print { get; set; }
        public decimal mm_postYN { get; set; }
        public Nullable<int> MM_Confirm { get; set; }
        public string MM_ConfirmEMNO { get; set; }
        public string MM_ConfirmNAME { get; set; }
        public Nullable<System.DateTime> MM_ConfirmDATE { get; set; }
        public string MM_ConfirmMEMO { get; set; }
    }
}
