//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MisSerReject
    {
        public string MST_MSNO { get; set; }
        public string MST_SUBJECT { get; set; }
        public string MST_CONTENT1 { get; set; }
        public string MST_ACBACKMEMO { get; set; }
        public Nullable<System.DateTime> MST_DATE { get; set; }
        public string MST_ACEMNO { get; set; }
        public string MST_ACNAME { get; set; }
    }
}
