//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modbase
    {
        public decimal mb_item { get; set; }
        public string mb_setno { get; set; }
        public string mb_loc { get; set; }
        public Nullable<decimal> mb_qty { get; set; }
        public string mb_memo { get; set; }
        public Nullable<decimal> mb_time { get; set; }
        public Nullable<System.DateTime> mb_date { get; set; }
        public Nullable<decimal> mb_share { get; set; }
        public string mb_setno1 { get; set; }
        public System.DateTime mb_date1 { get; set; }
        public Nullable<System.DateTime> mb_date2 { get; set; }
        public string mb_emno { get; set; }
        public string mb_emno1 { get; set; }
        public Nullable<System.DateTime> mb_opdate { get; set; }
        public string mb_version { get; set; }
        public string mb_mkno { get; set; }
        public string mb_reason { get; set; }
        public string mb_dpno { get; set; }
        public decimal mb_modflag { get; set; }
        public decimal mb_kind { get; set; }
        public decimal mb_kseq { get; set; }
        public string mb_locP { get; set; }
        public int mb_usage { get; set; }
    }
}
