//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModRecord
    {
        public decimal md_seqno { get; set; }
        public string md_mkno { get; set; }
        public string md_setno { get; set; }
        public string md_setno1 { get; set; }
        public string md_prno { get; set; }
        public Nullable<System.DateTime> md_date { get; set; }
        public int md_usage { get; set; }
        public int md_mpaper { get; set; }
        public int md_TotalUse { get; set; }
        public string md_remake { get; set; }
    }
}
