//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModStore
    {
        public string ms_kind { get; set; }
        public string ms_id { get; set; }
        public int ms_level { get; set; }
        public int ms_place { get; set; }
        public int ms_piece { get; set; }
        public int ms_height { get; set; }
        public int ms_width { get; set; }
        public int ms_depth { get; set; }
        public string ms_desc { get; set; }
        public decimal ms_zero { get; set; }
    }
}
