//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mpgoa
    {
        public string mp_ym { get; set; }
        public Nullable<decimal> mp_depa1 { get; set; }
        public Nullable<decimal> mp_depa11 { get; set; }
        public Nullable<decimal> mp_depa2 { get; set; }
        public Nullable<decimal> mp_depa21 { get; set; }
        public Nullable<decimal> mp_depa3 { get; set; }
        public Nullable<decimal> mp_depa31 { get; set; }
        public Nullable<decimal> mp_depa4 { get; set; }
        public Nullable<decimal> mp_depa41 { get; set; }
        public decimal mp_depa5 { get; set; }
        public decimal mp_depa51 { get; set; }
        public Nullable<decimal> mp_depb1 { get; set; }
        public Nullable<decimal> mp_depb11 { get; set; }
        public Nullable<decimal> mp_depb2 { get; set; }
        public Nullable<decimal> mp_depb21 { get; set; }
        public Nullable<decimal> mp_depb3 { get; set; }
        public Nullable<decimal> mp_depb31 { get; set; }
        public Nullable<decimal> mp_depb4 { get; set; }
        public Nullable<decimal> mp_depb41 { get; set; }
        public decimal mp_depb5 { get; set; }
        public decimal mp_depb51 { get; set; }
        public Nullable<decimal> mp_depc1 { get; set; }
        public Nullable<decimal> mp_depc11 { get; set; }
        public Nullable<decimal> mp_depc2 { get; set; }
        public Nullable<decimal> mp_depc21 { get; set; }
        public Nullable<decimal> mp_depc3 { get; set; }
        public Nullable<decimal> mp_depc31 { get; set; }
        public Nullable<decimal> mp_depc4 { get; set; }
        public Nullable<decimal> mp_depc41 { get; set; }
        public decimal mp_depc5 { get; set; }
        public decimal mp_depc51 { get; set; }
        public Nullable<decimal> mp_depd1 { get; set; }
        public Nullable<decimal> mp_depd11 { get; set; }
        public decimal mp_depd2 { get; set; }
        public decimal mp_depd21 { get; set; }
        public Nullable<decimal> mp_depd3 { get; set; }
        public Nullable<decimal> mp_depd31 { get; set; }
        public decimal mp_depd4 { get; set; }
        public decimal mp_depd41 { get; set; }
        public decimal mp_depd5 { get; set; }
        public decimal mp_depd51 { get; set; }
        public Nullable<decimal> mp_depe1 { get; set; }
        public Nullable<decimal> mp_depe11 { get; set; }
        public decimal mp_depe2 { get; set; }
        public decimal mp_depe21 { get; set; }
        public Nullable<decimal> mp_depe3 { get; set; }
        public Nullable<decimal> mp_depe31 { get; set; }
        public decimal mp_depe4 { get; set; }
        public decimal mp_depe41 { get; set; }
        public decimal mp_depe5 { get; set; }
        public decimal mp_depe51 { get; set; }
        public Nullable<decimal> mp_depf1 { get; set; }
        public Nullable<decimal> mp_depf11 { get; set; }
        public decimal mp_depf2 { get; set; }
        public decimal mp_depf21 { get; set; }
        public Nullable<decimal> mp_depf3 { get; set; }
        public Nullable<decimal> mp_depf31 { get; set; }
        public decimal mp_depf4 { get; set; }
        public decimal mp_depf41 { get; set; }
        public decimal mp_depf5 { get; set; }
        public decimal mp_depf51 { get; set; }
        public Nullable<decimal> mp_depg1 { get; set; }
        public Nullable<decimal> mp_depg11 { get; set; }
        public decimal mp_depg2 { get; set; }
        public decimal mp_depg21 { get; set; }
        public Nullable<decimal> mp_depg3 { get; set; }
        public Nullable<decimal> mp_depg31 { get; set; }
        public decimal mp_depg4 { get; set; }
        public decimal mp_depg41 { get; set; }
        public decimal mp_depg5 { get; set; }
        public decimal mp_depg51 { get; set; }
        public Nullable<decimal> mp_despl { get; set; }
        public Nullable<decimal> mp_despl1 { get; set; }
        public Nullable<decimal> mp_deskn { get; set; }
        public Nullable<decimal> mp_deskn1 { get; set; }
        public Nullable<decimal> mp_disk { get; set; }
        public Nullable<decimal> mp_disk1 { get; set; }
        public Nullable<decimal> mp_day { get; set; }
        public Nullable<decimal> mp_despl2 { get; set; }
        public Nullable<decimal> mp_despl21 { get; set; }
        public Nullable<decimal> mp_disk2 { get; set; }
        public Nullable<decimal> mp_disk21 { get; set; }
        public Nullable<decimal> mp_ohour { get; set; }
        public Nullable<decimal> mp_chour { get; set; }
        public Nullable<decimal> mp_part { get; set; }
        public Nullable<decimal> mp_part1 { get; set; }
        public Nullable<decimal> mp_bqty1 { get; set; }
        public Nullable<decimal> mp_bqty2 { get; set; }
        public Nullable<decimal> mp_bqty3 { get; set; }
        public Nullable<decimal> mp_netnum { get; set; }
        public Nullable<decimal> mp_part010 { get; set; }
        public Nullable<decimal> mp_part011 { get; set; }
        public Nullable<decimal> mp_part020 { get; set; }
        public Nullable<decimal> mp_part021 { get; set; }
        public Nullable<decimal> mp_part030 { get; set; }
        public Nullable<decimal> mp_part031 { get; set; }
        public Nullable<decimal> mp_part040 { get; set; }
        public Nullable<decimal> mp_part041 { get; set; }
        public Nullable<decimal> mp_part050 { get; set; }
        public Nullable<decimal> mp_part051 { get; set; }
        public Nullable<decimal> mp_filmuse { get; set; }
        public decimal mp_jit { get; set; }
        public decimal mp_jit1 { get; set; }
        public decimal mp_jit2 { get; set; }
        public decimal mp_jit3 { get; set; }
        public decimal mp_jit4 { get; set; }
        public decimal mp_jit5 { get; set; }
        public decimal mp_turn1 { get; set; }
        public decimal mp_turn11 { get; set; }
        public decimal mp_turn2 { get; set; }
        public decimal mp_turn21 { get; set; }
        public decimal mp_raised { get; set; }
        public decimal mp_raised1 { get; set; }
        public decimal mp_daycount { get; set; }
        public decimal mp_NetA { get; set; }
        public decimal mp_NetB { get; set; }
        public decimal mp_netsupp { get; set; }
        public decimal mp_ohour1 { get; set; }
        public decimal mp_depa12 { get; set; }
        public decimal mp_depa22 { get; set; }
        public decimal mp_depa32 { get; set; }
        public decimal mp_depa42 { get; set; }
        public decimal mp_depa52 { get; set; }
        public decimal mp_depb12 { get; set; }
        public decimal mp_depb22 { get; set; }
        public decimal mp_depb32 { get; set; }
        public decimal mp_depb42 { get; set; }
        public decimal mp_depb52 { get; set; }
        public decimal mp_depc12 { get; set; }
        public decimal mp_depc22 { get; set; }
        public decimal mp_depc32 { get; set; }
        public decimal mp_depc42 { get; set; }
        public decimal mp_depc52 { get; set; }
        public decimal mp_depd12 { get; set; }
        public decimal mp_depd22 { get; set; }
        public decimal mp_depd32 { get; set; }
        public decimal mp_depd42 { get; set; }
        public decimal mp_depd52 { get; set; }
        public decimal mp_depe12 { get; set; }
        public decimal mp_depe22 { get; set; }
        public decimal mp_depe32 { get; set; }
        public decimal mp_depe42 { get; set; }
        public decimal mp_depe52 { get; set; }
        public decimal mp_depf12 { get; set; }
        public decimal mp_depf22 { get; set; }
        public decimal mp_depf32 { get; set; }
        public decimal mp_depf42 { get; set; }
        public decimal mp_depf52 { get; set; }
        public decimal mp_depg12 { get; set; }
        public decimal mp_depg22 { get; set; }
        public decimal mp_depg32 { get; set; }
        public decimal mp_depg42 { get; set; }
        public decimal mp_depg52 { get; set; }
        public decimal mp_ReachHour { get; set; }
    }
}
