//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msalaryC
    {
        public int me_dsn { get; set; }
        public string me_kind { get; set; }
        public string me_dpno { get; set; }
        public string me_yymm { get; set; }
        public Nullable<int> me_amt { get; set; }
        public Nullable<int> me_heatotal { get; set; }
        public Nullable<int> me_sub { get; set; }
        public Nullable<double> me_rate { get; set; }
        public Nullable<int> me_explain { get; set; }
        public string me_saltype { get; set; }
        public string me_costym { get; set; }
    }
}
