//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msalary
    {
        public string my_emno { get; set; }
        public string my_dpno { get; set; }
        public string my_ym { get; set; }
        public Nullable<decimal> my_baspay { get; set; }
        public Nullable<decimal> my_pospri { get; set; }
        public Nullable<decimal> my_abpri { get; set; }
        public Nullable<decimal> my_foodpri { get; set; }
        public Nullable<decimal> my_rward { get; set; }
        public Nullable<decimal> my_shifsal { get; set; }
        public Nullable<decimal> my_effsal { get; set; }
        public Nullable<decimal> my_insour { get; set; }
        public Nullable<decimal> my_trasal { get; set; }
        public Nullable<decimal> my_ntaxot { get; set; }
        public Nullable<decimal> my_taxot { get; set; }
        public Nullable<decimal> my_ottime { get; set; }
        public Nullable<decimal> my_otsal { get; set; }
        public Nullable<decimal> my_labpri { get; set; }
        public Nullable<decimal> my_heapri { get; set; }
        public Nullable<decimal> my_empben { get; set; }
        public Nullable<decimal> my_leave { get; set; }
        public Nullable<decimal> my_foodsal { get; set; }
        public Nullable<decimal> my_tax { get; set; }
        public Nullable<decimal> my_prepri { get; set; }
        public Nullable<decimal> my_otdepri { get; set; }
        public Nullable<decimal> my_nosal { get; set; }
        public Nullable<decimal> my_artot { get; set; }
        public Nullable<decimal> my_drtot { get; set; }
        public Nullable<decimal> my_inftot { get; set; }
        public Nullable<decimal> my_taxinc { get; set; }
        public Nullable<decimal> my_retain { get; set; }
        public Nullable<decimal> my_labtotal { get; set; }
        public Nullable<decimal> my_heatotal { get; set; }
        public string my_name { get; set; }
        public Nullable<decimal> my_other1 { get; set; }
        public Nullable<decimal> my_other2 { get; set; }
        public Nullable<decimal> my_other3 { get; set; }
        public decimal my_retire1 { get; set; }
        public decimal my_retire2 { get; set; }
        public decimal my_awardtax { get; set; }
        public decimal my_em13 { get; set; }
        public decimal my_nextpri { get; set; }
        public decimal my_effsal_org { get; set; }
        public decimal my_flag { get; set; }
        public decimal my_other4 { get; set; }
        public decimal my_other5 { get; set; }
        public int my_explain { get; set; }
        public Nullable<System.DateTime> my_paydate { get; set; }
        public string my_pdf { get; set; }
        public Nullable<System.DateTime> my_sendtime { get; set; }
        public string my_send { get; set; }
        public decimal my_PowerAward { get; set; }
        public decimal my_PowerShift { get; set; }
        public decimal my_baspay_org { get; set; }
        public Nullable<decimal> my_30 { get; set; }
        public decimal my_YieldRateAward { get; set; }
    }
}
