//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msaltax_p19
    {
        public string em_no { get; set; }
        public string em_id { get; set; }
        public string em_cname { get; set; }
        public string em_addr1 { get; set; }
        public decimal p1 { get; set; }
        public decimal p2 { get; set; }
        public decimal p3 { get; set; }
        public decimal p4 { get; set; }
        public decimal p5 { get; set; }
        public decimal p6 { get; set; }
        public decimal p7 { get; set; }
        public decimal p8 { get; set; }
        public decimal p9 { get; set; }
        public decimal p10 { get; set; }
        public decimal p11 { get; set; }
        public decimal p12 { get; set; }
        public decimal p13 { get; set; }
        public decimal p14 { get; set; }
        public decimal p15 { get; set; }
        public decimal p16 { get; set; }
        public decimal p17 { get; set; }
        public decimal p18 { get; set; }
        public decimal p19 { get; set; }
        public decimal p20 { get; set; }
        public decimal p21 { get; set; }
        public decimal p22 { get; set; }
        public decimal p23 { get; set; }
        public decimal p24 { get; set; }
        public decimal p25 { get; set; }
        public decimal p26 { get; set; }
    }
}
