//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msalaryF
    {
        public string mf_ym { get; set; }
        public string mf_fnno { get; set; }
        public string mf_name { get; set; }
        public string mf_dpno { get; set; }
        public decimal mf_baspay { get; set; }
        public decimal mf_ntaxot { get; set; }
        public decimal mf_taxot { get; set; }
        public decimal mf_otsal { get; set; }
        public decimal mf_shifsal { get; set; }
        public decimal mf_bf21 { get; set; }
        public decimal mf_bf22 { get; set; }
        public decimal mf_cut1 { get; set; }
        public decimal mf_cut2 { get; set; }
        public decimal mf_cut3 { get; set; }
        public decimal mf_cut4 { get; set; }
        public decimal mf_cut5 { get; set; }
        public decimal mf_leave { get; set; }
        public decimal mf_tax { get; set; }
        public decimal mf_labpri { get; set; }
        public decimal mf_heapri { get; set; }
        public decimal mf_artot { get; set; }
        public decimal mf_drtot { get; set; }
        public decimal mf_inftot { get; set; }
        public decimal mf_taxinc { get; set; }
        public decimal mf_labtotal { get; set; }
        public decimal mf_heatotal { get; set; }
        public decimal mf_cut6 { get; set; }
        public decimal mf_cut7 { get; set; }
        public decimal mf_effsal { get; set; }
        public int mf_explain { get; set; }
        public Nullable<System.DateTime> mf_paydate { get; set; }
    }
}
