//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msalary_edit
    {
        public System.DateTime upddate { get; set; }
        public decimal Kind { get; set; }
        public string my_ym { get; set; }
        public string my_emno { get; set; }
        public string my_name { get; set; }
        public decimal my_effsal { get; set; }
        public decimal my_trasal { get; set; }
        public decimal my_prepri { get; set; }
        public decimal my_otdepri { get; set; }
        public decimal my_effsal_Old { get; set; }
        public decimal my_trasal_Old { get; set; }
        public decimal my_prepri_Old { get; set; }
        public decimal my_otdepri_Old { get; set; }
        public string updid { get; set; }
    }
}
