//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msalaryEP
    {
        public int me_dsn { get; set; }
        public string me_dpno { get; set; }
        public string me_dpname { get; set; }
        public string me_emno { get; set; }
        public string me_cname { get; set; }
        public string me_kind { get; set; }
        public Nullable<System.DateTime> me_yymm { get; set; }
        public int me_heatotal { get; set; }
        public int me_heatotal4 { get; set; }
        public int me_amt { get; set; }
        public int me_amtT1 { get; set; }
        public int me_amtT2 { get; set; }
        public int me_explainT1 { get; set; }
        public double me_rate { get; set; }
        public int me_explain { get; set; }
        public int me_k { get; set; }
        public int me_explainE { get; set; }
        public string me_ym { get; set; }
        public Nullable<int> me_taxinc { get; set; }
        public string me_costym { get; set; }
    }
}
