//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msalward
    {
        public string md_yymm { get; set; }
        public string md_emno { get; set; }
        public string md_name { get; set; }
        public string md_id { get; set; }
        public decimal md_amt { get; set; }
        public decimal md_tax { get; set; }
        public string md_year { get; set; }
        public decimal md_kind { get; set; }
        public decimal md_saltype { get; set; }
        public Nullable<System.DateTime> md_paydate { get; set; }
        public int md_explain { get; set; }
        public string md_pdf { get; set; }
        public Nullable<System.DateTime> md_sendtime { get; set; }
        public string md_send { get; set; }
        public decimal md_PowerAward { get; set; }
    }
}
