//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msic24_01
    {
        public string rd_mtno { get; set; }
        public string rd_diff { get; set; }
        public decimal rd_width { get; set; }
        public decimal rd_long { get; set; }
        public System.DateTime rd_date { get; set; }
        public string rd_emno { get; set; }
        public Nullable<decimal> rd_qty { get; set; }
        public Nullable<decimal> rd_qty1 { get; set; }
        public Nullable<decimal> rd_qty2 { get; set; }
        public string mt_spec { get; set; }
        public string mt_unit { get; set; }
        public string mt_unit1 { get; set; }
        public string mt_curr { get; set; }
        public Nullable<decimal> mt_cost { get; set; }
        public string myk_name { get; set; }
        public Nullable<decimal> er_excrate { get; set; }
        public string The_BoxNo { get; set; }
        public string The_reason { get; set; }
        public string fs_loc1 { get; set; }
        public decimal rd_ver { get; set; }
        public string rd_veremno { get; set; }
        public string rd_vername { get; set; }
        public Nullable<System.DateTime> rd_verdate { get; set; }
        public decimal rd_print { get; set; }
        public Nullable<System.DateTime> con_lastdate { get; set; }
        public Nullable<System.DateTime> mt_date1 { get; set; }
    }
}
