//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nesb08_01
    {
        public Nullable<System.DateTime> PR_UPDATE { get; set; }
        public string PR_NETNO { get; set; }
        public string PR_LOC { get; set; }
        public Nullable<decimal> pr_spec { get; set; }
        public Nullable<decimal> pr_ntclass { get; set; }
        public string pr_01 { get; set; }
        public Nullable<decimal> PR_QTY { get; set; }
        public string PR_02 { get; set; }
        public string PR_SETNO { get; set; }
        public Nullable<System.DateTime> PR_NDATE { get; set; }
        public Nullable<System.DateTime> PR_MDATE { get; set; }
        public string PR_DPNO { get; set; }
        public string pr_dpno1 { get; set; }
        public Nullable<decimal> pr_use { get; set; }
        public string loginID { get; set; }
        public decimal DoFilter { get; set; }
        public string sb_num { get; set; }
    }
}
