//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetAward
    {
        public string YM { get; set; }
        public System.DateTime ne_date { get; set; }
        public string nt_no { get; set; }
        public string nt_tname { get; set; }
        public int mCnt { get; set; }
        public decimal Cnt { get; set; }
        public decimal NetEff { get; set; }
        public decimal Award { get; set; }
        public decimal AwardShow { get; set; }
        public decimal WorkHour_Real { get; set; }
        public decimal WorkHour { get; set; }
        public decimal er_hour_Real { get; set; }
        public decimal er_hour_std { get; set; }
        public decimal StdWorkHour { get; set; }
    }
}
