//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netcreate
    {
        public System.DateTime ne_date { get; set; }
        public string ne_snetno { get; set; }
        public string ne_setno { get; set; }
        public Nullable<decimal> ne_qty { get; set; }
        public Nullable<decimal> ne_spec { get; set; }
        public string ne_emno { get; set; }
        public string ne_cpro { get; set; }
        public string ne_dpno { get; set; }
        public Nullable<decimal> ne_ntclass { get; set; }
        public Nullable<decimal> ne_exemno { get; set; }
        public decimal ne_count { get; set; }
        public decimal ne_seq { get; set; }
        public Nullable<System.DateTime> ne_postdate { get; set; }
        public decimal ne_Optics { get; set; }
        public string ne_num { get; set; }
        public string ne_reason { get; set; }
        public string ne_bemno { get; set; }
        public decimal ne_Exquisite { get; set; }
    }
}
