//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetFix
    {
        public decimal nf_seqno { get; set; }
        public Nullable<System.DateTime> nf_cdate { get; set; }
        public string nf_cemno { get; set; }
        public string nf_dpno { get; set; }
        public string nf_netno { get; set; }
        public decimal nf_new { get; set; }
        public string nf_setno { get; set; }
        public Nullable<System.DateTime> nf_mdate { get; set; }
        public string nf_memno { get; set; }
        public string nf_qemno { get; set; }
        public string nf_pemno { get; set; }
        public string nf_condition { get; set; }
        public decimal nf_fix { get; set; }
        public Nullable<decimal> nf_post { get; set; }
        public decimal nf_confirm { get; set; }
        public string nf_femno { get; set; }
        public Nullable<System.DateTime> nf_fdate { get; set; }
    }
}
