//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetHole
    {
        public decimal ne_seqno { get; set; }
        public string ne_emno { get; set; }
        public System.DateTime ne_enddate { get; set; }
        public string ne_dpno { get; set; }
        public string ne_netno { get; set; }
        public Nullable<decimal> ne_spec { get; set; }
        public int ne_qty { get; set; }
        public decimal ne_post { get; set; }
        public Nullable<System.DateTime> ne_cdate { get; set; }
        public string ne_memno { get; set; }
        public string ne_memo { get; set; }
    }
}
