//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netmodi
    {
        public string nm_snetno { get; set; }
        public System.DateTime nm_update { get; set; }
        public decimal nm_kind { get; set; }
        public Nullable<decimal> nm_qty { get; set; }
        public Nullable<decimal> nm_ntclass { get; set; }
        public string nm_reason { get; set; }
        public string nm_cemno { get; set; }
        public string nm_setno { get; set; }
        public string nm_dno { get; set; }
        public string nm_dpno { get; set; }
        public string nm_demno { get; set; }
        public Nullable<decimal> nm_exemno { get; set; }
        public string nm_cpro { get; set; }
        public string nm_suno { get; set; }
        public Nullable<decimal> nm_post { get; set; }
        public decimal nm_seq { get; set; }
        public Nullable<System.DateTime> nm_newdate { get; set; }
        public Nullable<System.DateTime> nm_cdate { get; set; }
        public decimal nm_email { get; set; }
        public decimal nm_check { get; set; }
        public Nullable<int> NM_TENSION { get; set; }
    }
}
