//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsamp
    {
        public string np_setno { get; set; }
        public string np_puno { get; set; }
        public Nullable<decimal> np_post { get; set; }
        public string np_cemno { get; set; }
        public Nullable<System.DateTime> np_cdate { get; set; }
        public Nullable<System.DateTime> np_pdate { get; set; }
    }
}
