//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewDevelop
    {
        public string NP_NO { get; set; }
        public string NP_EMNO { get; set; }
        public string NP_NAME { get; set; }
        public string NP_DPNO { get; set; }
        public string NP_DPNAME { get; set; }
        public string NP_CUNO { get; set; }
        public string NP_CUNAME { get; set; }
        public Nullable<System.DateTime> NP_DATE1 { get; set; }
        public Nullable<System.DateTime> NP_DATE2 { get; set; }
        public string NP_SUBJECT { get; set; }
        public string NP_CONTENT1 { get; set; }
        public string NP_CONTENT2 { get; set; }
        public Nullable<System.DateTime> NP_UPDATE { get; set; }
        public Nullable<System.DateTime> NP_ACDATE { get; set; }
        public string NP_ACEMNO { get; set; }
        public string NP_ACNAME { get; set; }
        public Nullable<System.DateTime> NP_PCDATE { get; set; }
        public Nullable<decimal> NP_PCHOUR { get; set; }
        public Nullable<System.DateTime> NP_RCDATE { get; set; }
        public Nullable<decimal> NP_RCHOUR { get; set; }
        public Nullable<decimal> NP_POST { get; set; }
        public Nullable<decimal> NP_YN { get; set; }
        public Nullable<decimal> NP_YN1 { get; set; }
        public Nullable<decimal> NP_CLOSE { get; set; }
        public string NP_ACBACKMEMO { get; set; }
        public decimal NP_KIND { get; set; }
        public string NP_RCMEMO { get; set; }
        public string NP_FILENAME { get; set; }
        public string NP_ACMEMO { get; set; }
    }
}
