//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewDevelop1
    {
        public string NP_NO { get; set; }
        public string NP_NO1 { get; set; }
        public string NP_EMNO { get; set; }
        public string NP_NAME { get; set; }
        public string NP_DPNO { get; set; }
        public string NP_DPNAME { get; set; }
        public Nullable<System.DateTime> NP_DATE1 { get; set; }
        public Nullable<System.DateTime> NP_DATE2 { get; set; }
        public Nullable<System.DateTime> NP_DATE3 { get; set; }
        public string NP_SUBJECT { get; set; }
        public Nullable<decimal> NP_KIND1 { get; set; }
        public Nullable<decimal> NP_KIND2 { get; set; }
        public Nullable<decimal> NP_QTY { get; set; }
        public Nullable<decimal> NP_KIND3 { get; set; }
        public string NP_CUNO { get; set; }
        public string NP_CUNAME { get; set; }
        public string NP_CONTENT1 { get; set; }
        public string NP_CONTENT2 { get; set; }
        public string NP_FILENAME { get; set; }
        public string NP_EMNO1 { get; set; }
        public string NP_NAME1 { get; set; }
        public Nullable<System.DateTime> NP_PDATE1 { get; set; }
        public Nullable<System.DateTime> NP_PDATE2 { get; set; }
        public Nullable<System.DateTime> NP_PDATE3 { get; set; }
        public Nullable<System.DateTime> NP_PDATE4 { get; set; }
        public Nullable<System.DateTime> NP_CDATE1 { get; set; }
        public Nullable<System.DateTime> NP_CDATE2 { get; set; }
        public Nullable<System.DateTime> NP_CDATE3 { get; set; }
        public Nullable<System.DateTime> NP_CDATE4 { get; set; }
        public string NP_FILE1 { get; set; }
        public string NP_FILE2 { get; set; }
        public string NP_FILE3 { get; set; }
        public string NP_FILE4 { get; set; }
        public string NP_FILE5 { get; set; }
        public decimal NP_POST { get; set; }
        public decimal NP_CLOSE { get; set; }
        public string NP_CONTENT3 { get; set; }
        public string NP_REASON { get; set; }
        public Nullable<int> NP_VERIFY { get; set; }
        public string NP_VREASON { get; set; }
        public string NP_VEMNO { get; set; }
        public string NP_VNAME { get; set; }
        public Nullable<System.DateTime> NP_DATE4 { get; set; }
        public Nullable<int> NP_Q1 { get; set; }
        public Nullable<int> NP_Q2 { get; set; }
        public Nullable<int> NP_Q3 { get; set; }
        public Nullable<int> NP_Q4 { get; set; }
        public Nullable<int> NP_Q5 { get; set; }
        public Nullable<int> NP_Q6 { get; set; }
        public Nullable<int> NP_Q7 { get; set; }
        public Nullable<int> NP_Q8 { get; set; }
        public Nullable<int> NP_Q9 { get; set; }
        public Nullable<int> NP_SOURCE { get; set; }
        public string NP_YN { get; set; }
        public string NP_PTEAM { get; set; }
        public string NP_YN1 { get; set; }
        public string NP_PNAME { get; set; }
        public string NP_PREASON { get; set; }
        public Nullable<int> NP_MONEY1 { get; set; }
        public Nullable<int> NP_MONEY2 { get; set; }
        public string NP_VEMNO1 { get; set; }
        public string NP_VNAME1 { get; set; }
        public Nullable<System.DateTime> NP_DATE5 { get; set; }
        public Nullable<System.DateTime> NP_NGDATES { get; set; }
        public Nullable<System.DateTime> NP_NGDATEE { get; set; }
        public string NP_NGREASON { get; set; }
        public string NP_FEMNO { get; set; }
        public string NP_FNAME { get; set; }
        public Nullable<System.DateTime> NP_FDATE { get; set; }
        public string NP_MONEY1N { get; set; }
        public string NP_MONEY2N { get; set; }
        public Nullable<System.DateTime> NP_GGDATE { get; set; }
        public string NP_GGREASON { get; set; }
        public decimal NP_KIND21 { get; set; }
        public decimal NP_KIND22 { get; set; }
        public decimal NP_KIND23 { get; set; }
        public decimal NP_KIND24 { get; set; }
        public decimal NP_QTY21 { get; set; }
        public decimal NP_QTY22 { get; set; }
        public decimal NP_QTY23 { get; set; }
        public decimal NP_QTY24 { get; set; }
        public Nullable<System.DateTime> NP_NDATE1 { get; set; }
        public Nullable<System.DateTime> NP_NDATE2 { get; set; }
        public Nullable<System.DateTime> NP_NDATE3 { get; set; }
        public Nullable<System.DateTime> NP_NDATE4 { get; set; }
        public string NP_FILE6 { get; set; }
        public string NP_REASON3 { get; set; }
    }
}
