//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewSysFunc
    {
        public string NS_NO { get; set; }
        public string NS_EMNO { get; set; }
        public string NS_NAME { get; set; }
        public string NS_DPNO { get; set; }
        public string NS_DPNAME { get; set; }
        public Nullable<System.DateTime> NS_DATE1 { get; set; }
        public string NS_SUBJECT { get; set; }
        public string NS_CONTENT1 { get; set; }
        public Nullable<System.DateTime> NS_UPDATE { get; set; }
        public Nullable<System.DateTime> NS_RCDATE { get; set; }
        public Nullable<decimal> NS_POST { get; set; }
        public Nullable<decimal> NS_CLOSE { get; set; }
        public string NS_BACKMEMO { get; set; }
        public string NS_ACEMNO { get; set; }
        public string NS_ACNAME { get; set; }
        public decimal ns_kind1 { get; set; }
        public decimal ns_kind2 { get; set; }
        public decimal ns_kind3 { get; set; }
        public decimal ns_kind4 { get; set; }
        public decimal ns_kind5 { get; set; }
        public decimal ns_kind6 { get; set; }
        public decimal ns_kind7 { get; set; }
        public decimal ns_kind8 { get; set; }
        public string ns_loginID1 { get; set; }
        public string ns_password1 { get; set; }
        public string ns_loginID2 { get; set; }
        public string ns_password2 { get; set; }
        public decimal ns_item31 { get; set; }
        public decimal ns_item32 { get; set; }
        public string ns_emno31 { get; set; }
        public string ns_emcname31 { get; set; }
        public string ns_cename31 { get; set; }
        public string ns_emno32 { get; set; }
        public string ns_emcname32 { get; set; }
        public string ns_emno33 { get; set; }
        public string ns_emcname33 { get; set; }
        public string ns_cuno4 { get; set; }
        public string ns_cuname4 { get; set; }
        public string ns_reason4 { get; set; }
        public string ns_loginID4 { get; set; }
        public string ns_password4 { get; set; }
        public string ns_reason5 { get; set; }
        public Nullable<System.DateTime> ns_date51 { get; set; }
        public Nullable<System.DateTime> ns_date52 { get; set; }
        public string ns_reason6 { get; set; }
        public decimal ns_item61 { get; set; }
        public decimal ns_item62 { get; set; }
        public decimal ns_item63 { get; set; }
        public decimal ns_item64 { get; set; }
        public decimal ns_item65 { get; set; }
        public decimal ns_item66 { get; set; }
        public string ns_other6 { get; set; }
        public string ns_account6 { get; set; }
        public string ns_reason7 { get; set; }
        public decimal ns_item71 { get; set; }
        public decimal ns_item72 { get; set; }
        public decimal ns_item73 { get; set; }
        public string ns_other7 { get; set; }
        public string ns_eqname7 { get; set; }
        public string ns_reason8 { get; set; }
        public decimal ns_item81 { get; set; }
        public decimal ns_item82 { get; set; }
        public string ns_other8 { get; set; }
        public string ns_eqname8 { get; set; }
        public string ns_GID { get; set; }
        public string ns_cemno { get; set; }
        public string ns_cname { get; set; }
        public string ns_MacAddr81 { get; set; }
        public string ns_MacAddr82 { get; set; }
        public Nullable<decimal> ns_kind9 { get; set; }
        public string ns_password11 { get; set; }
        public Nullable<int> NS_VERIFY { get; set; }
        public string NS_VEMNO { get; set; }
        public string NS_VNAME { get; set; }
        public Nullable<System.DateTime> NS_VDATE { get; set; }
        public Nullable<int> NS_VERIFY1 { get; set; }
        public string NS_VEMNO1 { get; set; }
        public string NS_VNAME1 { get; set; }
        public Nullable<System.DateTime> NS_VDATE1 { get; set; }
        public Nullable<int> NS_VERIFY2 { get; set; }
        public string NS_VEMNO2 { get; set; }
        public string NS_VNAME2 { get; set; }
        public Nullable<System.DateTime> NS_VDATE2 { get; set; }
        public string NS_REASON1 { get; set; }
    }
}
