//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ntetime
    {
        public string nt_netno { get; set; }
        public Nullable<System.DateTime> nt_date { get; set; }
        public string nt_emno { get; set; }
        public Nullable<decimal> nt_qty { get; set; }
        public Nullable<decimal> nt_size { get; set; }
        public string nt_brand { get; set; }
        public Nullable<System.DateTime> nt_cdate { get; set; }
        public Nullable<decimal> nt_k1 { get; set; }
        public Nullable<decimal> nt_k2 { get; set; }
        public Nullable<decimal> nt_k3 { get; set; }
        public Nullable<decimal> nt_k4 { get; set; }
        public Nullable<decimal> nt_k5 { get; set; }
        public Nullable<decimal> nt_k7 { get; set; }
        public Nullable<decimal> nt_k10 { get; set; }
    }
}
