//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OilNet_chg
    {
        public string The_Action { get; set; }
        public Nullable<System.DateTime> The_Date { get; set; }
        public string on_emno { get; set; }
        public string on_chno { get; set; }
        public decimal on_serial { get; set; }
        public decimal on_qty { get; set; }
        public decimal on_serial_old { get; set; }
        public decimal on_qty_old { get; set; }
    }
}
