//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oilprof
    {
        public string of_clno { get; set; }
        public string of_prop { get; set; }
        public string of_item1 { get; set; }
        public string of_item2 { get; set; }
        public string of_item3 { get; set; }
        public string of_item4 { get; set; }
        public string of_item5 { get; set; }
        public string of_item6 { get; set; }
        public string of_item7 { get; set; }
        public string of_item8 { get; set; }
        public string of_item9 { get; set; }
        public string of_item10 { get; set; }
        public decimal of_rate1 { get; set; }
        public decimal of_rate2 { get; set; }
        public decimal of_rate3 { get; set; }
        public decimal of_rate4 { get; set; }
        public decimal of_rate5 { get; set; }
        public decimal of_rate6 { get; set; }
        public decimal of_rate7 { get; set; }
        public decimal of_rate8 { get; set; }
        public decimal of_rate9 { get; set; }
        public decimal of_rate10 { get; set; }
        public decimal of_weight1 { get; set; }
        public decimal of_weight2 { get; set; }
        public decimal of_weight3 { get; set; }
        public decimal of_weight4 { get; set; }
        public decimal of_weight5 { get; set; }
        public decimal of_weight6 { get; set; }
        public decimal of_weight7 { get; set; }
        public decimal of_weight8 { get; set; }
        public decimal of_weight9 { get; set; }
        public decimal of_weight10 { get; set; }
        public Nullable<System.DateTime> of_cdate { get; set; }
        public Nullable<System.DateTime> of_udate { get; set; }
        public string of_serial { get; set; }
        public string of_cemno { get; set; }
        public string of_uemno { get; set; }
    }
}
