//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oilpr18_01
    {
        public decimal seqno { get; set; }
        public string The_no { get; set; }
        public string The_name { get; set; }
        public string Ma_Kind { get; set; }
        public decimal Qty1 { get; set; }
        public decimal Qty2 { get; set; }
        public decimal Qty3 { get; set; }
        public decimal Qty4 { get; set; }
        public decimal Qty5 { get; set; }
        public decimal Qty6 { get; set; }
        public decimal Qty7 { get; set; }
        public decimal PrintTimes { get; set; }
        public decimal PlusTimes { get; set; }
        public decimal CarQty { get; set; }
        public decimal AvgQty1 { get; set; }
        public decimal AvgQty2 { get; set; }
        public decimal AvgQty3 { get; set; }
        public decimal AvgQty4 { get; set; }
        public decimal AvgQty5 { get; set; }
        public decimal AvgQty6 { get; set; }
        public decimal AvgQty7 { get; set; }
        public decimal AvgQty1C { get; set; }
        public decimal AvgQty2C { get; set; }
        public decimal AvgQty3C { get; set; }
        public decimal AvgQty4C { get; set; }
        public decimal AvgQty5C { get; set; }
        public decimal AvgQty6C { get; set; }
        public decimal AvgQty7C { get; set; }
        public decimal GoalA1 { get; set; }
        public decimal GoalA2 { get; set; }
        public decimal GoalB { get; set; }
        public decimal GoalC { get; set; }
        public decimal GoalD { get; set; }
        public decimal PlusTimes_SD { get; set; }
        public decimal Qty8 { get; set; }
        public decimal AvgQty8 { get; set; }
        public decimal AvgQty8C { get; set; }
    }
}
