//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OilProof_Bak
    {
        public string op_pemno { get; set; }
        public string op_mkno { get; set; }
        public string op_setno { get; set; }
        public Nullable<System.DateTime> op_sdate { get; set; }
        public Nullable<System.DateTime> op_edate { get; set; }
        public Nullable<decimal> op_time { get; set; }
        public string op_num { get; set; }
        public decimal op_kind { get; set; }
        public string op_chno { get; set; }
        public string op_cemno { get; set; }
        public decimal op_count { get; set; }
    }
}
