//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnLineCheck
    {
        public decimal ok_seq { get; set; }
        public string ok_emno { get; set; }
        public string ok_dpno { get; set; }
        public Nullable<System.DateTime> ok_Tdate { get; set; }
        public Nullable<System.DateTime> ok_mocdate { get; set; }
        public string ok_mkno { get; set; }
        public string ok_setno { get; set; }
        public decimal ok_AccepQty { get; set; }
        public decimal ok_GoodQty { get; set; }
        public decimal ok_result { get; set; }
    }
}
