//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class or_oren41_01
    {
        public string ed_orno { get; set; }
        public string ed_inno { get; set; }
        public Nullable<System.DateTime> ed_ordate { get; set; }
        public string ed_fano { get; set; }
        public string ed_item { get; set; }
        public Nullable<decimal> ed_yn { get; set; }
        public string ed_cupdno { get; set; }
        public string ed_pdno { get; set; }
        public string ed_cusetno { get; set; }
        public string ed_setno { get; set; }
        public string ed_level { get; set; }
        public Nullable<System.DateTime> ed_date { get; set; }
        public Nullable<decimal> ed_amt { get; set; }
        public string ed_mykno { get; set; }
        public Nullable<decimal> ed_price { get; set; }
        public string ed_desc { get; set; }
        public string ed_emno { get; set; }
        public string ed_cuno { get; set; }
        public string em_cname { get; set; }
        public string ed_dpno { get; set; }
        public decimal ed_check { get; set; }
        public decimal ed_reply { get; set; }
        public string ed_mkid { get; set; }
        public decimal ed_pause { get; set; }
        public decimal sh_amount { get; set; }
    }
}
