//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orload
    {
        public System.DateTime od_date { get; set; }
        public string od_psta { get; set; }
        public string od_mkno { get; set; }
        public string od_proatt { get; set; }
        public Nullable<decimal> od_carqty { get; set; }
        public Nullable<decimal> od_fcqty { get; set; }
        public decimal od_pcqty { get; set; }
        public decimal od_fcqty1 { get; set; }
    }
}
