//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orpl32_01
    {
        public decimal The_seq { get; set; }
        public Nullable<System.DateTime> The_date { get; set; }
        public string The_cupdno { get; set; }
        public string The_pdno { get; set; }
        public Nullable<System.DateTime> The_date1 { get; set; }
        public Nullable<System.DateTime> The_date2 { get; set; }
        public Nullable<System.DateTime> The_date3 { get; set; }
        public Nullable<System.DateTime> The_date4 { get; set; }
        public Nullable<decimal> Qty1 { get; set; }
        public Nullable<decimal> Qty2 { get; set; }
        public Nullable<decimal> Qty3 { get; set; }
        public Nullable<decimal> Qty4 { get; set; }
        public Nullable<decimal> StockQty { get; set; }
    }
}
