//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orpl34_01
    {
        public string The_cupdno { get; set; }
        public string The_orno { get; set; }
        public string The_desc { get; set; }
        public string The_pdno { get; set; }
        public decimal NeedQty { get; set; }
        public decimal sh_amt { get; set; }
        public Nullable<System.DateTime> The_date { get; set; }
        public decimal The_Qty { get; set; }
        public decimal The_MCnt { get; set; }
        public decimal The_YN { get; set; }
        public string The_memo { get; set; }
        public string The_emno { get; set; }
        public decimal The_seq { get; set; }
        public Nullable<System.DateTime> The_cdate { get; set; }
        public Nullable<System.DateTime> The_NPdate { get; set; }
    }
}
