//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orpl35_01
    {
        public string The_cupdno { get; set; }
        public decimal Qty1 { get; set; }
        public decimal Qty2 { get; set; }
        public decimal QtyT { get; set; }
        public string The_pdno { get; set; }
        public decimal sh_amt { get; set; }
        public string The_setno { get; set; }
        public string The_mkno { get; set; }
        public Nullable<System.DateTime> The_date { get; set; }
        public string The_brgemno { get; set; }
        public string The_memo { get; set; }
        public string The_emno { get; set; }
        public decimal The_seq { get; set; }
    }
}
