//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orpl29_03
    {
        public decimal yy { get; set; }
        public decimal ww { get; set; }
        public string cupdno { get; set; }
        public Nullable<decimal> qty { get; set; }
        public System.DateTime The_Date { get; set; }
    }
}
