//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orpl21_01
    {
        public string id_orno { get; set; }
        public string id_cupdno { get; set; }
        public string id_pdno { get; set; }
        public string b1_desc { get; set; }
        public Nullable<decimal> id_amt1 { get; set; }
        public string id_imno { get; set; }
        public Nullable<System.DateTime> id_tdate1 { get; set; }
        public string id_mkid { get; set; }
        public string im_cuno { get; set; }
        public string sh_loc { get; set; }
        public string im_memo2 { get; set; }
        public string b1_color { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> The_ModCnt { get; set; }
        public string id_curr { get; set; }
        public int The_No { get; set; }
        public int The_qty { get; set; }
    }
}
