//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orpl22_01
    {
        public Nullable<System.DateTime> or_date { get; set; }
        public string or_cupdno { get; set; }
        public string or_level { get; set; }
        public string or_pdno { get; set; }
        public string or_desc { get; set; }
        public Nullable<decimal> or_qty { get; set; }
        public Nullable<System.DateTime> or_cudate { get; set; }
        public string or_no { get; set; }
        public string or_item { get; set; }
        public decimal or_seqno { get; set; }
    }
}
