//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class osbasic
    {
        public string ob_tano { get; set; }
        public string ob_suno { get; set; }
        public string ob_unit { get; set; }
        public Nullable<decimal> ob_basamt { get; set; }
        public string ob_emno1 { get; set; }
        public string ob_emno2 { get; set; }
        public string ob_payno { get; set; }
        public string ob_emno3 { get; set; }
        public decimal ob_kind { get; set; }
    }
}
