//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oschkdtl
    {
        public string oc_omno { get; set; }
        public Nullable<System.DateTime> oc_chkdate { get; set; }
        public Nullable<decimal> oc_qty { get; set; }
        public Nullable<decimal> oc_chkqty { get; set; }
        public Nullable<decimal> oc_close { get; set; }
        public Nullable<decimal> oc_totamt { get; set; }
        public Nullable<decimal> oc_oilfee { get; set; }
        public string oc_inno { get; set; }
        public Nullable<decimal> oc_size { get; set; }
        public string oc_emno { get; set; }
        public string oc_mkno { get; set; }
        public decimal oc_price { get; set; }
        public decimal oc_serial { get; set; }
        public string oc_chkno { get; set; }
        public int oc_flag { get; set; }
        public int oc_ver { get; set; }
        public Nullable<System.DateTime> oc_vdate { get; set; }
        public string oc_vemno { get; set; }
        public string oc_vname { get; set; }
        public string oc_curr { get; set; }
    }
}
