//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class osdetail
    {
        public string od_omno { get; set; }
        public string od_mkno { get; set; }
        public string od_setno { get; set; }
        public string od_note { get; set; }
        public Nullable<decimal> od_qty { get; set; }
        public Nullable<System.DateTime> od_predate { get; set; }
        public decimal od_price { get; set; }
        public decimal od_calamt { get; set; }
        public Nullable<decimal> od_totamt { get; set; }
        public decimal od_serial { get; set; }
        public int od_ver { get; set; }
        public Nullable<System.DateTime> od_vdate { get; set; }
        public string od_vemno { get; set; }
        public string od_vname { get; set; }
        public decimal od_idseqno { get; set; }
        public string od_curr { get; set; }
    }
}
