//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class osmain
    {
        public string om_no { get; set; }
        public string om_suno { get; set; }
        public string om_dpno { get; set; }
        public string om_payno { get; set; }
        public string om_tano { get; set; }
        public Nullable<decimal> om_check { get; set; }
        public string om_memo { get; set; }
        public decimal om_out { get; set; }
        public Nullable<System.DateTime> om_cdate { get; set; }
        public decimal om_kind { get; set; }
        public string om_emno { get; set; }
        public decimal om_print { get; set; }
    }
}
