//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class other
    {
        public string ot_suno { get; set; }
        public Nullable<System.DateTime> ot_date { get; set; }
        public string ot_itemno { get; set; }
        public string ot_payno { get; set; }
        public Nullable<decimal> ot_amt { get; set; }
        public Nullable<decimal> ot_taxamt { get; set; }
        public string ot_note { get; set; }
        public Nullable<decimal> ot_10 { get; set; }
        public Nullable<decimal> ot_diff { get; set; }
        public decimal ot_seqno { get; set; }
        public Nullable<System.DateTime> ot_date1 { get; set; }
        public string ot_pemno1 { get; set; }
        public string ot_pcname1 { get; set; }
        public Nullable<System.DateTime> ot_pdate1 { get; set; }
        public string ot_pemno2 { get; set; }
        public string ot_pcname2 { get; set; }
        public Nullable<System.DateTime> ot_pdate2 { get; set; }
        public string ot_pemno3 { get; set; }
        public string ot_pcname3 { get; set; }
        public Nullable<System.DateTime> ot_pdate3 { get; set; }
        public Nullable<int> ot_flag { get; set; }
    }
}
