//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class outpayb
    {
        public Nullable<System.DateTime> ob_date { get; set; }
        public Nullable<decimal> ob_qty { get; set; }
        public string ob_mtno { get; set; }
        public string ob_emno { get; set; }
        public string ob_otno { get; set; }
        public Nullable<decimal> ob_uprice { get; set; }
        public Nullable<decimal> ob_total { get; set; }
        public Nullable<decimal> ob_amount { get; set; }
        public string ob_mkno { get; set; }
        public Nullable<System.DateTime> ob_date1 { get; set; }
        public string ob_ckno { get; set; }
        public string ob_suno { get; set; }
        public string ob_unit { get; set; }
        public string ob_kind { get; set; }
        public string ob_dpno { get; set; }
        public Nullable<decimal> ob_serial { get; set; }
        public decimal ob_seqno { get; set; }
    }
}
