//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartTime
    {
        public string pt_no { get; set; }
        public string pt_cname { get; set; }
        public string pt_id { get; set; }
        public Nullable<decimal> pt_sex { get; set; }
        public Nullable<System.DateTime> pt_birth { get; set; }
        public string pt_dpno { get; set; }
        public string pt_tel1 { get; set; }
        public string pt_tel2 { get; set; }
        public string pt_addr1 { get; set; }
        public string pt_addr2 { get; set; }
        public Nullable<decimal> pt_skind { get; set; }
        public Nullable<decimal> pt_daypay { get; set; }
        public Nullable<decimal> pt_nightpay { get; set; }
        public Nullable<decimal> pt_monthpay { get; set; }
        public string pt_work { get; set; }
        public Nullable<decimal> pt_11 { get; set; }
        public Nullable<decimal> pt_14 { get; set; }
        public Nullable<System.DateTime> pt_20 { get; set; }
        public Nullable<System.DateTime> pt_21 { get; set; }
        public Nullable<System.DateTime> pt_22 { get; set; }
        public Nullable<System.DateTime> pt_23 { get; set; }
        public Nullable<System.DateTime> pt_24 { get; set; }
        public Nullable<System.DateTime> pt_25 { get; set; }
        public string pt_26 { get; set; }
        public string pt_27 { get; set; }
        public Nullable<decimal> pt_30 { get; set; }
        public string pt_31 { get; set; }
        public Nullable<decimal> pt_41 { get; set; }
        public string pt_61 { get; set; }
        public string pt_63 { get; set; }
        public Nullable<decimal> pt_70 { get; set; }
        public Nullable<System.DateTime> pt_90 { get; set; }
        public Nullable<decimal> pt_post { get; set; }
        public Nullable<decimal> pt_working { get; set; }
        public decimal pt_kind { get; set; }
        public string pt_contract { get; set; }
        public string pt_94 { get; set; }
        public decimal pt_95 { get; set; }
        public decimal pt_96 { get; set; }
        public string pt_100 { get; set; }
        public int pt_special { get; set; }
        public string pt_62 { get; set; }
        public string pt_69 { get; set; }
        public decimal pt_identity1 { get; set; }
        public decimal pt_identity2 { get; set; }
        public decimal pt_identity3 { get; set; }
        public string pt_bank { get; set; }
        public decimal pt_13 { get; set; }
        public Nullable<int> pt_95yn { get; set; }
        public Nullable<int> pt_96yn { get; set; }
        public decimal pt_12 { get; set; }
    }
}
