//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paydetailh
    {
        public string pa_ym { get; set; }
        public string pa_no { get; set; }
        public string pa_suno { get; set; }
        public Nullable<decimal> pa_disc { get; set; }
        public string pa_csup { get; set; }
        public Nullable<System.DateTime> pa_date { get; set; }
        public string pa_emno { get; set; }
        public Nullable<decimal> pa_post { get; set; }
        public Nullable<int> pa_flag { get; set; }
        public decimal pa_printyn { get; set; }
        public string pa_SNO1 { get; set; }
        public string pa_SNO2 { get; set; }
    }
}
