//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payinvoice
    {
        public int pay_dsn { get; set; }
        public int pay_dsn2 { get; set; }
        public Nullable<int> pay_kind { get; set; }
        public Nullable<int> pay_kind1 { get; set; }
        public Nullable<int> pay_price { get; set; }
        public Nullable<int> pay_percent { get; set; }
        public Nullable<int> pay_tax { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public string pay_inno { get; set; }
        public string pay_stno { get; set; }
        public string su_ivid { get; set; }
        public string pay_date1 { get; set; }
        public string pay_date2 { get; set; }
        public Nullable<int> pay_ftno { get; set; }
        public string pay_SNO1 { get; set; }
        public string pay_SNO2 { get; set; }
        public string pay_memo { get; set; }
    }
}
