//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdtrelfee
    {
        public string prf_ym { get; set; }
        public string prf_prno { get; set; }
        public Nullable<decimal> prf_amt1 { get; set; }
        public Nullable<decimal> prf_amt2 { get; set; }
        public Nullable<decimal> prf_amt3 { get; set; }
        public Nullable<decimal> prf_amt4 { get; set; }
        public Nullable<decimal> prf_amt5 { get; set; }
    }
}
