//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plchk
    {
        public string pc_suno { get; set; }
        public string pc_mtno { get; set; }
        public Nullable<System.DateTime> pc_date { get; set; }
        public string pc_ivno { get; set; }
        public Nullable<decimal> pc_width { get; set; }
        public Nullable<decimal> pc_long { get; set; }
        public Nullable<decimal> pc_qty1 { get; set; }
        public Nullable<decimal> pc_qty2 { get; set; }
        public string pc_seqno { get; set; }
        public Nullable<System.DateTime> pc_date1 { get; set; }
        public Nullable<decimal> pc_kind { get; set; }
        public string pc_no1 { get; set; }
        public string pc_no2 { get; set; }
        public Nullable<decimal> pc_unipric { get; set; }
        public Nullable<decimal> pc_fatype { get; set; }
        public string pc_curr { get; set; }
        public string pc_isno { get; set; }
    }
}
