//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class predodr
    {
        public string po_no { get; set; }
        public Nullable<System.DateTime> po_date { get; set; }
        public string po_diff { get; set; }
        public string po_version { get; set; }
        public string po_cupdno { get; set; }
        public string po_desc { get; set; }
        public Nullable<decimal> po_qty { get; set; }
        public Nullable<System.DateTime> po_date1 { get; set; }
        public Nullable<decimal> po_amt { get; set; }
        public string po_item { get; set; }
        public string po_status { get; set; }
        public Nullable<System.DateTime> po_date2 { get; set; }
        public string po_cuno { get; set; }
    }
}
