//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prepayF
    {
        public string pf_ym { get; set; }
        public string pf_fnno { get; set; }
        public decimal pf_cut1 { get; set; }
        public decimal pf_cut2 { get; set; }
        public decimal pf_cut3 { get; set; }
        public decimal pf_cut4 { get; set; }
        public decimal pf_cut5 { get; set; }
        public decimal pf_cut6 { get; set; }
        public decimal pf_cut7 { get; set; }
    }
}
