//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrizeRate
    {
        public string pr_yymm { get; set; }
        public string pr_emno { get; set; }
        public string pr_dpno { get; set; }
        public string pr_group { get; set; }
        public decimal pr_rate { get; set; }
        public decimal pr_grate { get; set; }
        public decimal pr_ceno3 { get; set; }
        public int pr_award { get; set; }
        public int pr_dir { get; set; }
    }
}
