//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrizeDivide
    {
        public string pd_ym { get; set; }
        public string pd_dpno { get; set; }
        public int pd_profit { get; set; }
        public int pd_share { get; set; }
        public decimal pd_rate { get; set; }
        public int pd_share0 { get; set; }
        public decimal pd_rate0 { get; set; }
        public int pd_share1 { get; set; }
        public decimal pd_rate1 { get; set; }
        public int pd_profitS { get; set; }
        public int pd_explain { get; set; }
    }
}
