//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string pr_no { get; set; }
        public string pr_ename { get; set; }
        public string pr_cname { get; set; }
        public Nullable<decimal> pr_fee { get; set; }
        public Nullable<decimal> pr_lock1 { get; set; }
        public string pr_mtno1 { get; set; }
        public Nullable<decimal> pr_lock2 { get; set; }
        public string pr_mtno2 { get; set; }
        public Nullable<decimal> pr_lock3 { get; set; }
        public string pr_mtno3 { get; set; }
        public Nullable<decimal> pr_lock4 { get; set; }
        public string pr_mtno4 { get; set; }
        public Nullable<decimal> pr_lock5 { get; set; }
        public string pr_mtno5 { get; set; }
        public string pr_type { get; set; }
        public Nullable<decimal> pr_percen { get; set; }
        public decimal pr_effdur { get; set; }
        public decimal pr_ewday { get; set; }
        public Nullable<decimal> pr_serial { get; set; }
        public string pr_chno1 { get; set; }
        public string pr_chno2 { get; set; }
        public string pr_chno3 { get; set; }
        public string pr_chno4 { get; set; }
        public string pr_chno5 { get; set; }
        public string pr_chno6 { get; set; }
        public decimal pr_hide { get; set; }
        public string pr_chno4N { get; set; }
        public string pr_chno3N { get; set; }
        public string pr_chno2N { get; set; }
        public string pr_chno1N { get; set; }
        public decimal pr_chk11 { get; set; }
        public decimal pr_chk12 { get; set; }
        public decimal pr_chk13 { get; set; }
        public decimal pr_chk14 { get; set; }
        public decimal pr_chk21 { get; set; }
        public decimal pr_chk22 { get; set; }
        public decimal pr_chk23 { get; set; }
        public decimal pr_chk24 { get; set; }
        public decimal pr_chk25 { get; set; }
        public decimal pr_chk26 { get; set; }
        public decimal pr_chk27 { get; set; }
        public string pr_memo1 { get; set; }
        public string pr_memo2 { get; set; }
        public string pr_memo3 { get; set; }
        public string pr_memo4 { get; set; }
        public string pr_memo5 { get; set; }
        public string pr_memo6 { get; set; }
        public string pr_memo1N { get; set; }
        public string pr_memo2N { get; set; }
        public string pr_memo3N { get; set; }
        public string pr_memo4N { get; set; }
        public decimal pr_level { get; set; }
        public decimal pr_good { get; set; }
        public int pr_qty1 { get; set; }
        public int pr_qty2 { get; set; }
        public int pr_qty3 { get; set; }
        public int pr_qty4 { get; set; }
        public int pr_qty5 { get; set; }
        public int pr_qty6 { get; set; }
        public int pr_qty1N { get; set; }
        public int pr_qty2N { get; set; }
        public int pr_qty3N { get; set; }
        public int pr_qty4N { get; set; }
        public int pr_serial1 { get; set; }
        public int pr_serial2 { get; set; }
        public int pr_serial3 { get; set; }
        public int pr_serial4 { get; set; }
        public int pr_serial5 { get; set; }
        public int pr_serial6 { get; set; }
        public int pr_serial1N { get; set; }
        public int pr_serial2N { get; set; }
        public int pr_serial3N { get; set; }
        public int pr_serial4N { get; set; }
    }
}
