//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proeval
    {
        public string pe_sampno { get; set; }
        public string pe_emno { get; set; }
        public Nullable<System.DateTime> pe_date { get; set; }
        public string pe_cuno { get; set; }
        public string pe_prno { get; set; }
        public string pe_mnno { get; set; }
        public string pe_desc { get; set; }
        public string pe_setno { get; set; }
        public decimal pe_ordamt { get; set; }
        public decimal pe_model { get; set; }
        public decimal pe_wide { get; set; }
        public decimal pe_defee { get; set; }
        public decimal pe_cfee { get; set; }
        public decimal pe_sfee { get; set; }
        public decimal pe_kfee { get; set; }
        public decimal pe_quot { get; set; }
        public decimal pe_mprice { get; set; }
        public decimal pe_uprice { get; set; }
        public decimal pe_dhour { get; set; }
        public decimal pe_dprice { get; set; }
        public decimal pe_dchour { get; set; }
        public decimal pe_dcprice { get; set; }
        public decimal pe_coll { get; set; }
        public decimal pe_colw { get; set; }
        public decimal pe_colnum { get; set; }
        public decimal pe_cprice { get; set; }
        public decimal pe_pnum65 { get; set; }
        public decimal pe_price65 { get; set; }
        public decimal pe_pnum75 { get; set; }
        public decimal pe_price75 { get; set; }
        public decimal pe_pnum88 { get; set; }
        public decimal pe_price88 { get; set; }
        public decimal pe_other { get; set; }
        public decimal pe_oprice { get; set; }
        public decimal pe_platen { get; set; }
        public decimal pe_platep { get; set; }
        public decimal pe_zincl { get; set; }
        public decimal pe_zincw { get; set; }
        public decimal pe_zincnum { get; set; }
        public decimal pe_zincp { get; set; }
        public decimal pe_coppl { get; set; }
        public decimal pe_coppw { get; set; }
        public decimal pe_copnum { get; set; }
        public decimal pe_coppp { get; set; }
        public decimal pe_shinen { get; set; }
        public decimal pe_shinep { get; set; }
        public decimal pe_klong { get; set; }
        public decimal pe_iron { get; set; }
        public decimal pe_plas { get; set; }
        public decimal pe_paperl { get; set; }
        public decimal pe_paperw { get; set; }
        public decimal pe_paperf { get; set; }
        public decimal pe_paperp { get; set; }
        public decimal pe_printcn { get; set; }
        public decimal pe_printn { get; set; }
        public decimal pe_printp { get; set; }
        public decimal pe_kcn { get; set; }
        public decimal pe_ckp { get; set; }
        public decimal pe_discn { get; set; }
        public decimal pe_discp { get; set; }
        public decimal pe_time { get; set; }
        public decimal pe_pack { get; set; }
        public decimal pe_arrn { get; set; }
        public decimal pe_mrate { get; set; }
        public decimal pe_grossr { get; set; }
        public string pe_dpno { get; set; }
        public decimal pe_pafee { get; set; }
        public decimal pe_prfee { get; set; }
        public decimal pe_kcfee { get; set; }
        public decimal pe_disfee { get; set; }
        public decimal pe_packfee { get; set; }
        public decimal pe_spfee { get; set; }
        public decimal pe_totala { get; set; }
        public decimal pe_totalb { get; set; }
        public decimal pe_mafee1 { get; set; }
        public decimal pe_mafee2 { get; set; }
        public decimal pe_total { get; set; }
        public decimal pe_mocharge { get; set; }
        public decimal pe_gross { get; set; }
        public decimal pe_hitfee { get; set; }
        public decimal pe_spqty { get; set; }
        public decimal pe_spprice { get; set; }
        public decimal pe_pnum117 { get; set; }
        public decimal pe_price117 { get; set; }
        public decimal pe_pnum130 { get; set; }
        public decimal pe_price130 { get; set; }
        public decimal pe_pnum110 { get; set; }
        public decimal pe_price110 { get; set; }
        public decimal pe_pnum136 { get; set; }
        public decimal pe_price136 { get; set; }
        public decimal pe_pnum125 { get; set; }
        public decimal pe_price125 { get; set; }
        public decimal pe_pnum113 { get; set; }
        public decimal pe_price113 { get; set; }
        public decimal pe_spInkFee { get; set; }
    }
}
