//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proload_JIT
    {
        public System.DateTime po_date { get; set; }
        public decimal po_jit1 { get; set; }
        public decimal po_jit2 { get; set; }
        public decimal po_jit3 { get; set; }
        public decimal po_jit4 { get; set; }
        public decimal po_jit5 { get; set; }
    }
}
