//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class provide
    {
        public string pv_suno { get; set; }
        public string pv_mtno { get; set; }
        public string pv_mkno { get; set; }
        public Nullable<decimal> pv_long { get; set; }
        public Nullable<decimal> pv_width { get; set; }
        public Nullable<decimal> pv_amount { get; set; }
        public Nullable<System.DateTime> pv_date { get; set; }
        public string pv_setno { get; set; }
        public string pv_emno { get; set; }
        public System.DateTime pv_date1 { get; set; }
        public string pv_selno { get; set; }
        public string pv_emno1 { get; set; }
        public Nullable<System.DateTime> pv_date2 { get; set; }
        public string pv_dpno { get; set; }
        public decimal pv_accamt { get; set; }
        public Nullable<decimal> pv_yn { get; set; }
        public Nullable<decimal> pv_price { get; set; }
        public Nullable<decimal> pv_sig { get; set; }
        public string pv_dpno2 { get; set; }
        public string pv_curr { get; set; }
        public decimal pv_kind { get; set; }
        public Nullable<System.DateTime> pv_date3 { get; set; }
        public decimal pv_seqno { get; set; }
        public Nullable<System.DateTime> pv_cdate { get; set; }
    }
}
