//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prtranf
    {
        public string pf_emno { get; set; }
        public string pf_seqno { get; set; }
        public decimal pf_kind { get; set; }
        public Nullable<System.DateTime> pf_bdate { get; set; }
        public Nullable<System.DateTime> pf_edate { get; set; }
        public string pf_10 { get; set; }
        public string pf_11 { get; set; }
        public string pf_12 { get; set; }
        public string pf_13 { get; set; }
        public string pf_14 { get; set; }
        public string pf_15 { get; set; }
        public string pf_16 { get; set; }
        public string pf_17 { get; set; }
        public string pf_20 { get; set; }
        public string pf_21 { get; set; }
        public string pf_22 { get; set; }
        public string pf_23 { get; set; }
        public string pf_24 { get; set; }
        public string pf_25 { get; set; }
        public string pf_26 { get; set; }
        public string pf_27 { get; set; }
        public Nullable<decimal> pf_31 { get; set; }
        public string pf_32 { get; set; }
        public string pf_33 { get; set; }
        public Nullable<decimal> pf_34 { get; set; }
        public string pf_meno { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public decimal pf_flag { get; set; }
    }
}
