//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prvacal
    {
        public string vl_yymm { get; set; }
        public string vl_emno { get; set; }
        public decimal vl_seqno { get; set; }
        public string vl_ceno { get; set; }
        public Nullable<System.DateTime> vl_bdate { get; set; }
        public Nullable<System.DateTime> vl_edate { get; set; }
        public Nullable<decimal> vl_day { get; set; }
        public Nullable<decimal> vl_hour { get; set; }
        public Nullable<decimal> vl_min { get; set; }
        public string vl_memo { get; set; }
        public string vl_memo1 { get; set; }
        public string vl_cemno { get; set; }
        public Nullable<System.DateTime> vl_cdate { get; set; }
        public decimal vl_yn { get; set; }
        public string vl_vemno { get; set; }
        public Nullable<System.DateTime> vl_vdate { get; set; }
        public decimal vl_yn1 { get; set; }
        public string vl_vemno1 { get; set; }
        public Nullable<System.DateTime> vl_vdate1 { get; set; }
        public string vl_agent { get; set; }
        public decimal vl_ticket { get; set; }
        public Nullable<System.DateTime> vl_bdate1 { get; set; }
        public Nullable<System.DateTime> vl_edate1 { get; set; }
        public Nullable<decimal> vl_meetNo { get; set; }
        public string vl_meetName { get; set; }
        public Nullable<decimal> vl_meetNo1 { get; set; }
        public string vl_meetName1 { get; set; }
        public string vl_meetemno { get; set; }
        public string vl_meetemno1 { get; set; }
        public string vl_meetemnoB { get; set; }
        public string vl_meetemno1B { get; set; }
        public decimal The_seqno { get; set; }
        public string vl_TourNo { get; set; }
        public decimal vl_TourAmt { get; set; }
        public decimal vl_TourFeedBack { get; set; }
        public decimal vl_TourPost { get; set; }
        public string vl_TourYM { get; set; }
        public decimal vl_TourClose { get; set; }
        public decimal vl_TourInvkind { get; set; }
        public string vl_TourMemo { get; set; }
        public string vl_uemno { get; set; }
        public Nullable<System.DateTime> vl_udate { get; set; }
        public decimal vl_cancel { get; set; }
        public decimal vl_day1 { get; set; }
        public decimal vl_hour1 { get; set; }
        public decimal vl_min1 { get; set; }
    }
}
