//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prvacam
    {
        public string vm_yymm { get; set; }
        public string vm_emno { get; set; }
        public Nullable<decimal> vm_111 { get; set; }
        public Nullable<decimal> vm_112 { get; set; }
        public Nullable<decimal> vm_113 { get; set; }
        public Nullable<decimal> vm_121 { get; set; }
        public Nullable<decimal> vm_122 { get; set; }
        public Nullable<decimal> vm_123 { get; set; }
        public Nullable<decimal> vm_131 { get; set; }
        public Nullable<decimal> vm_132 { get; set; }
        public Nullable<decimal> vm_133 { get; set; }
        public Nullable<decimal> vm_141 { get; set; }
        public Nullable<decimal> vm_142 { get; set; }
        public Nullable<decimal> vm_143 { get; set; }
        public Nullable<decimal> vm_151 { get; set; }
        public Nullable<decimal> vm_152 { get; set; }
        public Nullable<decimal> vm_153 { get; set; }
        public Nullable<decimal> vm_161 { get; set; }
        public Nullable<decimal> vm_162 { get; set; }
        public Nullable<decimal> vm_163 { get; set; }
        public Nullable<decimal> vm_171 { get; set; }
        public Nullable<decimal> vm_172 { get; set; }
        public Nullable<decimal> vm_173 { get; set; }
        public Nullable<decimal> vm_181 { get; set; }
        public Nullable<decimal> vm_182 { get; set; }
        public Nullable<decimal> vm_183 { get; set; }
        public Nullable<decimal> vm_191 { get; set; }
        public Nullable<decimal> vm_192 { get; set; }
        public Nullable<decimal> vm_193 { get; set; }
        public Nullable<decimal> vm_201 { get; set; }
        public Nullable<decimal> vm_202 { get; set; }
        public Nullable<decimal> vm_203 { get; set; }
        public Nullable<decimal> vm_211 { get; set; }
        public Nullable<decimal> vm_212 { get; set; }
        public Nullable<decimal> vm_213 { get; set; }
        public Nullable<decimal> vm_221 { get; set; }
        public Nullable<decimal> vm_231 { get; set; }
        public Nullable<decimal> vm_241 { get; set; }
        public Nullable<decimal> vm_242 { get; set; }
        public Nullable<decimal> vm_243 { get; set; }
        public Nullable<decimal> vm_244 { get; set; }
        public Nullable<decimal> vm_251 { get; set; }
        public Nullable<decimal> vm_252 { get; set; }
        public Nullable<decimal> vm_253 { get; set; }
        public Nullable<decimal> vm_night { get; set; }
        public decimal vm_261 { get; set; }
        public decimal vm_262 { get; set; }
        public decimal vm_263 { get; set; }
        public decimal vm_meal { get; set; }
        public decimal vm_301 { get; set; }
        public decimal vm_302 { get; set; }
        public decimal vm_303 { get; set; }
        public decimal vm_311 { get; set; }
        public decimal vm_312 { get; set; }
        public decimal vm_313 { get; set; }
        public decimal vm_321 { get; set; }
        public decimal vm_322 { get; set; }
        public decimal vm_323 { get; set; }
        public decimal vm_911 { get; set; }
        public decimal vm_912 { get; set; }
        public decimal vm_913 { get; set; }
        public decimal vm_811 { get; set; }
        public decimal vm_812 { get; set; }
        public decimal vm_813 { get; set; }
        public decimal vm_331 { get; set; }
        public decimal vm_332 { get; set; }
        public decimal vm_333 { get; set; }
        public decimal vm_341 { get; set; }
        public decimal vm_342 { get; set; }
        public decimal vm_343 { get; set; }
        public decimal vm_351 { get; set; }
        public decimal vm_352 { get; set; }
        public decimal vm_353 { get; set; }
        public decimal vm_361 { get; set; }
        public decimal vm_362 { get; set; }
        public decimal vm_363 { get; set; }
    }
}
