//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pstatist
    {
        public string ps_suno { get; set; }
        public string ps_susname { get; set; }
        public string ps_mtno { get; set; }
        public decimal ps_qty1 { get; set; }
        public Nullable<decimal> ps_price1 { get; set; }
        public decimal ps_qty2 { get; set; }
        public Nullable<decimal> ps_price2 { get; set; }
        public decimal ps_qty3 { get; set; }
        public Nullable<decimal> ps_price3 { get; set; }
        public decimal ps_qty4 { get; set; }
        public Nullable<decimal> ps_price4 { get; set; }
        public decimal ps_qty5 { get; set; }
        public Nullable<decimal> ps_price5 { get; set; }
        public decimal ps_qty6 { get; set; }
        public Nullable<decimal> ps_price6 { get; set; }
        public decimal ps_qty7 { get; set; }
        public Nullable<decimal> ps_price7 { get; set; }
        public decimal ps_qty8 { get; set; }
        public Nullable<decimal> ps_price8 { get; set; }
        public decimal ps_qty9 { get; set; }
        public Nullable<decimal> ps_price9 { get; set; }
        public decimal ps_qty10 { get; set; }
        public Nullable<decimal> ps_price10 { get; set; }
        public decimal ps_qty11 { get; set; }
        public Nullable<decimal> ps_price11 { get; set; }
        public decimal ps_qty12 { get; set; }
        public Nullable<decimal> ps_price12 { get; set; }
        public string ps_year { get; set; }
        public string ps_dpno { get; set; }
    }
}
