//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qratio
    {
        public string qo_year { get; set; }
        public decimal qo_season { get; set; }
        public string qo_dpno { get; set; }
        public decimal qo_dir { get; set; }
        public Nullable<decimal> qo_ratio1 { get; set; }
        public Nullable<decimal> qo_ratio2 { get; set; }
        public Nullable<decimal> qo_ratio3 { get; set; }
        public Nullable<decimal> qo_ratio4 { get; set; }
        public Nullable<decimal> qo_ratio5 { get; set; }
        public Nullable<decimal> qo_ratio6 { get; set; }
        public Nullable<decimal> qo_ratio7 { get; set; }
        public Nullable<decimal> qo_ratio8 { get; set; }
        public Nullable<decimal> qo_ratio9 { get; set; }
        public Nullable<decimal> qo_ratio10 { get; set; }
    }
}
