//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityResult
    {
        public string The_YM { get; set; }
        public string The_dpno { get; set; }
        public string The_dpname { get; set; }
        public decimal EB_Result { get; set; }
        public decimal EB_Cost { get; set; }
        public decimal EA_Result { get; set; }
        public decimal EA_Cost { get; set; }
        public decimal Net_BadCnt { get; set; }
        public decimal Net_BadCost { get; set; }
    }
}
