//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityGoal
    {
        public string The_YY { get; set; }
        public string The_dpno { get; set; }
        public string The_dpname { get; set; }
        public decimal EB_Goal { get; set; }
        public decimal EA_Goal { get; set; }
        public decimal Error_Cost { get; set; }
        public decimal Net_Goal { get; set; }
        public decimal Net_Cost { get; set; }
    }
}
