//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quarter
    {
        public string qr_year { get; set; }
        public decimal qr_season { get; set; }
        public string qr_emno { get; set; }
        public string qr_dpno { get; set; }
        public Nullable<decimal> qr_dir { get; set; }
        public Nullable<decimal> qr_shour { get; set; }
        public Nullable<decimal> qr_rhour { get; set; }
        public Nullable<decimal> qr_ahour { get; set; }
        public Nullable<decimal> qr_vhour { get; set; }
        public Nullable<decimal> qr_badnum { get; set; }
        public Nullable<decimal> qr_aveeff { get; set; }
        public Nullable<decimal> qr_assess1 { get; set; }
        public Nullable<decimal> qr_assess2 { get; set; }
        public Nullable<decimal> qr_assess3 { get; set; }
        public Nullable<decimal> qr_assess4 { get; set; }
        public Nullable<decimal> qr_assess5 { get; set; }
        public Nullable<decimal> qr_assess6 { get; set; }
        public Nullable<decimal> qr_assess7 { get; set; }
        public Nullable<decimal> qr_assess8 { get; set; }
        public Nullable<decimal> qr_assess9 { get; set; }
        public Nullable<decimal> qr_assess10 { get; set; }
        public Nullable<decimal> qr_totassess { get; set; }
        public string qr_memo { get; set; }
        public Nullable<decimal> qr_post { get; set; }
        public Nullable<System.DateTime> qr_cdate { get; set; }
        public Nullable<System.DateTime> qr_postdate { get; set; }
    }
}
