//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation_CD
    {
        public string QND_NO { get; set; }
        public string QND_VERSION { get; set; }
        public string QND_ITEMNO { get; set; }
        public string QND_CUPDNO { get; set; }
        public string QND_SPEC { get; set; }
        public string QND_MAT { get; set; }
        public Nullable<decimal> QND_LONG { get; set; }
        public Nullable<decimal> QND_WIDTH { get; set; }
        public Nullable<decimal> QND_COLOR { get; set; }
        public Nullable<decimal> QND_QTY { get; set; }
        public decimal QND_UPRICE { get; set; }
        public Nullable<decimal> QND_TOTAL { get; set; }
        public Nullable<decimal> QND_MODCOST { get; set; }
        public Nullable<decimal> QND_DEVCOST { get; set; }
        public decimal QND_PARA1 { get; set; }
        public decimal QND_PARA2 { get; set; }
        public decimal QND_PARA3 { get; set; }
        public decimal QND_PARA4 { get; set; }
        public decimal QND_PARA5 { get; set; }
        public string QND_UNIT { get; set; }
        public decimal QND_PARA6 { get; set; }
    }
}
