//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation_C
    {
        public string QNC_NO { get; set; }
        public string QNC_VERSION { get; set; }
        public Nullable<System.DateTime> QNC_DATE { get; set; }
        public string QNC_CUNO { get; set; }
        public string QNC_CUNAME { get; set; }
        public string QNC_CUVIP1 { get; set; }
        public string QNC_EMNO { get; set; }
        public string QNC_EMCNAME { get; set; }
        public string QNC_BRAND { get; set; }
        public string QNC_MYKNO { get; set; }
        public string QNC_MYKNAME { get; set; }
        public string QNC_DELIVERY { get; set; }
        public Nullable<decimal> QNC_DELDAY { get; set; }
        public string QNC_PAYMENT { get; set; }
        public Nullable<System.DateTime> QNC_EFFDATE { get; set; }
        public string QNC_MEMO { get; set; }
        public Nullable<decimal> QNC_YN { get; set; }
        public string QNC_BRAND1 { get; set; }
        public decimal QNC_YN1 { get; set; }
        public decimal QNC_LTDAY { get; set; }
        public string QNC_FILENAME { get; set; }
    }
}
