//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruit
    {
        public string rt_no { get; set; }
        public string rt_emno { get; set; }
        public string rt_name { get; set; }
        public string rt_dpno { get; set; }
        public string rt_dpname { get; set; }
        public Nullable<System.DateTime> rt_cdate { get; set; }
        public Nullable<System.DateTime> rt_rdate { get; set; }
        public Nullable<int> rt_rcnt { get; set; }
        public string rt_31 { get; set; }
        public string rt_work { get; set; }
        public Nullable<decimal> rt_s1 { get; set; }
        public string rt_sala { get; set; }
        public Nullable<decimal> rt_s2 { get; set; }
        public string rt_yy1 { get; set; }
        public string rt_mm1 { get; set; }
        public string rt_yy2 { get; set; }
        public string rt_mm2 { get; set; }
        public Nullable<decimal> rt_s3 { get; set; }
        public string rt_desc { get; set; }
        public Nullable<decimal> rt_sex { get; set; }
        public Nullable<decimal> rt_agelimit { get; set; }
        public string rt_ageB { get; set; }
        public string rt_ageE { get; set; }
        public Nullable<int> rt_edu { get; set; }
        public Nullable<int> rt_deplimit { get; set; }
        public string rt_dep { get; set; }
        public Nullable<int> rt_license { get; set; }
        public Nullable<int> rt_langlimit { get; set; }
        public string rt_lang1 { get; set; }
        public string rt_lang2 { get; set; }
        public string rt_lang3 { get; set; }
        public Nullable<int> rt_explimit { get; set; }
        public string rt_exp { get; set; }
        public decimal rt_post { get; set; }
        public string rt_vemno { get; set; }
        public string rt_vname { get; set; }
        public Nullable<System.DateTime> rt_vdate { get; set; }
        public decimal rt_ver { get; set; }
        public decimal rt_close { get; set; }
        public decimal rt_print { get; set; }
    }
}
