//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refer_v
    {
        public string bybdate2 { get; set; }
        public string byemno2 { get; set; }
        public Nullable<decimal> rf_11 { get; set; }
        public Nullable<decimal> rf_12 { get; set; }
        public Nullable<decimal> rf_21 { get; set; }
        public Nullable<decimal> rf_22 { get; set; }
    }
}
