//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refer
    {
        public string rf_byymm { get; set; }
        public string rf_eyymm { get; set; }
        public Nullable<decimal> rf_11 { get; set; }
        public Nullable<decimal> rf_12 { get; set; }
        public Nullable<decimal> rf_13 { get; set; }
        public Nullable<decimal> rf_14 { get; set; }
        public Nullable<decimal> rf_15 { get; set; }
        public Nullable<decimal> rf_16 { get; set; }
        public Nullable<decimal> rf_21 { get; set; }
        public Nullable<decimal> rf_22 { get; set; }
        public Nullable<decimal> rf_23 { get; set; }
        public Nullable<decimal> rf_24 { get; set; }
        public Nullable<decimal> rf_25 { get; set; }
        public string rf_31 { get; set; }
        public string rf_32 { get; set; }
        public Nullable<decimal> rf_33 { get; set; }
        public Nullable<decimal> rf_34 { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public decimal rf_explain { get; set; }
    }
}
