//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class regbas
    {
        public string RGB_EMON { get; set; }
        public string RGB_CNAME { get; set; }
        public string RGB_DEP { get; set; }
        public Nullable<decimal> RGB_STDQTY { get; set; }
        public Nullable<decimal> RGB_SHDATE { get; set; }
        public Nullable<System.DateTime> RGB_MODDT { get; set; }
        public string RGB_PANO { get; set; }
        public decimal RGB_JIT { get; set; }
        public string RGB_MANO { get; set; }
        public decimal RGB_CARA { get; set; }
        public Nullable<System.DateTime> RGB_LOADA { get; set; }
        public Nullable<System.DateTime> RGB_EMPTYA { get; set; }
        public decimal RGB_CARB { get; set; }
        public Nullable<System.DateTime> RGB_LOADB { get; set; }
        public Nullable<System.DateTime> RGB_EMPTYB { get; set; }
        public decimal RGB_CARC { get; set; }
        public Nullable<System.DateTime> RGB_LOADC { get; set; }
        public Nullable<System.DateTime> RGB_EMPTYC { get; set; }
        public string RGB_CARID { get; set; }
        public decimal RGB_YN { get; set; }
        public string rgb_emnoA { get; set; }
        public string rgb_cnameA { get; set; }
        public decimal RGB_PREQTY { get; set; }
        public decimal rgb_Giant { get; set; }
        public decimal rgb_SkillLevel { get; set; }
        public decimal rgb_AutoKind { get; set; }
    }
}
