//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class regdataC
    {
        public string RGD_MKNO { get; set; }
        public string RGD_SETNO { get; set; }
        public Nullable<decimal> RGD_CARQTY { get; set; }
        public Nullable<System.DateTime> RGD_DATE { get; set; }
        public Nullable<System.DateTime> RGD_DATE2 { get; set; }
        public string RGD_SIZE { get; set; }
        public string RGD_WS { get; set; }
        public string RGD_SPEC { get; set; }
        public Nullable<decimal> RGD_MPAPER { get; set; }
        public Nullable<decimal> RGD_HOUR { get; set; }
        public string RGD_YN { get; set; }
        public string RGD_SCHYN { get; set; }
        public string RGD_REMARK { get; set; }
        public string RGD_DEPNO { get; set; }
        public string RGD_PSIZE { get; set; }
        public string RGD_BOMPER { get; set; }
        public string RGD_PAPPRE { get; set; }
        public string RGD_COLPRE { get; set; }
        public string RGD_CUNO { get; set; }
        public Nullable<System.DateTime> RGD_BOMDATE { get; set; }
        public Nullable<System.DateTime> RGD_PAPERDATE { get; set; }
        public Nullable<System.DateTime> RGD_COLDATE { get; set; }
        public string RGD_PRNO { get; set; }
        public decimal RGD_netTemp { get; set; }
        public decimal RGD_NETQTY { get; set; }
        public string RGD_CARNO { get; set; }
        public decimal RGD_Process { get; set; }
        public Nullable<System.DateTime> RGD_PrepareDate { get; set; }
        public string RGD_TBNO { get; set; }
        public decimal rgd_paperflag { get; set; }
        public decimal rgd_combine { get; set; }
        public string rgd_reason { get; set; }
        public decimal rgd_netpre { get; set; }
        public decimal rgd_getflim { get; set; }
        public string rgd_suno { get; set; }
        public string rgd_group { get; set; }
        public decimal rgd_SchTimes { get; set; }
        public string rgd_pbseq { get; set; }
        public Nullable<System.DateTime> rgd_getcard { get; set; }
        public decimal rgd_ExtraYN { get; set; }
        public int rgd_jit { get; set; }
    }
}
