//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reqdata
    {
        public string rd_no { get; set; }
        public System.DateTime rd_date { get; set; }
        public Nullable<decimal> rd_use { get; set; }
        public string rd_dpno { get; set; }
        public string rd_emno { get; set; }
        public string rd_mtno { get; set; }
        public string rd_diff { get; set; }
        public string rd_ordno { get; set; }
        public Nullable<decimal> rd_width { get; set; }
        public Nullable<decimal> rd_long { get; set; }
        public Nullable<decimal> rd_qty { get; set; }
        public Nullable<decimal> rd_qty1 { get; set; }
        public decimal rd_qty2 { get; set; }
        public Nullable<decimal> rd_yn { get; set; }
        public string rd_setno { get; set; }
        public string rd_memo { get; set; }
        public decimal rd_seqno { get; set; }
        public decimal rd_ver { get; set; }
        public string rd_veremno { get; set; }
        public string rd_vername { get; set; }
        public Nullable<System.DateTime> rd_verdate { get; set; }
        public decimal rd_post { get; set; }
        public Nullable<System.DateTime> rd_postdate { get; set; }
        public decimal rd_width_org { get; set; }
        public decimal rd_long_org { get; set; }
        public decimal rd_qty_org { get; set; }
        public string rd_cuno { get; set; }
        public string rd_fa { get; set; }
        public string rd_prno { get; set; }
        public string rd_dsn { get; set; }
        public decimal rd_src { get; set; }
    }
}
