//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class retdata
    {
        public string rt_no { get; set; }
        public string rt_suno { get; set; }
        public Nullable<System.DateTime> rt_date { get; set; }
        public string rt_emno { get; set; }
        public string rt_stno { get; set; }
        public Nullable<System.DateTime> rt_chkdate { get; set; }
        public string rt_mtno { get; set; }
        public Nullable<decimal> rt_width { get; set; }
        public Nullable<decimal> rt_long { get; set; }
        public string rt_store { get; set; }
        public string rt_apno { get; set; }
        public decimal rt_qty { get; set; }
        public Nullable<decimal> rt_money { get; set; }
        public string rt_mkno { get; set; }
        public Nullable<decimal> rt_handle { get; set; }
        public Nullable<decimal> rt_stocks { get; set; }
        public Nullable<decimal> rt_post { get; set; }
        public string rt_reason { get; set; }
        public Nullable<decimal> rt_yn { get; set; }
        public Nullable<System.DateTime> rt_date1 { get; set; }
        public string rt_puno { get; set; }
        public string rt_orno { get; set; }
        public string rt_result { get; set; }
        public decimal rt_ikqty { get; set; }
        public string rt_src { get; set; }
        public decimal rt_srcSeqno { get; set; }
        public Nullable<System.DateTime> rt_cdate { get; set; }
    }
}
