//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class revenue_edit
    {
        public string The_YY { get; set; }
        public string The_fano { get; set; }
        public string The_faname { get; set; }
        public int The_ceno { get; set; }
        public string The_relation { get; set; }
        public decimal m01 { get; set; }
        public decimal m02 { get; set; }
        public decimal m03 { get; set; }
        public decimal m04 { get; set; }
        public decimal m05 { get; set; }
        public decimal m06 { get; set; }
        public decimal m07 { get; set; }
        public decimal m08 { get; set; }
        public decimal m09 { get; set; }
        public decimal m10 { get; set; }
        public decimal m11 { get; set; }
        public decimal m12 { get; set; }
        public decimal mTT { get; set; }
        public string note01 { get; set; }
        public string note02 { get; set; }
        public string note03 { get; set; }
        public string note04 { get; set; }
        public string note05 { get; set; }
        public string note06 { get; set; }
        public string note07 { get; set; }
        public string note08 { get; set; }
        public string note09 { get; set; }
        public string note10 { get; set; }
        public string note11 { get; set; }
        public string note12 { get; set; }
        public string noteTT { get; set; }
        public Nullable<System.DateTime> Upd_DATE { get; set; }
        public string Upd_EMNO { get; set; }
    }
}
