//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomRec
    {
        public decimal rc_seq { get; set; }
        public Nullable<System.DateTime> rc_date { get; set; }
        public string rc_emno { get; set; }
        public string rc_name { get; set; }
        public string rc_emno1 { get; set; }
        public string rc_name1 { get; set; }
        public string rc_rmid { get; set; }
        public string rc_rmname { get; set; }
        public Nullable<System.DateTime> rc_bdate { get; set; }
        public Nullable<System.DateTime> rc_edate { get; set; }
        public string rc_use { get; set; }
        public Nullable<decimal> rc_num { get; set; }
        public string rc_cuno { get; set; }
        public string rc_cuname { get; set; }
        public string rc_cuname1 { get; set; }
        public string rc_subject { get; set; }
        public string rc_subject1 { get; set; }
        public string rc_subject2 { get; set; }
        public decimal rc_v0 { get; set; }
        public decimal rc_v1 { get; set; }
        public decimal rc_v2 { get; set; }
        public decimal rc_v3 { get; set; }
        public string rc_tano { get; set; }
        public decimal rc_ver { get; set; }
        public Nullable<System.DateTime> rc_vdate { get; set; }
        public string rc_vemno { get; set; }
        public string rc_vemcname { get; set; }
        public Nullable<System.DateTime> rc_cdate { get; set; }
        public Nullable<int> rc_rcfseqno { get; set; }
    }
}
