//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary_p14
    {
        public string my_emno { get; set; }
        public string em_cname { get; set; }
        public Nullable<decimal> p1 { get; set; }
        public Nullable<decimal> p2 { get; set; }
        public Nullable<decimal> p3 { get; set; }
        public Nullable<decimal> p4 { get; set; }
        public Nullable<decimal> p5 { get; set; }
        public Nullable<decimal> p6 { get; set; }
        public Nullable<decimal> p7 { get; set; }
        public Nullable<decimal> p8 { get; set; }
        public Nullable<decimal> p9 { get; set; }
        public Nullable<decimal> p10 { get; set; }
        public Nullable<decimal> p11 { get; set; }
        public Nullable<decimal> p12 { get; set; }
        public Nullable<decimal> p13 { get; set; }
        public Nullable<decimal> p14 { get; set; }
        public Nullable<decimal> p15 { get; set; }
        public Nullable<decimal> p16 { get; set; }
        public Nullable<decimal> p17 { get; set; }
        public Nullable<decimal> p18 { get; set; }
        public Nullable<decimal> p19 { get; set; }
        public Nullable<decimal> p20 { get; set; }
        public Nullable<decimal> p21 { get; set; }
        public Nullable<decimal> p22 { get; set; }
        public Nullable<decimal> p23 { get; set; }
        public Nullable<decimal> p24 { get; set; }
    }
}
