//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleWard
    {
        public string sw_yymm { get; set; }
        public Nullable<decimal> sw_rate { get; set; }
        public Nullable<decimal> sw_sale1 { get; set; }
        public Nullable<decimal> sw_sale2 { get; set; }
        public Nullable<decimal> sw_sale3 { get; set; }
        public Nullable<decimal> sw_total { get; set; }
    }
}
