//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPR13Tmp
    {
        public string by_emno { get; set; }
        public string by_seqno { get; set; }
        public string by_ceno1 { get; set; }
        public string by_ceno2 { get; set; }
        public Nullable<decimal> by_ceno3 { get; set; }
        public Nullable<decimal> by_ceno4 { get; set; }
        public Nullable<System.DateTime> by_bdate { get; set; }
        public Nullable<System.DateTime> by_edate { get; set; }
        public Nullable<decimal> by_11 { get; set; }
        public Nullable<decimal> by_21 { get; set; }
        public Nullable<decimal> by_22 { get; set; }
        public Nullable<decimal> by_23 { get; set; }
        public Nullable<decimal> by_24 { get; set; }
        public Nullable<decimal> by_25 { get; set; }
        public Nullable<decimal> by_26 { get; set; }
        public Nullable<decimal> by_27 { get; set; }
        public Nullable<decimal> by_28 { get; set; }
        public Nullable<decimal> by_29 { get; set; }
        public Nullable<decimal> by_11_std { get; set; }
        public string em_no { get; set; }
        public string em_cname { get; set; }
        public Nullable<decimal> em_13 { get; set; }
        public string em_dpno { get; set; }
        public string em_work { get; set; }
        public string dp_no { get; set; }
        public string dp_name { get; set; }
        public string ce_no { get; set; }
        public string ce_name { get; set; }
        public int is111 { get; set; }
        public int is131 { get; set; }
        public int inamt1 { get; set; }
        public int is112 { get; set; }
        public int is132 { get; set; }
        public int inamt2 { get; set; }
        public decimal rf_11 { get; set; }
        public decimal rf_12 { get; set; }
        public decimal rf_21 { get; set; }
        public decimal rf_22 { get; set; }
        public Nullable<System.DateTime> em_20 { get; set; }
        public int my_taxinc { get; set; }
        public decimal rf_explain { get; set; }
    }
}
