//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sataxF
    {
        public Nullable<decimal> sf_othour { get; set; }
        public Nullable<decimal> sf_tax1 { get; set; }
        public Nullable<decimal> sf_tax2 { get; set; }
        public Nullable<decimal> sf_tax3 { get; set; }
        public decimal sf_shifsal { get; set; }
        public decimal sf_std01 { get; set; }
        public decimal sf_std11 { get; set; }
        public decimal sf_std12 { get; set; }
        public decimal sf_std13 { get; set; }
        public decimal sf_std14 { get; set; }
        public decimal sf_std21 { get; set; }
        public decimal sf_std31 { get; set; }
        public decimal sf_std41 { get; set; }
        public decimal sf_std42 { get; set; }
        public decimal sf_para11 { get; set; }
        public decimal sf_para12 { get; set; }
        public decimal sf_para13 { get; set; }
        public decimal sf_para14 { get; set; }
        public decimal sf_para21 { get; set; }
        public decimal sf_para31 { get; set; }
        public decimal sf_para41 { get; set; }
        public decimal sf_para42 { get; set; }
        public decimal sf_para43 { get; set; }
        public decimal sf_para01 { get; set; }
        public decimal sf_para44 { get; set; }
        public decimal sf_std51 { get; set; }
        public decimal sf_std52 { get; set; }
        public decimal sf_std53 { get; set; }
        public decimal sf_std61 { get; set; }
        public decimal sf_std62 { get; set; }
        public decimal sf_std63 { get; set; }
        public decimal sf_para51 { get; set; }
        public decimal sf_para52 { get; set; }
        public decimal sf_para53 { get; set; }
    }
}
