//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class satax
    {
        public decimal ta_id { get; set; }
        public Nullable<decimal> ta_spous { get; set; }
        public Nullable<decimal> ta_parent { get; set; }
        public Nullable<decimal> ta_stand { get; set; }
        public Nullable<decimal> ta_spec { get; set; }
        public Nullable<decimal> ta_low { get; set; }
        public Nullable<decimal> ta_rate { get; set; }
        public Nullable<decimal> ta_up1 { get; set; }
        public Nullable<decimal> ta_item1 { get; set; }
        public Nullable<decimal> ta_diff1 { get; set; }
        public Nullable<decimal> ta_up2 { get; set; }
        public Nullable<decimal> ta_item2 { get; set; }
        public Nullable<decimal> ta_diff2 { get; set; }
        public Nullable<decimal> ta_up3 { get; set; }
        public Nullable<decimal> ta_item3 { get; set; }
        public Nullable<decimal> ta_diff3 { get; set; }
        public Nullable<decimal> ta_up4 { get; set; }
        public Nullable<decimal> ta_item4 { get; set; }
        public Nullable<decimal> ta_diff4 { get; set; }
        public Nullable<decimal> ta_up5 { get; set; }
        public Nullable<decimal> ta_item5 { get; set; }
        public Nullable<decimal> ta_diff5 { get; set; }
        public Nullable<decimal> ta_up6 { get; set; }
        public Nullable<decimal> ta_item6 { get; set; }
        public Nullable<decimal> ta_diff6 { get; set; }
        public Nullable<decimal> ta_up7 { get; set; }
        public Nullable<decimal> ta_item7 { get; set; }
        public Nullable<decimal> ta_diff7 { get; set; }
        public Nullable<decimal> ta_up8 { get; set; }
        public Nullable<decimal> ta_item8 { get; set; }
        public Nullable<decimal> ta_diff8 { get; set; }
        public decimal ta_start { get; set; }
    }
}
