//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchEmptyLog
    {
        public decimal The_seq { get; set; }
        public string The_emno { get; set; }
        public string The_cname { get; set; }
        public Nullable<System.DateTime> RGB_EMPTYA { get; set; }
        public Nullable<System.DateTime> RGB_EMPTYB { get; set; }
        public string brg_mkno { get; set; }
        public string brg_setno { get; set; }
        public Nullable<decimal> brg_carqty { get; set; }
        public Nullable<System.DateTime> brg_date { get; set; }
        public Nullable<decimal> brg_dtord { get; set; }
        public Nullable<decimal> brg_subno { get; set; }
        public string brg_bompre { get; set; }
        public string brg_paper { get; set; }
        public decimal rgb_yn { get; set; }
        public Nullable<System.DateTime> mo_bomdate { get; set; }
        public Nullable<System.DateTime> mo_paperdate { get; set; }
        public string rgd_group { get; set; }
        public decimal rgd_paperflag { get; set; }
        public string The_memo { get; set; }
        public decimal mo_MakePaper { get; set; }
    }
}
