//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sdeduct
    {
        public string sd_suno { get; set; }
        public Nullable<System.DateTime> sd_date { get; set; }
        public string sd_puno { get; set; }
        public string sd_mtno { get; set; }
        public Nullable<decimal> sd_deamt { get; set; }
        public string sd_memo1 { get; set; }
        public string sd_memo2 { get; set; }
        public Nullable<System.DateTime> sd_cdate { get; set; }
        public string sd_faatt { get; set; }
        public decimal sd_seqno { get; set; }
        public string sd_pano { get; set; }
        public string sd_ym { get; set; }
        public decimal sd_pkind { get; set; }
        public decimal sd_dkind { get; set; }
    }
}
