//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class se_seum02_01
    {
        public string db_cuno { get; set; }
        public string db_cusname { get; set; }
        public string im_emno { get; set; }
        public string em_cname { get; set; }
        public string cu_dpno { get; set; }
        public Nullable<System.DateTime> db_date { get; set; }
        public string db_noteno { get; set; }
        public string db_pdno { get; set; }
        public Nullable<decimal> db_amount { get; set; }
        public Nullable<decimal> db_uprice { get; set; }
        public string im_cause { get; set; }
        public string re_reason { get; set; }
        public Nullable<decimal> money { get; set; }
        public string im_bono { get; set; }
    }
}
