//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class se_secy07_02
    {
        public string The_yy { get; set; }
        public string The_cuno { get; set; }
        public string The_cuname { get; set; }
        public Nullable<decimal> qty1 { get; set; }
        public Nullable<decimal> qty2 { get; set; }
        public Nullable<decimal> qty3 { get; set; }
        public Nullable<decimal> qty4 { get; set; }
        public Nullable<decimal> qty5 { get; set; }
        public Nullable<decimal> qty6 { get; set; }
        public Nullable<decimal> qty7 { get; set; }
        public Nullable<decimal> qty8 { get; set; }
        public Nullable<decimal> qty9 { get; set; }
        public Nullable<decimal> qty10 { get; set; }
        public Nullable<decimal> qty11 { get; set; }
        public Nullable<decimal> qty12 { get; set; }
        public string The_dpno { get; set; }
        public decimal amt1 { get; set; }
        public decimal amt2 { get; set; }
        public decimal amt3 { get; set; }
        public decimal amt4 { get; set; }
        public decimal amt5 { get; set; }
        public decimal amt6 { get; set; }
        public decimal amt7 { get; set; }
        public decimal amt8 { get; set; }
        public decimal amt9 { get; set; }
        public decimal amt10 { get; set; }
        public decimal amt11 { get; set; }
        public decimal amt12 { get; set; }
    }
}
