//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seaassess
    {
        public string se_emno { get; set; }
        public string se_yy { get; set; }
        public Nullable<decimal> se_wgrade1 { get; set; }
        public Nullable<decimal> se_ass1 { get; set; }
        public Nullable<decimal> se_oass1 { get; set; }
        public Nullable<decimal> se_wass1 { get; set; }
        public Nullable<decimal> se_wgrade2 { get; set; }
        public Nullable<decimal> se_ass2 { get; set; }
        public Nullable<decimal> se_oass2 { get; set; }
        public Nullable<decimal> se_wass2 { get; set; }
        public Nullable<decimal> se_wgrade3 { get; set; }
        public Nullable<decimal> se_ass3 { get; set; }
        public Nullable<decimal> se_oass3 { get; set; }
        public Nullable<decimal> se_wass3 { get; set; }
        public Nullable<decimal> se_wgrade4 { get; set; }
        public Nullable<decimal> se_ass4 { get; set; }
        public Nullable<decimal> se_oass4 { get; set; }
        public Nullable<decimal> se_wass4 { get; set; }
        public Nullable<decimal> se_yass { get; set; }
        public string se_rank { get; set; }
        public string se_prank { get; set; }
        public Nullable<decimal> se_upgrade { get; set; }
        public Nullable<decimal> se_dgrade { get; set; }
        public Nullable<decimal> se_yn { get; set; }
        public Nullable<decimal> se_srate { get; set; }
        public string se_yrank { get; set; }
        public Nullable<decimal> se_tgrade { get; set; }
        public string se_rank_org { get; set; }
        public decimal se_srate_org { get; set; }
    }
}
