//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sepeff
    {
        public string sf_ym { get; set; }
        public string sf_emno { get; set; }
        public Nullable<decimal> sf_coamt { get; set; }
        public Nullable<decimal> sf_filmamt { get; set; }
        public Nullable<decimal> sf_area { get; set; }
        public Nullable<decimal> sf_samt { get; set; }
        public Nullable<decimal> sf_sphour { get; set; }
        public Nullable<decimal> sf_hour { get; set; }
        public Nullable<decimal> sf_ralhour { get; set; }
        public Nullable<decimal> sf_bhour { get; set; }
        public Nullable<decimal> sf_efrw { get; set; }
        public Nullable<decimal> sf_dhour { get; set; }
        public Nullable<decimal> sf_avgeff { get; set; }
        public decimal sf_lostmoney { get; set; }
    }
}
