//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setbase
    {
        public string se_setno { get; set; }
        public Nullable<decimal> se_qty { get; set; }
        public string se_dpno { get; set; }
        public Nullable<System.DateTime> se_date { get; set; }
        public Nullable<decimal> se_sqty { get; set; }
        public Nullable<decimal> se_keep { get; set; }
        public Nullable<decimal> se_kday { get; set; }
        public decimal se_period { get; set; }
    }
}
