//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetPriceChg
    {
        public string sg_cuno { get; set; }
        public string sg_setno { get; set; }
        public decimal sg_oprice { get; set; }
        public decimal sg_nprice { get; set; }
        public System.DateTime sg_update { get; set; }
        public string sg_emno { get; set; }
        public decimal sg_seqno { get; set; }
    }
}
