//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class signature
    {
        public int ac_dsn { get; set; }
        public string ac_name { get; set; }
        public Nullable<int> ac_kind { get; set; }
        public string ac_kind1 { get; set; }
        public Nullable<int> ac_qty { get; set; }
        public Nullable<int> ac_qty1 { get; set; }
        public string ac_dpno1 { get; set; }
        public string dp_name1 { get; set; }
        public string ac_emno1 { get; set; }
        public string ac_cname1 { get; set; }
        public string ac_dpno2 { get; set; }
        public string dp_name2 { get; set; }
        public string ac_emno2 { get; set; }
        public string ac_cname2 { get; set; }
        public Nullable<int> ac_verify { get; set; }
        public string ac_verify1 { get; set; }
        public string ac_verify1n { get; set; }
        public string ac_verify2 { get; set; }
        public string ac_verify2n { get; set; }
        public string ac_verify3 { get; set; }
        public string ac_verify3n { get; set; }
        public Nullable<int> ac_state { get; set; }
        public Nullable<System.DateTime> ac_cdate { get; set; }
        public string ac_range { get; set; }
        public string ac_groupA { get; set; }
        public string ac_groupB { get; set; }
        public string ac_groupC { get; set; }
        public string ac_groupD { get; set; }
        public string ac_oemno { get; set; }
        public string ac_oname { get; set; }
        public string ac_cvemno1 { get; set; }
        public string ac_cvname1 { get; set; }
        public string ac_cvemno2 { get; set; }
        public string ac_cvname2 { get; set; }
    }
}
