//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class signatureUse
    {
        public string au_dsn { get; set; }
        public string au_no { get; set; }
        public string au_name { get; set; }
        public string au_dpno { get; set; }
        public string dp_name { get; set; }
        public string au_emno { get; set; }
        public string au_cname { get; set; }
        public string au_doc { get; set; }
        public string au_reason { get; set; }
        public Nullable<System.DateTime> au_cdate { get; set; }
        public Nullable<int> au_verify { get; set; }
        public Nullable<int> au_flag0 { get; set; }
        public Nullable<int> au_yn0 { get; set; }
        public string au_emno0 { get; set; }
        public string au_cname0 { get; set; }
        public Nullable<System.DateTime> au_pdate0 { get; set; }
        public Nullable<int> au_flag1 { get; set; }
        public Nullable<int> au_yn1 { get; set; }
        public string au_emno1 { get; set; }
        public string au_cname1 { get; set; }
        public Nullable<System.DateTime> au_pdate1 { get; set; }
        public Nullable<int> au_flag2 { get; set; }
        public Nullable<int> au_yn2 { get; set; }
        public string au_emno2 { get; set; }
        public string au_cname2 { get; set; }
        public Nullable<System.DateTime> au_pdate2 { get; set; }
        public Nullable<int> au_flag3 { get; set; }
        public Nullable<int> au_yn3 { get; set; }
        public string au_emno3 { get; set; }
        public string au_cname3 { get; set; }
        public Nullable<System.DateTime> au_pdate3 { get; set; }
        public Nullable<int> au_out { get; set; }
        public string au_dsn1 { get; set; }
        public Nullable<System.DateTime> au_odate { get; set; }
        public string au_oemno { get; set; }
        public string au_oname { get; set; }
        public string au_reject { get; set; }
        public Nullable<int> au_contract { get; set; }
        public Nullable<int> au_flag6 { get; set; }
        public Nullable<int> au_yn6 { get; set; }
        public string au_emno6 { get; set; }
        public string au_cname6 { get; set; }
        public Nullable<System.DateTime> au_pdate6 { get; set; }
        public Nullable<int> au_flag7 { get; set; }
        public Nullable<int> au_yn7 { get; set; }
        public string au_emno7 { get; set; }
        public string au_cname7 { get; set; }
        public Nullable<System.DateTime> au_pdate7 { get; set; }
        public string au_unit { get; set; }
        public string au_subject { get; set; }
        public string au_memo { get; set; }
    }
}
