//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialHour
    {
        public int sh_no { get; set; }
        public string sh_emno { get; set; }
        public string sh_dpno { get; set; }
        public System.DateTime sh_date { get; set; }
        public string sh_hour_s { get; set; }
        public string sh_hour_e { get; set; }
        public decimal sh_hour { get; set; }
        public string sh_reason { get; set; }
        public string sh_note { get; set; }
        public decimal sh_yn { get; set; }
        public decimal sh_post { get; set; }
        public Nullable<System.DateTime> sh_cdate { get; set; }
        public string sh_cemno { get; set; }
    }
}
