//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stchg
    {
        public string sc_diff { get; set; }
        public string sc_mtno { get; set; }
        public decimal sc_type { get; set; }
        public string sc_no { get; set; }
        public string sc_dpno1 { get; set; }
        public decimal sc_qty { get; set; }
        public string sc_ordno { get; set; }
        public Nullable<decimal> sc_width { get; set; }
        public Nullable<decimal> sc_long { get; set; }
        public Nullable<decimal> sc_pcsqty { get; set; }
        public System.DateTime sc_date { get; set; }
        public Nullable<System.DateTime> sc_cdate { get; set; }
        public string sc_memo { get; set; }
        public decimal sc_seqno { get; set; }
        public string sc_fa { get; set; }
    }
}
