//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stkstore
    {
        public string ss_dpno { get; set; }
        public string ss_no { get; set; }
        public string ss_spec { get; set; }
        public Nullable<decimal> ss_qty { get; set; }
        public string ss_subno { get; set; }
        public System.DateTime ss_date { get; set; }
        public string ss_mkno { get; set; }
        public string ss_setno { get; set; }
        public string ss_loc1 { get; set; }
        public string ss_loc2 { get; set; }
        public string ss_loc3 { get; set; }
        public Nullable<decimal> ss_close { get; set; }
        public Nullable<decimal> ss_setnum { get; set; }
        public Nullable<decimal> ss_10 { get; set; }
        public decimal ss_kind { get; set; }
        public decimal ss_yn { get; set; }
        public decimal ss_evaqty { get; set; }
        public string ss_emno { get; set; }
        public decimal ss_seqno { get; set; }
        public decimal ss_GoodQty { get; set; }
    }
}
