//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockh_Detail
    {
        public string YM { get; set; }
        public string sh_no { get; set; }
        public string b3_cuupno { get; set; }
        public string sh_spec { get; set; }
        public Nullable<decimal> sh_uprice { get; set; }
        public decimal Qty0 { get; set; }
        public decimal Qty1 { get; set; }
        public decimal Cnt1 { get; set; }
        public decimal Qty2 { get; set; }
        public decimal Cnt2 { get; set; }
        public decimal Qty3 { get; set; }
        public decimal Qty4 { get; set; }
        public decimal Qty5 { get; set; }
        public decimal Qty6 { get; set; }
        public decimal Qty7 { get; set; }
        public decimal Qty8 { get; set; }
    }
}
