//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTake2
    {
        public string The_YM { get; set; }
        public decimal The_Kind { get; set; }
        public string The_No { get; set; }
        public string fs_suno { get; set; }
        public string fs_mtno { get; set; }
        public string mt_spec { get; set; }
        public Nullable<decimal> ms_width { get; set; }
        public Nullable<decimal> ms_long { get; set; }
        public Nullable<decimal> ms_qty { get; set; }
        public string mt_unit { get; set; }
        public string mt_unit1 { get; set; }
        public Nullable<System.DateTime> ms_date { get; set; }
        public Nullable<decimal> fs_qty { get; set; }
        public string fs_loc1 { get; set; }
        public string fs_loc2 { get; set; }
        public string fs_loc3 { get; set; }
        public string fs_loc4 { get; set; }
        public string fs_loc5 { get; set; }
        public Nullable<decimal> mt_cost { get; set; }
        public Nullable<decimal> AccQty { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> mt_date1 { get; set; }
    }
}
