//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockpayb
    {
        public Nullable<System.DateTime> sb_date { get; set; }
        public Nullable<decimal> sb_bqty { get; set; }
        public decimal sb_long { get; set; }
        public string sb_mtno { get; set; }
        public string sb_emno { get; set; }
        public string sb_puno { get; set; }
        public Nullable<decimal> sb_uprice { get; set; }
        public Nullable<decimal> sb_total { get; set; }
        public decimal sb_qty { get; set; }
        public decimal sb_width { get; set; }
        public System.DateTime sb_date1 { get; set; }
        public string sb_stno { get; set; }
        public string sb_suno { get; set; }
        public Nullable<decimal> sb_sqty { get; set; }
        public string sb_mkno { get; set; }
        public string sb_diff { get; set; }
        public string sb_ftno { get; set; }
        public string sb_payno { get; set; }
        public decimal sb_chkqty { get; set; }
        public decimal sb_seqno { get; set; }
        public string sb_orno { get; set; }
        public string sb_memo { get; set; }
        public string sb_spec { get; set; }
        public string sb_SNO1 { get; set; }
        public string sb_SNO2 { get; set; }
        public string sb_curr { get; set; }
        public string sb_ikno { get; set; }
    }
}
