//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreClean
    {
        public decimal sn_seqno { get; set; }
        public string sn_ym { get; set; }
        public string sn_no { get; set; }
        public string sn_desc { get; set; }
        public string sn_mykno { get; set; }
        public Nullable<decimal> sn_amt { get; set; }
        public Nullable<decimal> sn_qty { get; set; }
        public Nullable<decimal> sn_total { get; set; }
        public Nullable<decimal> sn_totalnt { get; set; }
        public Nullable<System.DateTime> sn_date { get; set; }
        public string sn_memo { get; set; }
        public string sn_memod { get; set; }
    }
}
