//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsidy
    {
        public string sy_ProductKind { get; set; }
        public string sy_OilSerial { get; set; }
        public string sy_chno { get; set; }
        public int sy_times1 { get; set; }
        public int sy_times2 { get; set; }
        public int sy_times3 { get; set; }
        public Nullable<System.DateTime> sy_cdate { get; set; }
        public string sy_emno { get; set; }
    }
}
