//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supcard
    {
        public string sa_suno { get; set; }
        public string sa_sname { get; set; }
        public string sa_payway { get; set; }
        public string sa_date { get; set; }
        public decimal sa_class { get; set; }
        public string sa_abst { get; set; }
        public Nullable<decimal> sa_amount { get; set; }
        public Nullable<decimal> sa_disc { get; set; }
        public Nullable<decimal> sa_yield { get; set; }
        public Nullable<System.DateTime> sa_date1 { get; set; }
        public string sa_dpno { get; set; }
        public decimal sa_seq { get; set; }
    }
}
