//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_chg
    {
        public int su_dsn { get; set; }
        public string su_no { get; set; }
        public string su_sname { get; set; }
        public string su_reqpay1 { get; set; }
        public string su_reqpay2 { get; set; }
        public Nullable<decimal> su_date1 { get; set; }
        public Nullable<decimal> su_date2 { get; set; }
        public string su_pay1 { get; set; }
        public string su_pay2 { get; set; }
        public string su_bank1 { get; set; }
        public string su_bank2 { get; set; }
        public string su_cemno { get; set; }
        public string su_cname { get; set; }
        public Nullable<System.DateTime> su_cdate { get; set; }
        public Nullable<int> su_verify { get; set; }
        public string su_vemno { get; set; }
        public string su_vname { get; set; }
        public Nullable<System.DateTime> su_vdate { get; set; }
    }
}
