//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysgrouppriv
    {
        public string sgp_sgid { get; set; }
        public string sgp_sflid { get; set; }
        public Nullable<decimal> sgp_add { get; set; }
        public Nullable<decimal> sgp_edit { get; set; }
        public Nullable<decimal> sgp_del { get; set; }
        public Nullable<decimal> sgp_qry { get; set; }
        public Nullable<decimal> sgp_save { get; set; }
        public Nullable<decimal> sgp_cancel { get; set; }
        public Nullable<decimal> sgp_f1 { get; set; }
        public Nullable<decimal> sgp_f2 { get; set; }
        public Nullable<decimal> sgp_f3 { get; set; }
        public Nullable<decimal> sgp_f4 { get; set; }
        public Nullable<decimal> sgp_f5 { get; set; }
        public Nullable<decimal> sgp_f6 { get; set; }
        public Nullable<decimal> sgp_f7 { get; set; }
        public Nullable<decimal> sgp_f8 { get; set; }
        public Nullable<decimal> sgp_f9 { get; set; }
    }
}
