//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class systable
    {
        public string tablename { get; set; }
        public string fieldname { get; set; }
        public Nullable<decimal> china { get; set; }
        public Nullable<decimal> nobrow { get; set; }
        public Nullable<decimal> query { get; set; }
        public Nullable<decimal> @readonly { get; set; }
        public Nullable<decimal> noedit { get; set; }
        public Nullable<decimal> required { get; set; }
        public Nullable<decimal> querytype { get; set; }
        public string fortable { get; set; }
        public string forshowf { get; set; }
        public string forrefrf { get; set; }
        public string forcomk { get; set; }
        public string forcomfk { get; set; }
        public string forkey { get; set; }
        public Nullable<decimal> forcomkcnt { get; set; }
        public string forfield { get; set; }
        public string forpwhere { get; set; }
        public Nullable<decimal> forcanexit { get; set; }
        public string combo { get; set; }
        public string options { get; set; }
        public string sumfield1 { get; set; }
        public string sumvalid1 { get; set; }
        public string sumfield2 { get; set; }
        public string sumvalid2 { get; set; }
        public string replfield { get; set; }
        public string replexpr { get; set; }
        public string tiptext { get; set; }
        public string showvalid { get; set; }
        public string enablevalid { get; set; }
        public Nullable<decimal> showquery { get; set; }
        public Nullable<decimal> mainfield { get; set; }
        public Nullable<decimal> controltype { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
