//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class takestock
    {
        public string tt_partno { get; set; }
        public string tt_cupdno { get; set; }
        public string tt_spec { get; set; }
        public string tt_loc1 { get; set; }
        public string tt_loc2 { get; set; }
        public string tt_loc3 { get; set; }
        public Nullable<decimal> tt_stock { get; set; }
        public Nullable<decimal> tt_adjust { get; set; }
        public Nullable<decimal> tt_nstock { get; set; }
        public Nullable<decimal> tt_uprice { get; set; }
        public string tt_dpno { get; set; }
        public string tt_emno { get; set; }
        public Nullable<System.DateTime> tt_cdate { get; set; }
        public Nullable<int> tt_post { get; set; }
        public Nullable<System.DateTime> tt_postdate { get; set; }
        public int tt_dsn { get; set; }
        public string tt_mykno { get; set; }
        public decimal tt_kind { get; set; }
    }
}
