//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tourism_Fee
    {
        public string tmf_year { get; set; }
        public string tmf_no { get; set; }
        public string tmf_FeeNo { get; set; }
        public decimal tmf_item01 { get; set; }
        public decimal tmf_item02 { get; set; }
        public decimal tmf_item03 { get; set; }
        public decimal tmf_item04 { get; set; }
        public decimal tmf_item05 { get; set; }
        public decimal tmf_yn01 { get; set; }
        public decimal tmf_yn02 { get; set; }
        public decimal tmf_yn03 { get; set; }
        public decimal tmf_yn04 { get; set; }
        public decimal tmf_yn05 { get; set; }
        public int tmf_ageS { get; set; }
        public int tmf_ageE { get; set; }
        public string tmf_memo { get; set; }
        public int tmf_fee { get; set; }
        public int tmf_FinalFee { get; set; }
    }
}
