//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tourism_Subsidy
    {
        public string tmy_JobNo { get; set; }
        public int tmy_kind { get; set; }
        public string tmy_emno { get; set; }
        public string tmy_cname { get; set; }
        public string tmy_dpno { get; set; }
        public string tmy_dpname { get; set; }
        public string tmy_TourName { get; set; }
        public int tmy_amt1 { get; set; }
        public int tmy_amt2 { get; set; }
        public int tmy_amt3 { get; set; }
        public int tmy_amt4 { get; set; }
        public int tmy_amt5 { get; set; }
        public string tmy_Y { get; set; }
        public string tmy_N { get; set; }
        public string tmy_NotMet { get; set; }
        public string tmy_memo { get; set; }
        public Nullable<System.DateTime> tmy_cdate { get; set; }
        public string tmy_cemno { get; set; }
    }
}
