//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tourism
    {
        public string tm_year { get; set; }
        public string tm_no { get; set; }
        public string tm_content1 { get; set; }
        public string tm_content2 { get; set; }
        public Nullable<System.DateTime> tm_sdate { get; set; }
        public Nullable<System.DateTime> tm_edate { get; set; }
        public string tm_emno { get; set; }
        public string tm_cemno { get; set; }
        public Nullable<System.DateTime> tm_cdate { get; set; }
        public int tm_group { get; set; }
        public decimal tm_yn { get; set; }
        public Nullable<System.DateTime> tm_SignSdate { get; set; }
        public Nullable<System.DateTime> tm_SignEdate { get; set; }
        public int tm_para { get; set; }
        public int tm_limit { get; set; }
    }
}
