//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainApply
    {
        public string ta_no { get; set; }
        public string ta_train { get; set; }
        public Nullable<System.DateTime> ta_sdate { get; set; }
        public Nullable<System.DateTime> ta_edate { get; set; }
        public Nullable<decimal> ta_hour { get; set; }
        public string ta_unit { get; set; }
        public string ta_temno { get; set; }
        public string ta_teacher { get; set; }
        public Nullable<decimal> ta_feetype { get; set; }
        public string ta_content { get; set; }
        public string ta_reason { get; set; }
        public string ta_dpno { get; set; }
        public string ta_dpname { get; set; }
        public string ta_emno { get; set; }
        public string ta_emcname { get; set; }
        public string ta_rmid { get; set; }
        public string ta_rmname { get; set; }
        public decimal ta_post { get; set; }
        public decimal ta_close { get; set; }
        public decimal ta_kind { get; set; }
        public Nullable<System.DateTime> ta_sdate1 { get; set; }
        public Nullable<System.DateTime> ta_edate1 { get; set; }
        public decimal ta_check { get; set; }
    }
}
