//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainApply_Member
    {
        public string tm_no { get; set; }
        public string tm_emno { get; set; }
        public string tm_cname { get; set; }
        public string tm_dpno { get; set; }
        public string tm_31 { get; set; }
        public string tm_license { get; set; }
        public decimal tm_A { get; set; }
        public decimal tm_B { get; set; }
        public decimal tm_C { get; set; }
        public decimal tm_D { get; set; }
        public decimal tm_OK { get; set; }
        public string tm_reason { get; set; }
        public decimal tm_fees { get; set; }
        public decimal tm_hour { get; set; }
        public decimal tm_score { get; set; }
    }
}
