//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripApply
    {
        public string ty_no { get; set; }
        public string ty_place { get; set; }
        public string ty_emno { get; set; }
        public string ty_name { get; set; }
        public string ty_dpno { get; set; }
        public string ty_dpname { get; set; }
        public System.DateTime ty_date1 { get; set; }
        public System.DateTime ty_date2 { get; set; }
        public string ty_subject { get; set; }
        public string ty_content { get; set; }
        public string ty_cuno { get; set; }
        public string ty_cuname { get; set; }
        public decimal ty_yn { get; set; }
        public decimal ty_print { get; set; }
        public string ty_cemno { get; set; }
        public decimal ty_salYN { get; set; }
        public Nullable<System.DateTime> ty_date3 { get; set; }
        public Nullable<System.DateTime> ty_date4 { get; set; }
        public Nullable<decimal> ty_meetNo { get; set; }
        public string ty_meetName { get; set; }
        public Nullable<decimal> ty_meetNo1 { get; set; }
        public string ty_meetName1 { get; set; }
        public string ty_meetemno { get; set; }
        public string ty_meetemno1 { get; set; }
        public string ty_meetemnoB { get; set; }
        public string ty_meetemno1B { get; set; }
        public string ty_agent { get; set; }
        public string ty_cuno1 { get; set; }
        public string ty_cuname1 { get; set; }
        public string ty_cuno2 { get; set; }
        public string ty_cuname2 { get; set; }
        public string ty_cuno3 { get; set; }
        public string ty_cuname3 { get; set; }
        public string ty_cuno4 { get; set; }
        public string ty_cuname4 { get; set; }
        public string ty_cuno5 { get; set; }
        public string ty_cuname5 { get; set; }
    }
}
