//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripStd
    {
        public decimal td_seqno { get; set; }
        public string td_ceno { get; set; }
        public decimal td_sub1 { get; set; }
        public decimal td_sub2 { get; set; }
        public decimal td_sub3 { get; set; }
        public decimal td_sub4 { get; set; }
        public decimal td_sub5 { get; set; }
        public decimal td_sub6 { get; set; }
        public decimal td_sub7 { get; set; }
        public decimal td_yn1 { get; set; }
        public decimal td_yn2 { get; set; }
        public decimal td_yn3 { get; set; }
        public decimal td_yn4 { get; set; }
        public decimal td_yn5 { get; set; }
        public decimal td_yn6 { get; set; }
        public decimal td_yn7 { get; set; }
        public decimal td_car { get; set; }
        public decimal td_motor { get; set; }
        public decimal td_out1 { get; set; }
        public decimal td_out2 { get; set; }
        public decimal td_out3 { get; set; }
        public decimal td_out4 { get; set; }
    }
}
