//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripReport
    {
        public string tt_no { get; set; }
        public System.DateTime tt_date1 { get; set; }
        public System.DateTime tt_date2 { get; set; }
        public decimal tt_caryn { get; set; }
        public string tt_carno { get; set; }
        public Nullable<decimal> tt_trip1 { get; set; }
        public Nullable<decimal> tt_trip2 { get; set; }
        public Nullable<decimal> tt_trip { get; set; }
        public decimal tt_tripsub { get; set; }
        public decimal tt_parksub { get; set; }
        public string tt_taxi { get; set; }
        public decimal tt_taxisub { get; set; }
        public decimal tt_livesub { get; set; }
        public decimal tt_meal1 { get; set; }
        public decimal tt_meal2 { get; set; }
        public decimal tt_meal3 { get; set; }
        public decimal tt_mealsub { get; set; }
        public decimal tt_othersub { get; set; }
        public decimal tt_socialsub { get; set; }
        public decimal tt_totalsub { get; set; }
        public string tt_report { get; set; }
        public decimal tt_yn { get; set; }
        public decimal tt_verify { get; set; }
        public string tt_vername { get; set; }
        public Nullable<System.DateTime> tt_vertime { get; set; }
        public decimal tt_verify1 { get; set; }
        public string tt_vername1 { get; set; }
        public Nullable<System.DateTime> tt_vertime1 { get; set; }
        public decimal tt_close { get; set; }
        public decimal tt_disc { get; set; }
        public decimal tt_post { get; set; }
        public decimal tt_carverify { get; set; }
        public decimal tt_outsub { get; set; }
        public string tt_curr { get; set; }
        public Nullable<decimal> tt_prepay { get; set; }
        public decimal tt_exrate { get; set; }
        public decimal tt_prepaysub { get; set; }
        public decimal tt_OilTrip { get; set; }
        public decimal tt_OilCnt { get; set; }
        public decimal tt_OilCharge { get; set; }
        public string tt_OilInv { get; set; }
        public Nullable<System.DateTime> tt_OilDate { get; set; }
        public Nullable<decimal> tt_OilCharge1 { get; set; }
        public Nullable<decimal> tt_OilCharge2 { get; set; }
        public Nullable<decimal> tt_park { get; set; }
        public Nullable<decimal> tt_carpass { get; set; }
        public Nullable<decimal> tt_prepayB { get; set; }
        public string tt_curr2 { get; set; }
        public Nullable<decimal> tt_prepay2 { get; set; }
        public Nullable<decimal> tt_prepayB2 { get; set; }
        public Nullable<decimal> tt_exrate2 { get; set; }
        public Nullable<decimal> tt_prepaysub2 { get; set; }
        public string tt_curr3 { get; set; }
        public Nullable<decimal> tt_prepay3 { get; set; }
        public Nullable<decimal> tt_prepayB3 { get; set; }
        public Nullable<decimal> tt_exrate3 { get; set; }
        public Nullable<decimal> tt_prepaysub3 { get; set; }
        public Nullable<int> tt_finanical { get; set; }
    }
}
