//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unipric
    {
        public string up_no { get; set; }
        public string up_cuupno { get; set; }
        public string up_mykno { get; set; }
        public Nullable<decimal> up_amt { get; set; }
        public Nullable<System.DateTime> up_date { get; set; }
        public string up_desc { get; set; }
        public Nullable<decimal> up_std { get; set; }
        public string up_cuno { get; set; }
        public string up_cuupno1 { get; set; }
    }
}
