//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unsales
    {
        public string us_no { get; set; }
        public string us_spec { get; set; }
        public Nullable<decimal> us_qty { get; set; }
        public Nullable<decimal> us_ntprice { get; set; }
        public Nullable<System.DateTime> us_deldate { get; set; }
        public string us_dpno { get; set; }
        public string us_curr { get; set; }
        public string us_boxno { get; set; }
        public Nullable<decimal> us_uprice { get; set; }
        public string us_label { get; set; }
        public Nullable<decimal> us_iqty { get; set; }
        public Nullable<decimal> us_oqty { get; set; }
        public string us_ym { get; set; }
        public string us_loc { get; set; }
    }
}
