//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unus
    {
        public string un_suno { get; set; }
        public string un_ym { get; set; }
        public string un_puno2 { get; set; }
        public string un_setno { get; set; }
        public string un_mtno { get; set; }
        public string un_spec { get; set; }
        public Nullable<decimal> un_width { get; set; }
        public Nullable<decimal> un_long { get; set; }
        public Nullable<decimal> un_chkamt { get; set; }
        public Nullable<System.DateTime> un_date { get; set; }
        public Nullable<System.DateTime> un_date1 { get; set; }
        public Nullable<decimal> un_delday { get; set; }
        public string un_reason { get; set; }
        public string un_chno { get; set; }
        public Nullable<decimal> un_qures { get; set; }
        public Nullable<decimal> un_buyamt { get; set; }
        public Nullable<decimal> un_padd { get; set; }
        public Nullable<decimal> un_unqu { get; set; }
        public string un_puno { get; set; }
        public decimal un_seqno { get; set; }
    }
}
