//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public string id { get; set; }
        public string name { get; set; }
        public string pword { get; set; }
        public string grph_id { get; set; }
        public string dept_name { get; set; }
        public string title { get; set; }
        public byte[] photo { get; set; }
        public string starts { get; set; }
        public Nullable<decimal> usr_10 { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
