//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AllEmployee
    {
        public string em_no { get; set; }
        public string em_cname { get; set; }
        public string em_id { get; set; }
        public string em_addr1 { get; set; }
        public Nullable<System.DateTime> em_20 { get; set; }
        public Nullable<System.DateTime> em_21 { get; set; }
        public string em_dpno { get; set; }
        public Nullable<decimal> em_79 { get; set; }
        public decimal em_85 { get; set; }
    }
}
