//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_badpro_MBO
    {
        public string bo_yymm { get; set; }
        public decimal bo_kind { get; set; }
        public string bo_no { get; set; }
        public Nullable<decimal> bo_lost { get; set; }
        public string bo_dpno1 { get; set; }
        public Nullable<decimal> bo_dpreat1 { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    }
}
