//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_basb07_sub1
    {
        public string pb_seqno { get; set; }
        public string bk_setno { get; set; }
        public string bk_tbno { get; set; }
        public string tb_name { get; set; }
        public decimal bk_item { get; set; }
        public decimal bk_kind { get; set; }
        public string KnifeItem { get; set; }
        public string ShareKind { get; set; }
        public string bk_setno1 { get; set; }
        public string mb_loc { get; set; }
    }
}
