//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_bommo
    {
        public System.DateTime mo_cdate { get; set; }
        public string mo_mkno { get; set; }
        public string mo_setno { get; set; }
        public System.DateTime mo_date { get; set; }
        public Nullable<decimal> mo_qty { get; set; }
        public Nullable<decimal> mo_mpaper { get; set; }
        public decimal mo_stdcarqty { get; set; }
        public Nullable<decimal> mo_yn { get; set; }
        public string mo_mpno { get; set; }
        public decimal mo_jit { get; set; }
        public Nullable<decimal> mo_post { get; set; }
        public Nullable<decimal> mo_close { get; set; }
        public Nullable<System.DateTime> mo_schdate1 { get; set; }
        public Nullable<System.DateTime> mo_schdate2 { get; set; }
        public Nullable<System.DateTime> mo_indate { get; set; }
        public Nullable<System.DateTime> mo_extradate { get; set; }
        public string SNO { get; set; }
        public decimal mo_kind { get; set; }
        public string mo_enno { get; set; }
        public decimal mo_ssqty { get; set; }
        public string mo_mtno1 { get; set; }
        public decimal mo_plen { get; set; }
        public decimal mo_pwid { get; set; }
        public string mo_dpno { get; set; }
        public string mo_DelReason { get; set; }
        public string mo_memo1 { get; set; }
        public string mo_memo2 { get; set; }
    }
}
