//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Bommo_TimeSheet
    {
        public System.DateTime mo_cdate { get; set; }
        public string mo_mkno { get; set; }
        public string mo_setno { get; set; }
        public System.DateTime mo_date { get; set; }
        public string mo_mpno { get; set; }
        public string pb_seqno { get; set; }
        public string pb_tbno { get; set; }
        public string tb_name { get; set; }
        public Nullable<System.DateTime> The_PDate { get; set; }
        public Nullable<System.DateTime> The_PreDate { get; set; }
        public Nullable<System.DateTime> The_UDate { get; set; }
        public string The_delay { get; set; }
        public string The_memo { get; set; }
        public string mo_dpno { get; set; }
        public string mo_SuppDpno { get; set; }
        public Nullable<System.DateTime> time_Receive { get; set; }
        public Nullable<System.DateTime> time_Start { get; set; }
        public Nullable<System.DateTime> time_Fin { get; set; }
        public string emno_Receive { get; set; }
        public string emno_Start { get; set; }
        public string emno_Fin { get; set; }
    }
}
