//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_bupf02_01
    {
        public string bh_puno { get; set; }
        public Nullable<decimal> bh_way { get; set; }
        public string bh_cuno { get; set; }
        public string bh_mnname { get; set; }
        public string bh_brand { get; set; }
        public string bh_cpro { get; set; }
        public string bh_draft { get; set; }
        public string bh_disk { get; set; }
        public string bh_oldon { get; set; }
        public string bh_film { get; set; }
        public string bh_email { get; set; }
        public Nullable<System.DateTime> bh_ddate { get; set; }
        public Nullable<decimal> bh_color { get; set; }
        public string bh_mnno { get; set; }
        public Nullable<decimal> bh_fflow { get; set; }
        public Nullable<decimal> bh_bflow { get; set; }
        public Nullable<decimal> bh_dflow { get; set; }
        public Nullable<decimal> bh_cflow { get; set; }
        public Nullable<decimal> bh_sflow { get; set; }
        public Nullable<decimal> bh_pflow { get; set; }
        public Nullable<decimal> bh_kflow { get; set; }
        public string em_cname { get; set; }
        public string pr_cname { get; set; }
        public string bh_emno { get; set; }
        public string cu_sname { get; set; }
        public Nullable<System.DateTime> bh_pdate { get; set; }
        public string cu_no { get; set; }
        public string pr_ename { get; set; }
        public string bh_dpno { get; set; }
        public decimal bh_jit { get; set; }
        public string bh_memo { get; set; }
        public string bh_chalf { get; set; }
        public Nullable<decimal> bh_long { get; set; }
        public Nullable<decimal> bh_width { get; set; }
        public Nullable<decimal> bh_colnum { get; set; }
        public decimal bh_filmnum { get; set; }
        public string bh_wno { get; set; }
        public decimal bh_20 { get; set; }
        public decimal bh_nqty { get; set; }
        public string bh_metno1 { get; set; }
        public string mt_spec1 { get; set; }
        public string p_unit { get; set; }
        public string bh_metno2 { get; set; }
        public string mt_spec2 { get; set; }
        public string bh_metno3 { get; set; }
        public string mt_spec3 { get; set; }
        public string bh_metno4 { get; set; }
        public string mt_spec4 { get; set; }
        public string bh_metno5 { get; set; }
        public string mt_spec5 { get; set; }
        public string p_unit2 { get; set; }
        public string bh_metno6 { get; set; }
        public string mt_spec6 { get; set; }
        public string p_unit3 { get; set; }
    }
}
