//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_bulm06_01
    {
        public string bh_cuno { get; set; }
        public string cu_sname { get; set; }
        public string bh_puno { get; set; }
        public Nullable<decimal> bh_colnum { get; set; }
        public string bh_spno { get; set; }
        public Nullable<decimal> bh_reafee { get; set; }
        public Nullable<decimal> bh_expfee { get; set; }
        public Nullable<System.DateTime> bh_date3 { get; set; }
        public string bh_brand { get; set; }
        public Nullable<decimal> bh_keyin { get; set; }
        public string bh_dpno { get; set; }
        public Nullable<System.DateTime> bh_findate { get; set; }
        public Nullable<decimal> bh_dpnum { get; set; }
        public Nullable<decimal> bh_allnum { get; set; }
        public Nullable<decimal> bh_paste { get; set; }
        public Nullable<decimal> bh_psqu { get; set; }
        public string pr_ename { get; set; }
    }
}
