//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_cabs17
    {
        public string er_yymm { get; set; }
        public string em_dpno { get; set; }
        public string er_emno { get; set; }
        public string em_cname { get; set; }
        public Nullable<decimal> er_tothour { get; set; }
        public decimal er_hour { get; set; }
        public Nullable<double> er_rate1 { get; set; }
        public decimal vm_hour { get; set; }
        public Nullable<double> er_rate2 { get; set; }
        public Nullable<decimal> my_inftot { get; set; }
        public Nullable<decimal> my_taxot { get; set; }
        public Nullable<double> er_rate3 { get; set; }
        public Nullable<decimal> em_85 { get; set; }
        public string em_work { get; set; }
    }
}
