//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_card
    {
        public System.DateTime ca_date { get; set; }
        public string ca_emno { get; set; }
        public string ca_seca { get; set; }
        public string ca_secb { get; set; }
        public string ca_secc { get; set; }
        public string ca_secd { get; set; }
        public Nullable<decimal> Ta { get; set; }
        public Nullable<decimal> Tb { get; set; }
        public Nullable<decimal> Tc { get; set; }
        public Nullable<decimal> Td { get; set; }
        public Nullable<decimal> NHour { get; set; }
        public Nullable<decimal> OHour { get; set; }
        public Nullable<decimal> WorkHour { get; set; }
        public decimal er_hour_Real { get; set; }
        public decimal er_hour_std { get; set; }
    }
}
