//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_cabs48
    {
        public System.DateTime moc_date { get; set; }
        public string moc_mkno { get; set; }
        public string moc_setno { get; set; }
        public string moc_mtno { get; set; }
        public string mt_spec { get; set; }
        public decimal moc_long { get; set; }
        public decimal moc_width { get; set; }
        public decimal moc_mpaper { get; set; }
        public Nullable<decimal> The_Area1 { get; set; }
        public string rd_no { get; set; }
        public Nullable<System.DateTime> rd_date { get; set; }
        public Nullable<decimal> rd_long { get; set; }
        public Nullable<decimal> rd_width { get; set; }
        public Nullable<decimal> rd_qty { get; set; }
        public Nullable<decimal> The_Area2 { get; set; }
        public string moc_dpno { get; set; }
        public string moc_cuno { get; set; }
        public string moc_prno { get; set; }
        public decimal moc_mono { get; set; }
        public int DataType { get; set; }
    }
}
