//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_emqp04
    {
        public string dp_name { get; set; }
        public string em_cname { get; set; }
        public string yp_ym1y { get; set; }
        public string yp_ym2y { get; set; }
        public string yp_ym3y { get; set; }
        public string yp_ym4y { get; set; }
        public string yp_ym5y { get; set; }
        public string yp_ym6y { get; set; }
        public string yp_ym7y { get; set; }
        public string yp_ym8y { get; set; }
        public string yp_ym9y { get; set; }
        public string yp_ym10y { get; set; }
        public string yp_ym11y { get; set; }
        public string yp_ym12y { get; set; }
        public string yp_dpno { get; set; }
        public string yp_emno { get; set; }
        public string yp_ym1 { get; set; }
        public string yp_ym2 { get; set; }
        public string yp_ym3 { get; set; }
        public string yp_ym4 { get; set; }
        public string yp_ym5 { get; set; }
        public string yp_ym6 { get; set; }
        public string yp_ym7 { get; set; }
        public string yp_ym8 { get; set; }
        public string yp_ym9 { get; set; }
        public string yp_ym10 { get; set; }
        public string yp_ym11 { get; set; }
        public string yp_ym12 { get; set; }
        public Nullable<decimal> yp_amt1 { get; set; }
        public Nullable<decimal> yp_amt2 { get; set; }
        public Nullable<decimal> yp_amt3 { get; set; }
        public Nullable<decimal> yp_amt4 { get; set; }
        public Nullable<decimal> yp_amt5 { get; set; }
        public Nullable<decimal> yp_amt6 { get; set; }
        public Nullable<decimal> yp_amt7 { get; set; }
        public Nullable<decimal> yp_amt8 { get; set; }
        public Nullable<decimal> yp_amt9 { get; set; }
        public Nullable<decimal> yp_amt10 { get; set; }
        public Nullable<decimal> yp_amt11 { get; set; }
        public Nullable<decimal> yp_amt12 { get; set; }
        public Nullable<decimal> yp_gcamt1 { get; set; }
        public Nullable<decimal> yp_gcamt2 { get; set; }
        public Nullable<decimal> yp_gcamt3 { get; set; }
        public Nullable<decimal> yp_gcamt4 { get; set; }
        public Nullable<decimal> yp_gcamt5 { get; set; }
        public Nullable<decimal> yp_gcamt6 { get; set; }
        public Nullable<decimal> yp_gcamt7 { get; set; }
        public Nullable<decimal> yp_gcamt8 { get; set; }
        public Nullable<decimal> yp_gcamt9 { get; set; }
        public Nullable<decimal> yp_gcamt10 { get; set; }
        public Nullable<decimal> yp_gcamt11 { get; set; }
        public Nullable<decimal> yp_gcamt12 { get; set; }
        public Nullable<decimal> yp_whour1 { get; set; }
        public Nullable<decimal> yp_whour2 { get; set; }
        public Nullable<decimal> yp_whour3 { get; set; }
        public Nullable<decimal> yp_whour4 { get; set; }
        public Nullable<decimal> yp_whour5 { get; set; }
        public Nullable<decimal> yp_whour6 { get; set; }
        public Nullable<decimal> yp_whour7 { get; set; }
        public Nullable<decimal> yp_whour8 { get; set; }
        public Nullable<decimal> yp_whour9 { get; set; }
        public Nullable<decimal> yp_whour10 { get; set; }
        public Nullable<decimal> yp_whour11 { get; set; }
        public Nullable<decimal> yp_whour12 { get; set; }
        public Nullable<decimal> yp_avcamt1 { get; set; }
        public Nullable<decimal> yp_avcamt2 { get; set; }
        public Nullable<decimal> yp_avcamt3 { get; set; }
        public Nullable<decimal> yp_avcamt4 { get; set; }
        public Nullable<decimal> yp_avcamt5 { get; set; }
        public Nullable<decimal> yp_avcamt6 { get; set; }
        public Nullable<decimal> yp_avcamt7 { get; set; }
        public Nullable<decimal> yp_avcamt8 { get; set; }
        public Nullable<decimal> yp_avcamt9 { get; set; }
        public Nullable<decimal> yp_avcamt10 { get; set; }
        public Nullable<decimal> yp_avcamt11 { get; set; }
        public Nullable<decimal> yp_avcamt12 { get; set; }
        public string em_no { get; set; }
        public string dp_no { get; set; }
    }
}
