//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_employee
    {
        public string em_no { get; set; }
        public string em_cname { get; set; }
        public Nullable<decimal> em_sex { get; set; }
        public string em_id { get; set; }
        public Nullable<System.DateTime> em_birth { get; set; }
        public string em_60 { get; set; }
        public string em_dpno { get; set; }
        public Nullable<decimal> em_11 { get; set; }
        public Nullable<decimal> em_12 { get; set; }
        public Nullable<decimal> em_14 { get; set; }
        public Nullable<decimal> em_41 { get; set; }
        public string em_31 { get; set; }
        public string em_61 { get; set; }
        public Nullable<decimal> em_30 { get; set; }
        public Nullable<System.DateTime> em_20 { get; set; }
        public Nullable<System.DateTime> em_21 { get; set; }
        public Nullable<System.DateTime> em_22 { get; set; }
        public Nullable<System.DateTime> em_24 { get; set; }
        public Nullable<decimal> em_13 { get; set; }
        public string em_62 { get; set; }
        public string em_63 { get; set; }
        public string em_addr1 { get; set; }
        public string em_addr2 { get; set; }
        public string em_44 { get; set; }
        public string em_64 { get; set; }
        public string em_65 { get; set; }
        public string em_43 { get; set; }
        public string em_66 { get; set; }
        public Nullable<System.DateTime> em_67 { get; set; }
        public Nullable<decimal> em_68 { get; set; }
        public string em_69 { get; set; }
        public Nullable<decimal> em_70 { get; set; }
        public Nullable<decimal> em_71 { get; set; }
        public Nullable<decimal> em_73 { get; set; }
        public string em_tel2 { get; set; }
        public string em_ename { get; set; }
        public Nullable<decimal> em_74 { get; set; }
        public Nullable<System.DateTime> em_75 { get; set; }
        public Nullable<decimal> em_kind { get; set; }
        public string em_cono2 { get; set; }
        public string em_csno { get; set; }
        public string em_tel1 { get; set; }
        public string em_bcc { get; set; }
        public string em_mobil { get; set; }
        public string em_zip1 { get; set; }
        public string em_zip2 { get; set; }
        public Nullable<decimal> em_15 { get; set; }
        public Nullable<decimal> em_16 { get; set; }
        public string em_17 { get; set; }
        public Nullable<decimal> em_18 { get; set; }
        public Nullable<decimal> em_19 { get; set; }
        public Nullable<System.DateTime> em_25 { get; set; }
        public string em_26 { get; set; }
        public Nullable<System.DateTime> em_23 { get; set; }
        public string em_27 { get; set; }
        public string em_32 { get; set; }
        public string em_33 { get; set; }
        public string em_34 { get; set; }
        public Nullable<decimal> em_35 { get; set; }
        public Nullable<decimal> em_36 { get; set; }
        public string em_37 { get; set; }
        public string em_38 { get; set; }
        public Nullable<decimal> em_39 { get; set; }
        public Nullable<decimal> em_40 { get; set; }
        public string em_42 { get; set; }
        public string em_45 { get; set; }
        public string em_46 { get; set; }
        public string em_47 { get; set; }
        public string em_48 { get; set; }
        public Nullable<decimal> em_49 { get; set; }
        public string em_50 { get; set; }
        public string em_51 { get; set; }
        public Nullable<decimal> em_52 { get; set; }
        public string em_53 { get; set; }
        public string em_54 { get; set; }
        public string em_55 { get; set; }
        public string em_56 { get; set; }
        public string em_57 { get; set; }
        public string em_58 { get; set; }
        public Nullable<decimal> em_59 { get; set; }
        public byte[] em_photo { get; set; }
        public Nullable<System.DateTime> em_create { get; set; }
        public string em_memo { get; set; }
        public string em_loginid { get; set; }
        public string em_loginpw { get; set; }
        public string em_mainrole { get; set; }
        public string em_role1 { get; set; }
        public string em_role2 { get; set; }
        public string em_role3 { get; set; }
        public string em_role4 { get; set; }
        public Nullable<System.DateTime> em_76 { get; set; }
        public Nullable<System.DateTime> em_77 { get; set; }
        public Nullable<decimal> em_78 { get; set; }
        public Nullable<decimal> em_79 { get; set; }
        public Nullable<decimal> em_81 { get; set; }
        public Nullable<decimal> em_82 { get; set; }
        public Nullable<decimal> em_72 { get; set; }
        public string em_83 { get; set; }
        public string em_84 { get; set; }
        public Nullable<decimal> em_85 { get; set; }
        public string em_passwd { get; set; }
        public Nullable<System.DateTime> em_90 { get; set; }
        public Nullable<System.DateTime> em_91 { get; set; }
        public Nullable<System.DateTime> em_92 { get; set; }
        public Nullable<decimal> em_86 { get; set; }
        public decimal em_93 { get; set; }
        public string em_94 { get; set; }
        public decimal em_95 { get; set; }
        public decimal em_96 { get; set; }
        public decimal em_97 { get; set; }
        public decimal em_98 { get; set; }
        public decimal em_99 { get; set; }
        public string em_work { get; set; }
        public decimal em_98T { get; set; }
        public string em_100 { get; set; }
        public decimal em_101 { get; set; }
    }
}
