//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_emqp02_13
    {
        public string ma_emno { get; set; }
        public string em_cname { get; set; }
        public string ma_dpno { get; set; }
        public string dp_name { get; set; }
        public System.DateTime ma_date { get; set; }
        public Nullable<decimal> ma_ptime { get; set; }
        public Nullable<decimal> ma_mtime { get; set; }
        public Nullable<decimal> ma_famt { get; set; }
        public Nullable<decimal> ma_caramt { get; set; }
        public Nullable<decimal> ma_tcamt { get; set; }
        public Nullable<decimal> ma_waamt { get; set; }
        public decimal sm_rlhour { get; set; }
        public double agamt { get; set; }
        public decimal em_85 { get; set; }
        public string ws_machine { get; set; }
        public decimal ma_PowerAmt { get; set; }
        public decimal ph_hour { get; set; }
        public Nullable<decimal> ep_stdefc { get; set; }
    }
}
