//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_emqp03_13
    {
        public string yp_ym { get; set; }
        public string yp_emno { get; set; }
        public string em_cname { get; set; }
        public string yp_dpno { get; set; }
        public string dp_name { get; set; }
        public string yp_ws { get; set; }
        public Nullable<decimal> yp_pmtime { get; set; }
        public Nullable<decimal> yp_caramt { get; set; }
        public Nullable<decimal> yp_tcamt { get; set; }
        public Nullable<decimal> yp_gcamt { get; set; }
        public Nullable<decimal> yp_whour { get; set; }
        public Nullable<decimal> yp_avcamt { get; set; }
    }
}
