//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_material
    {
        public string mt_no { get; set; }
        public string mt_spec { get; set; }
        public string mt_unit { get; set; }
        public string mt_unit1 { get; set; }
        public decimal mt_long { get; set; }
        public decimal mt_width { get; set; }
        public Nullable<decimal> mt_cost { get; set; }
        public string The_prno { get; set; }
        public string The_Kind { get; set; }
    }
}
