//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_moqp01_01
    {
        public string b1_desc { get; set; }
        public Nullable<System.DateTime> b1_date { get; set; }
        public Nullable<decimal> b1_stdamt { get; set; }
        public string b2_setno { get; set; }
        public string b2_cusetno { get; set; }
        public string b2_desc { get; set; }
        public Nullable<decimal> b2_qty { get; set; }
        public string b3_upno { get; set; }
        public string b3_cuupno { get; set; }
        public string b3_desc { get; set; }
        public Nullable<decimal> b3_qty { get; set; }
        public Nullable<decimal> b3_amt { get; set; }
        public string b1_carno { get; set; }
        public string b1_cucar { get; set; }
        public string b1_mykname { get; set; }
        public string b3_mykname { get; set; }
        public string cu_sname { get; set; }
        public string cp_cuno { get; set; }
        public string b1_color { get; set; }
    }
}
