//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_modbase_pay_3
    {
        public string b2_setno { get; set; }
        public string b2_desc { get; set; }
        public decimal mb_item { get; set; }
        public string mb_loc { get; set; }
        public Nullable<decimal> mb_qty { get; set; }
        public Nullable<System.DateTime> mb_date2 { get; set; }
        public Nullable<System.DateTime> mb_date { get; set; }
        public string mb_setno1 { get; set; }
        public Nullable<decimal> mb_share { get; set; }
    }
}
