//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_mpgoa_Machine
    {
        public string mp_ym { get; set; }
        public string dpno { get; set; }
        public Nullable<decimal> CntM { get; set; }
        public Nullable<decimal> mp_day { get; set; }
    }
}
