//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_nesb19
    {
        public string wt_emno { get; set; }
        public string em_cname { get; set; }
        public System.DateTime wt_enddate { get; set; }
        public int DayCount1 { get; set; }
        public int DayCount2 { get; set; }
        public int DayCount3 { get; set; }
        public int DayCount4 { get; set; }
        public decimal DayCount6 { get; set; }
        public decimal DayCount7 { get; set; }
        public decimal DayCount9 { get; set; }
        public int DayCount11 { get; set; }
        public int DayCount21 { get; set; }
        public int DayCount31 { get; set; }
        public int DayCount41 { get; set; }
        public int DayCount61 { get; set; }
        public int DayCount71 { get; set; }
        public int DayCount91 { get; set; }
        public int For75 { get; set; }
        public int For88 { get; set; }
        public int For92 { get; set; }
        public int For130 { get; set; }
        public int ForBack { get; set; }
    }
}
