//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pdtbas_TimeSet
    {
        public string pb_no { get; set; }
        public string pb_name { get; set; }
        public string pb_seqno { get; set; }
        public string pb_tbno { get; set; }
        public string tb_name { get; set; }
        public Nullable<decimal> tb_sche { get; set; }
        public decimal tb_feedback { get; set; }
        public string The_type { get; set; }
        public decimal The_Time { get; set; }
        public Nullable<decimal> The_TimeGT { get; set; }
    }
}
