//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_perb34_01
    {
        public string em_no { get; set; }
        public string em_cname { get; set; }
        public string dp_no { get; set; }
        public string dp_name { get; set; }
        public Nullable<decimal> em_68 { get; set; }
        public Nullable<decimal> er_tothour { get; set; }
        public Nullable<decimal> er_bashour { get; set; }
        public string er_yymm { get; set; }
        public Nullable<decimal> er_ehour { get; set; }
    }
}
