//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PERB66_01
    {
        public string va_yy { get; set; }
        public string fn_no { get; set; }
        public string fn_cname { get; set; }
        public Nullable<System.DateTime> fn_20 { get; set; }
        public Nullable<decimal> va_111 { get; set; }
        public Nullable<decimal> va_112 { get; set; }
        public Nullable<decimal> va_113 { get; set; }
        public Nullable<decimal> va_114 { get; set; }
        public Nullable<decimal> va_115 { get; set; }
        public string va_12 { get; set; }
        public string dp_no { get; set; }
        public string dp_name { get; set; }
    }
}
