//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PERB45_01
    {
        public System.DateTime ca_date { get; set; }
        public string ca_seca { get; set; }
        public string ca_secb { get; set; }
        public string ca_secc { get; set; }
        public string ca_secd { get; set; }
        public string Realot1 { get; set; }
        public string ca_ot1 { get; set; }
        public string ca_ot2 { get; set; }
        public string ca_tmpno { get; set; }
        public Nullable<decimal> ca_meal { get; set; }
        public Nullable<decimal> ca_holiday { get; set; }
        public string ca_emno { get; set; }
        public string em_cname { get; set; }
        public string em_dpno { get; set; }
        public Nullable<decimal> OT1 { get; set; }
        public Nullable<decimal> OT2 { get; set; }
        public decimal ho_kind { get; set; }
    }
}
