//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PERB44_02
    {
        public string dp_name { get; set; }
        public string pt_no { get; set; }
        public string pt_cname { get; set; }
        public Nullable<System.DateTime> pt_birth { get; set; }
        public Nullable<decimal> pt_sex { get; set; }
        public string pt_id { get; set; }
        public Nullable<System.DateTime> pt_20 { get; set; }
        public Nullable<decimal> pt_30 { get; set; }
        public string pt_tel2 { get; set; }
        public Nullable<System.DateTime> pt_21 { get; set; }
        public Nullable<System.DateTime> pt_22 { get; set; }
        public string pt_dpno { get; set; }
        public string pt_work { get; set; }
        public Nullable<decimal> in_amt { get; set; }
        public string ce_name { get; set; }
        public Nullable<decimal> pt_working { get; set; }
    }
}
