//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PERB45_02
    {
        public System.DateTime ca_date { get; set; }
        public string ca_emno { get; set; }
        public Nullable<decimal> ho_kind { get; set; }
        public Nullable<decimal> TotalH { get; set; }
        public Nullable<decimal> P1 { get; set; }
        public Nullable<decimal> P2 { get; set; }
        public Nullable<decimal> P0r { get; set; }
        public Nullable<decimal> P1r { get; set; }
        public Nullable<decimal> P2r { get; set; }
        public Nullable<decimal> P0s { get; set; }
        public Nullable<decimal> P1s { get; set; }
        public Nullable<decimal> P2s { get; set; }
        public Nullable<decimal> P0w { get; set; }
        public Nullable<decimal> P1w { get; set; }
        public Nullable<decimal> P2w { get; set; }
    }
}
