//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PERB68_01
    {
        public System.DateTime cf_date { get; set; }
        public string cf_seca { get; set; }
        public string cf_secb { get; set; }
        public string cf_secc { get; set; }
        public string cf_secd { get; set; }
        public string Realot1 { get; set; }
        public string cf_ot1 { get; set; }
        public string cf_ot2 { get; set; }
        public string cf_tmpno { get; set; }
        public Nullable<decimal> cf_meal { get; set; }
        public Nullable<decimal> cf_holiday { get; set; }
        public string cf_emno { get; set; }
        public string fn_cname { get; set; }
        public string fn_dpno { get; set; }
        public Nullable<decimal> OT1 { get; set; }
        public Nullable<decimal> OT2 { get; set; }
        public Nullable<decimal> ho_kind { get; set; }
    }
}
