//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pocp02_01
    {
        public string woc_mkno { get; set; }
        public System.DateTime woc_modday { get; set; }
        public string woc_setno { get; set; }
        public decimal woc_qty { get; set; }
        public decimal woc_mpaper { get; set; }
        public System.DateTime woc_spdate { get; set; }
        public Nullable<decimal> woc_yn { get; set; }
        public Nullable<decimal> mo_mpaper { get; set; }
        public System.DateTime mo_date { get; set; }
        public Nullable<decimal> mo_yn { get; set; }
        public Nullable<decimal> mo_qty { get; set; }
    }
}
