//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pofn03_01
    {
        public System.DateTime pq_cudate { get; set; }
        public string pq_pdno { get; set; }
        public string pq_setno { get; set; }
        public string pq_inno { get; set; }
        public Nullable<decimal> pq_reqqty { get; set; }
        public string em_cname { get; set; }
        public Nullable<System.DateTime> pq_date { get; set; }
        public string pq_mkno { get; set; }
        public string pq_dpno { get; set; }
    }
}
