//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_poas05_01
    {
        public string WS_NAME { get; set; }
        public Nullable<decimal> BS_TIME { get; set; }
        public string MO_SETNO { get; set; }
        public string MO_MKNO { get; set; }
        public Nullable<decimal> MO_MPAPER { get; set; }
        public System.DateTime MO_DATE { get; set; }
        public Nullable<System.DateTime> MO_CDATE { get; set; }
        public string MO_MTNO1 { get; set; }
        public Nullable<decimal> LW_PCQTY { get; set; }
        public Nullable<decimal> LW_POST { get; set; }
        public string MT_SPEC { get; set; }
        public Nullable<decimal> MO_POST { get; set; }
        public Nullable<decimal> BH_COLNUM { get; set; }
        public string BH_PUNO { get; set; }
        public string MO_DPNO { get; set; }
    }
}
