//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_POEW18_02
    {
        public string em_no { get; set; }
        public string em_cname { get; set; }
        public string mo_mkno { get; set; }
        public string mo_setno { get; set; }
        public string mo_mpno { get; set; }
        public string pb_seqno { get; set; }
        public string pb_tbno { get; set; }
        public string tb_name { get; set; }
        public string ew_emno { get; set; }
        public Nullable<System.DateTime> ReachTime { get; set; }
        public string ew_memo { get; set; }
        public System.DateTime ErrorTime { get; set; }
        public string ErrorSRC { get; set; }
        public string loginCname { get; set; }
        public string The_duty { get; set; }
        public Nullable<System.DateTime> ForecastTime { get; set; }
        public string FeedbackMemo { get; set; }
        public Nullable<decimal> ew_seqno { get; set; }
    }
}
