//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sapr41_01
    {
        public string et_ym { get; set; }
        public string et_emno { get; set; }
        public string et_cname { get; set; }
        public string et_dpno { get; set; }
        public string et_dpname { get; set; }
        public string em_31 { get; set; }
        public string ce_name { get; set; }
        public Nullable<System.DateTime> em_21 { get; set; }
        public string pr_group { get; set; }
        public string GroupName { get; set; }
        public decimal by_ceno3 { get; set; }
        public Nullable<decimal> TotalRate { get; set; }
        public decimal pr_rate { get; set; }
        public Nullable<decimal> P1 { get; set; }
        public decimal GroupTotalRate { get; set; }
        public decimal GroupRate { get; set; }
        public decimal P2 { get; set; }
        public Nullable<decimal> SeniorityM { get; set; }
        public string NewFlag { get; set; }
        public int SaveFlag { get; set; }
        public int pd_share0 { get; set; }
        public int pr_award { get; set; }
        public Nullable<decimal> my_effsal { get; set; }
        public int Chk_Cnt { get; set; }
    }
}
