//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sapr68
    {
        public string tm_emno { get; set; }
        public string tm_cname { get; set; }
        public decimal tm_OK { get; set; }
        public decimal tm_score { get; set; }
        public string TDate { get; set; }
        public string ta_train { get; set; }
        public string TKind { get; set; }
    }
}
