//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sapr18_excel
    {
        public string mx_yymm { get; set; }
        public string mx_kind { get; set; }
        public string mx_emno { get; set; }
        public string em_cname { get; set; }
        public string dp_name { get; set; }
        public string mx_saltype { get; set; }
        public string em_sex { get; set; }
        public Nullable<decimal> mx_amt { get; set; }
        public Nullable<decimal> mx_amtt { get; set; }
        public Nullable<decimal> mx_amt1 { get; set; }
        public Nullable<decimal> mx_amt2 { get; set; }
        public Nullable<decimal> mx_tax { get; set; }
        public int me_explain { get; set; }
    }
}
