//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sapr54_01
    {
        public string et_ym { get; set; }
        public string et_emno { get; set; }
        public string et_cname { get; set; }
        public Nullable<decimal> WashCnt { get; set; }
        public Nullable<decimal> ef_tothour { get; set; }
        public decimal ef_ehour { get; set; }
        public Nullable<decimal> WashEff { get; set; }
        public Nullable<decimal> ef_hour { get; set; }
        public int BrokenCnt { get; set; }
        public decimal gn_qty8 { get; set; }
        public Nullable<decimal> Usage8 { get; set; }
        public decimal gn_qty3 { get; set; }
        public Nullable<decimal> Usage3 { get; set; }
        public decimal Award1 { get; set; }
        public int Award2 { get; set; }
        public decimal Award3 { get; set; }
        public Nullable<decimal> Award4 { get; set; }
        public Nullable<decimal> Cut1 { get; set; }
        public Nullable<decimal> Cut2 { get; set; }
        public decimal Cut3 { get; set; }
        public int Cut4 { get; set; }
    }
}
