//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_secb08_01
    {
        public string name { get; set; }
        public Nullable<decimal> s1 { get; set; }
        public Nullable<decimal> s2 { get; set; }
        public Nullable<decimal> r1 { get; set; }
        public Nullable<decimal> s3 { get; set; }
        public Nullable<decimal> s4 { get; set; }
        public Nullable<decimal> r2 { get; set; }
        public Nullable<decimal> s5 { get; set; }
        public Nullable<decimal> s6 { get; set; }
        public Nullable<decimal> s7 { get; set; }
        public Nullable<decimal> r3 { get; set; }
        public Nullable<decimal> s8 { get; set; }
        public string dpno { get; set; }
        public decimal sn_totalnt { get; set; }
    }
}
