//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sesa11_01
    {
        public string im_dpno { get; set; }
        public string im_cuno { get; set; }
        public string im_emno { get; set; }
        public string im_cusname { get; set; }
        public string im_inno { get; set; }
        public string id_cupdno { get; set; }
        public string id_pdno { get; set; }
        public Nullable<decimal> id_amt { get; set; }
        public Nullable<System.DateTime> id_date { get; set; }
        public Nullable<System.DateTime> id_tdate { get; set; }
        public int Kind { get; set; }
        public int OverStatus { get; set; }
        public int OverToday { get; set; }
    }
}
