//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_StdPaperUsed
    {
        public string YM { get; set; }
        public string mo_dpno { get; set; }
        public string pv_mkno { get; set; }
        public string mt_spec { get; set; }
        public string pv_setno { get; set; }
        public string pv_mtno { get; set; }
        public string bs_wno { get; set; }
        public Nullable<decimal> bs_plen { get; set; }
        public Nullable<decimal> bs_pwid { get; set; }
        public decimal ChooseLen { get; set; }
        public decimal ChooseWid { get; set; }
        public Nullable<decimal> mo_mpaper { get; set; }
        public Nullable<decimal> Accamt { get; set; }
    }
}
