//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_tinvoice
    {
        public decimal th_seqno { get; set; }
        public string th_no { get; set; }
        public string th_inhno { get; set; }
        public Nullable<System.DateTime> th_inhdate { get; set; }
        public Nullable<System.DateTime> th_date { get; set; }
        public string th_cuno { get; set; }
        public string th_tno { get; set; }
        public Nullable<System.DateTime> th_ddate { get; set; }
        public string th_pdno { get; set; }
        public string th_cupdno { get; set; }
        public string th_mailway { get; set; }
        public decimal th_mailamt { get; set; }
        public string th_memo { get; set; }
        public string th_pname { get; set; }
        public decimal th_qty { get; set; }
        public decimal th_price { get; set; }
        public decimal th_amt { get; set; }
        public string th_inhcurr { get; set; }
        public decimal th_post { get; set; }
        public decimal th_kind { get; set; }
        public string th_SNO1 { get; set; }
        public string th_SNO2 { get; set; }
        public decimal th_SeaKind { get; set; }
        public decimal th_amtO { get; set; }
        public decimal th_excrate { get; set; }
        public string th_ym { get; set; }
    }
}
