//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_worksch07
    {
        public decimal bc_seqno { get; set; }
        public string bc_dpno { get; set; }
        public string dp_name { get; set; }
        public string bc_emno1 { get; set; }
        public string rgb_cname1 { get; set; }
        public Nullable<System.DateTime> bc_date1 { get; set; }
        public string bc_mkno1 { get; set; }
        public string bc_setno1 { get; set; }
        public Nullable<decimal> bc_carqty1 { get; set; }
        public string bc_emno2 { get; set; }
        public string rgb_cname2 { get; set; }
        public Nullable<System.DateTime> bc_date2 { get; set; }
        public string bc_mkno2 { get; set; }
        public string bc_setno2 { get; set; }
        public Nullable<decimal> bc_carqty2 { get; set; }
        public Nullable<decimal> bc_post { get; set; }
        public Nullable<System.DateTime> bc_cdate { get; set; }
        public string bc_cemno { get; set; }
        public string em_cname { get; set; }
        public decimal NeedCount { get; set; }
        public string bc_reason { get; set; }
    }
}
