//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_M
    {
        public decimal vm_seqno { get; set; }
        public string vm_carno { get; set; }
        public Nullable<System.DateTime> vm_date { get; set; }
        public string vm_emno { get; set; }
        public string vm_name { get; set; }
        public Nullable<decimal> vm_item { get; set; }
        public Nullable<decimal> vm_trip1 { get; set; }
        public Nullable<decimal> vm_trip2 { get; set; }
        public Nullable<decimal> vm_trip { get; set; }
        public Nullable<decimal> vm_oiladd { get; set; }
        public Nullable<decimal> vm_ocost { get; set; }
        public Nullable<decimal> vm_mcost { get; set; }
        public string vm_memo { get; set; }
        public string vm_OilInv { get; set; }
        public string vm_tyno { get; set; }
    }
}
