//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vouch
    {
        public string compid { get; set; }
        public string vh_year { get; set; }
        public string vh_month { get; set; }
        public string vh_no { get; set; }
        public string vh_inno { get; set; }
        public Nullable<System.DateTime> vh_date { get; set; }
        public Nullable<decimal> vh_db { get; set; }
        public Nullable<decimal> vh_cr { get; set; }
        public Nullable<decimal> vh_kind { get; set; }
        public Nullable<decimal> vh_10 { get; set; }
        public Nullable<decimal> vh_11 { get; set; }
        public Nullable<decimal> vh_12 { get; set; }
        public string vh_13 { get; set; }
        public string vh_14 { get; set; }
        public string vh_15 { get; set; }
        public Nullable<System.DateTime> vh_16 { get; set; }
        public string vh_17 { get; set; }
        public Nullable<System.DateTime> vh_18 { get; set; }
        public Nullable<decimal> vh_19 { get; set; }
        public Nullable<decimal> vh_20 { get; set; }
        public Nullable<decimal> vh_21 { get; set; }
        public string vh_descs { get; set; }
        public string vh_memos { get; set; }
        public string updid { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public byte[] timestamp_column { get; set; }
    }
}
