//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wordchg
    {
        public string woc_mkno { get; set; }
        public System.DateTime woc_modday { get; set; }
        public string woc_setno { get; set; }
        public decimal woc_qty { get; set; }
        public decimal woc_mpaper { get; set; }
        public System.DateTime woc_spdate { get; set; }
        public Nullable<decimal> woc_yn { get; set; }
        public string woc_reason { get; set; }
        public Nullable<decimal> woc_post { get; set; }
        public Nullable<decimal> woc_oqty { get; set; }
        public Nullable<decimal> woc_omaper { get; set; }
        public Nullable<System.DateTime> woc_ospate { get; set; }
        public Nullable<decimal> woc_oyn { get; set; }
        public decimal woc_seq { get; set; }
        public string woc_emno { get; set; }
        public Nullable<System.DateTime> woc_HandleTime { get; set; }
        public decimal woc_ver { get; set; }
        public string woc_vemno { get; set; }
        public Nullable<System.DateTime> woc_vdate { get; set; }
        public decimal woc_mpaper1 { get; set; }
        public decimal woc_mpaper2 { get; set; }
        public decimal woc_mpaper3 { get; set; }
        public decimal woc_ompaper1 { get; set; }
        public decimal woc_ompaper2 { get; set; }
        public decimal woc_ompaper3 { get; set; }
        public decimal woc_reqqty { get; set; }
        public string woc_DelReason { get; set; }
        public decimal woc_adjqty { get; set; }
        public decimal woc_times { get; set; }
    }
}
