//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws
    {
        public string ws_no { get; set; }
        public string ws_name { get; set; }
        public string ws_machine { get; set; }
        public Nullable<decimal> ws_num { get; set; }
        public Nullable<decimal> ws_kind { get; set; }
    }
}
