//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ymcheck
    {
        public System.DateTime yc_date { get; set; }
        public string yc_emno { get; set; }
        public string yc_ceno1 { get; set; }
        public string yc_ceno2 { get; set; }
        public Nullable<decimal> yc_ranum { get; set; }
        public Nullable<decimal> yc_yn { get; set; }
    }
}
