//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ypesta
    {
        public string yp_ym { get; set; }
        public string yp_emno { get; set; }
        public string yp_dpno { get; set; }
        public string yp_ws { get; set; }
        public Nullable<decimal> yp_pmtime { get; set; }
        public Nullable<decimal> yp_caramt { get; set; }
        public Nullable<decimal> yp_tcamt { get; set; }
        public Nullable<decimal> yp_whour { get; set; }
        public Nullable<decimal> yp_avcamt { get; set; }
        public Nullable<decimal> yp_amt { get; set; }
        public Nullable<decimal> yp_rw { get; set; }
        public Nullable<decimal> yp_exhour { get; set; }
        public Nullable<decimal> yp_dhour { get; set; }
        public Nullable<decimal> yp_gcamt { get; set; }
        public Nullable<decimal> yp_brw { get; set; }
        public Nullable<decimal> yp_dir { get; set; }
        public Nullable<decimal> yp_wamt { get; set; }
        public decimal yp_bad1 { get; set; }
        public decimal yp_bad2 { get; set; }
        public decimal yp_bad3 { get; set; }
        public decimal yp_totalnet { get; set; }
        public decimal yp_twhour { get; set; }
        public decimal yp_lostmoney { get; set; }
        public decimal yp_PowerAmt { get; set; }
        public decimal yp_PowerAward { get; set; }
        public decimal yp_PowerCar { get; set; }
        public decimal yp_PowerCarT { get; set; }
        public decimal yp_PowerHour { get; set; }
        public decimal yp_sphour { get; set; }
        public decimal yp_NewAward1 { get; set; }
        public decimal yp_NewAward2 { get; set; }
        public decimal yp_NewAward3 { get; set; }
        public decimal yp_GoodRate { get; set; }
        public decimal yp_EffCarQty { get; set; }
        public decimal yp_ShiftAward { get; set; }
    }
}
